# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ff7cb545855d89c3983e319c3dfad1971ab0707a2bd3835327f6853ed31cdde
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  defstruct text: "",
            kind: :line,
            span: nil,
            associated_node: ""
end
