# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:39622037a97662b67613ca920b8c0b654207ccab236e91263dd152e081a23f09
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CommentKind do
  @moduledoc "The kind of a comment found in source code."

  @type t :: :line | :block | :doc

  @line :line
  @block :block
  @doc_attr :doc

  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec doc() :: t()
  def doc, do: @doc_attr
end
