# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @typedoc "A diagnostic (syntax error, missing node, etc.) from parsing."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          severity: String.t() | nil,
          span: map()
        }

  defstruct message: nil,
            severity: :error,
            span: nil
end
