# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f32a05c55950f7ffcaeebe00bb7693bad88dde726bd1a3a84e65d75dfa90846b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule TreeSitterLanguagePack.DocstringFormat do
  @moduledoc """
  The format of a docstring extracted from source code.

  Identifies the docstring convention used, which varies by language
  (e.g., Python triple-quoted strings, JSDoc, Rustdoc `///` comments).
  """

  @typedoc "The format of a docstring extracted from source code."
  @type t :: term()

  @type python_triple_quote :: :python_triple_quote
  @type js_doc :: :js_doc
  @type rustdoc :: :rustdoc
  @type go_doc :: :go_doc
  @type java_doc :: :java_doc
  @type other :: %{type: :other, value: String.t()}
end
