# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.ExportKind do
  @moduledoc """
  The kind of an export statement found in source code.

  Covers named exports, default exports, and re-exports from other modules.
  """

  @typedoc "The kind of an export statement found in source code."
  @type t :: :named | :default | :re_export

  @named :named
  @default :default
  @re_export :re_export

  @spec named() :: t()
  def named, do: @named
  @spec default() :: t()
  def default, do: @default
  @spec re_export() :: t()
  def re_export, do: @re_export
end
