# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ee275465d8d01a9c08f56e20d5dfa651f97a9ad19dc85beb5b7c36021db3bb6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.FileMetrics do
  @moduledoc "Aggregate metrics for a source file."

  defstruct total_lines: 0,
            code_lines: 0,
            comment_lines: 0,
            blank_lines: 0,
            total_bytes: 0,
            node_count: 0,
            error_count: 0,
            max_depth: 0
end
