# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:784d27f93731854d18c43dcb00f35d51a222b4d9e461c8d31f9eb5d26755a612
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ImportInfo do
  @moduledoc "An import statement extracted from source code."

  @typedoc "An import statement extracted from source code."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          items: [String.t()],
          alias: String.t() | nil,
          is_wildcard: boolean(),
          span: map()
        }

  defstruct source: nil,
            items: [],
            alias: nil,
            is_wildcard: false,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
