# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ea06239ccf2e773db8bf6adadae12444e91bc5afde9a545cf65578512e562e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
