# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb4f7b93b97d64c44a784ad899298b669e39b6206b05af6fee6923b09f137f69
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.StructureKind do
  @moduledoc """
  The kind of structural item found in source code.

  Categorizes top-level and nested declarations such as functions, classes,
  structs, enums, traits, and more. Use [`Other`](StructureKind::Other) for
  language-specific constructs that do not fit a standard category.

  # Wire format (public JSON contract)

  Unit variants serialize as a bare string (`"Function"`); the `Other`
  variant serializes as a single-keyed object (`{"Other": "macro"}`). DO
  NOT add `#[serde(tag = "...")]` or rename variants — every language
  binding has a hand-written deserializer matching this exact shape, and
  any change breaks all bindings' `process()` tests simultaneously.
  Covered by `tests/wire_format.rs`.
  """

  @typedoc "The kind of structural item found in source code."
  @type t :: term()

  @typedoc "A free-standing or associated function."
  @type function_variant :: :function
  @typedoc "A method defined inside a class, struct, trait, or impl block."
  @type method :: :method
  @typedoc "A class definition."
  @type class :: :class
  @typedoc "A struct definition."
  @type struct_variant :: :struct
  @typedoc "An interface or protocol definition."
  @type interface :: :interface
  @typedoc "An enum definition."
  @type enum :: :enum
  @typedoc "A module or package declaration."
  @type module_variant :: :module
  @typedoc "A trait definition."
  @type trait :: :trait
  @typedoc "An impl block (Rust) or similar implementation block."
  @type impl :: :impl
  @typedoc "A namespace declaration."
  @type namespace :: :namespace
  @typedoc "A language-specific construct that does not fit any standard category."
  @type other :: %{type: :other, value: String.t()}
end
