# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:183b7ba042864aaa85f21ed53834d20ee553819cafa541d8ca35a2f5c48e5886
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.SymbolKind do
  @moduledoc """
  The kind of a symbol definition found in source code.

  Categorizes symbol definitions such as variables, constants, functions,
  classes, types, interfaces, enums, and modules.
  """

  @typedoc "The kind of a symbol definition found in source code."
  @type t :: term()

  @type variable :: :variable
  @type constant :: :constant
  @type function_variant :: :function
  @type class :: :class
  @type type :: :type
  @type interface :: :interface
  @type enum :: :enum
  @type module_variant :: :module
  @type other :: %{type: :other, value: String.t()}
end
