# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6c258a20ebfddd074592606d754e7ca338d9ae406fd413fe81e0164d67af105a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.SymbolKind do
  @moduledoc """
  The kind of a symbol definition found in source code.

  Categorizes symbol definitions such as variables, constants, functions,
  classes, types, interfaces, enums, and modules.
  """

  @typedoc "The kind of a symbol definition found in source code."
  @type t :: term()

  @typedoc "A variable binding."
  @type variable :: :variable
  @typedoc "A constant (immutable binding)."
  @type constant :: :constant
  @typedoc "A function definition."
  @type function_variant :: :function
  @typedoc "A class definition."
  @type class :: :class
  @typedoc "A type alias or typedef."
  @type type :: :type
  @typedoc "An interface definition."
  @type interface :: :interface
  @typedoc "An enum definition."
  @type enum :: :enum
  @typedoc "A module declaration."
  @type module_variant :: :module
  @typedoc "A symbol kind not covered by the standard variants."
  @type other :: %{type: :other, value: String.t()}
end
