// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb4f7b93b97d64c44a784ad899298b669e39b6206b05af6fee6923b09f137f69
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
