// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:68ddaefc3c842a8c73d8eb3b5a0efa0e0de4269cfb2e1ca487d9dc46b1928969
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(unsafe_code)]
#![allow(non_snake_case)]
#![allow(
    clippy::too_many_arguments,
    clippy::let_unit_value,
    clippy::needless_borrow,
    clippy::map_identity,
    clippy::just_underscores_and_digits,
    clippy::unnecessary_cast,
    clippy::unused_unit,
    clippy::unwrap_or_default,
    clippy::derivable_impls,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_fallible_conversions,
    clippy::arc_with_non_send_sync,
    clippy::collapsible_if,
    clippy::clone_on_copy,
    clippy::should_implement_trait,
    clippy::useless_conversion
)]
#![cfg_attr(windows, feature(abi_vectorcall))]

use ext_php_rs::prelude::*;
use std::sync::Arc;
use std::sync::Mutex;

#[derive(Debug, Clone, Default)]
pub struct PhpBytes(pub Vec<u8>);

impl<'a> ext_php_rs::convert::FromZval<'a> for PhpBytes {
    const TYPE: ext_php_rs::flags::DataType = ext_php_rs::flags::DataType::String;
    fn from_zval(zval: &'a ext_php_rs::types::Zval) -> Option<Self> {
        zval.zend_str().map(|zs| PhpBytes(zs.as_bytes().to_vec()))
    }
}

impl From<PhpBytes> for Vec<u8> {
    fn from(b: PhpBytes) -> Self {
        b.0
    }
}

impl From<Vec<u8>> for PhpBytes {
    fn from(v: Vec<u8>) -> Self {
        PhpBytes(v)
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Span")]
#[serde(default, rename_all = "camelCase")]
pub struct Span {
    #[php(prop, name = "startByte")]
    pub start_byte: i64,
    #[php(prop, name = "endByte")]
    pub end_byte: i64,
    #[php(prop, name = "startLine")]
    pub start_line: i64,
    #[php(prop, name = "startColumn")]
    pub start_column: i64,
    #[php(prop, name = "endLine")]
    pub end_line: i64,
    #[php(prop, name = "endColumn")]
    pub end_column: i64,
}

#[php_impl]
impl Span {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(startByte: i64, endByte: i64, startLine: i64, startColumn: i64, endLine: i64, endColumn: i64) -> Self {
        Self {
            start_byte: startByte,
            end_byte: endByte,
            start_line: startLine,
            start_column: startColumn,
            end_line: endLine,
            end_column: endColumn,
        }
    }

    pub fn get_start_byte(&self) -> i64 {
        self.start_byte.clone()
    }

    pub fn get_end_byte(&self) -> i64 {
        self.end_byte.clone()
    }

    pub fn get_start_line(&self) -> i64 {
        self.start_line.clone()
    }

    pub fn get_start_column(&self) -> i64 {
        self.start_column.clone()
    }

    pub fn get_end_line(&self) -> i64 {
        self.end_line.clone()
    }

    pub fn get_end_column(&self) -> i64 {
        self.end_column.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ProcessResult")]
#[serde(default, rename_all = "camelCase")]
#[allow(clippy::similar_names)]
pub struct ProcessResult {
    #[php(prop, name = "language")]
    pub language: String,
    pub metrics: FileMetrics,
    pub structure: Vec<StructureItem>,
    pub imports: Vec<ImportInfo>,
    pub exports: Vec<ExportInfo>,
    pub comments: Vec<CommentInfo>,
    pub docstrings: Vec<DocstringInfo>,
    pub symbols: Vec<SymbolInfo>,
    pub diagnostics: Vec<Diagnostic>,
    pub chunks: Vec<CodeChunk>,
}

#[php_impl]
impl ProcessResult {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(language: String) -> Self {
        Self {
            language,
            metrics: Default::default(),
            structure: Default::default(),
            imports: Default::default(),
            exports: Default::default(),
            comments: Default::default(),
            docstrings: Default::default(),
            symbols: Default::default(),
            diagnostics: Default::default(),
            chunks: Default::default(),
        }
    }

    pub fn get_language(&self) -> String {
        self.language.clone()
    }

    pub fn get_metrics(&self) -> FileMetrics {
        self.metrics.clone()
    }

    pub fn get_structure(&self) -> Vec<StructureItem> {
        self.structure.clone()
    }

    pub fn get_imports(&self) -> Vec<ImportInfo> {
        self.imports.clone()
    }

    pub fn get_exports(&self) -> Vec<ExportInfo> {
        self.exports.clone()
    }

    pub fn get_comments(&self) -> Vec<CommentInfo> {
        self.comments.clone()
    }

    pub fn get_docstrings(&self) -> Vec<DocstringInfo> {
        self.docstrings.clone()
    }

    pub fn get_symbols(&self) -> Vec<SymbolInfo> {
        self.symbols.clone()
    }

    pub fn get_diagnostics(&self) -> Vec<Diagnostic> {
        self.diagnostics.clone()
    }

    pub fn get_chunks(&self) -> Vec<CodeChunk> {
        self.chunks.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\FileMetrics")]
#[serde(default, rename_all = "camelCase")]
pub struct FileMetrics {
    #[php(prop, name = "totalLines")]
    pub total_lines: i64,
    #[php(prop, name = "codeLines")]
    pub code_lines: i64,
    #[php(prop, name = "commentLines")]
    pub comment_lines: i64,
    #[php(prop, name = "blankLines")]
    pub blank_lines: i64,
    #[php(prop, name = "totalBytes")]
    pub total_bytes: i64,
    #[php(prop, name = "nodeCount")]
    pub node_count: i64,
    #[php(prop, name = "errorCount")]
    pub error_count: i64,
    #[php(prop, name = "maxDepth")]
    pub max_depth: i64,
}

#[php_impl]
impl FileMetrics {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(
        totalLines: i64,
        codeLines: i64,
        commentLines: i64,
        blankLines: i64,
        totalBytes: i64,
        nodeCount: i64,
        errorCount: i64,
        maxDepth: i64,
    ) -> Self {
        Self {
            total_lines: totalLines,
            code_lines: codeLines,
            comment_lines: commentLines,
            blank_lines: blankLines,
            total_bytes: totalBytes,
            node_count: nodeCount,
            error_count: errorCount,
            max_depth: maxDepth,
        }
    }

    pub fn get_total_lines(&self) -> i64 {
        self.total_lines.clone()
    }

    pub fn get_code_lines(&self) -> i64 {
        self.code_lines.clone()
    }

    pub fn get_comment_lines(&self) -> i64 {
        self.comment_lines.clone()
    }

    pub fn get_blank_lines(&self) -> i64 {
        self.blank_lines.clone()
    }

    pub fn get_total_bytes(&self) -> i64 {
        self.total_bytes.clone()
    }

    pub fn get_node_count(&self) -> i64 {
        self.node_count.clone()
    }

    pub fn get_error_count(&self) -> i64 {
        self.error_count.clone()
    }

    pub fn get_max_depth(&self) -> i64 {
        self.max_depth.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\StructureItem")]
#[serde(default, rename_all = "camelCase")]
pub struct StructureItem {
    #[php(prop, name = "kind")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub kind: String,
    #[php(prop, name = "name")]
    pub name: Option<String>,
    #[php(prop, name = "visibility")]
    pub visibility: Option<String>,
    pub span: Span,
    pub children: Vec<StructureItem>,
    #[php(prop, name = "decorators")]
    pub decorators: Vec<String>,
    #[php(prop, name = "docComment")]
    pub doc_comment: Option<String>,
    #[php(prop, name = "signature")]
    pub signature: Option<String>,
    pub body_span: Option<Span>,
}

#[php_impl]
impl StructureItem {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(
        kind: String,
        name: Option<String>,
        visibility: Option<String>,
        decorators: Vec<String>,
        docComment: Option<String>,
        signature: Option<String>,
    ) -> Self {
        Self {
            kind,
            name,
            visibility,
            span: Default::default(),
            children: Default::default(),
            decorators,
            doc_comment: docComment,
            signature,
            body_span: Default::default(),
        }
    }

    pub fn get_kind(&self) -> String {
        self.kind.clone()
    }

    pub fn get_name(&self) -> Option<String> {
        self.name.clone()
    }

    pub fn get_visibility(&self) -> Option<String> {
        self.visibility.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }

    pub fn get_children(&self) -> Vec<StructureItem> {
        self.children.clone()
    }

    pub fn get_decorators(&self) -> Vec<String> {
        self.decorators.clone()
    }

    pub fn get_doc_comment(&self) -> Option<String> {
        self.doc_comment.clone()
    }

    pub fn get_signature(&self) -> Option<String> {
        self.signature.clone()
    }

    pub fn get_body_span(&self) -> Option<Span> {
        self.body_span.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\CommentInfo")]
#[serde(default, rename_all = "camelCase")]
pub struct CommentInfo {
    #[php(prop, name = "text")]
    pub text: String,
    #[php(prop, name = "kind")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub kind: String,
    pub span: Span,
    #[php(prop, name = "associatedNode")]
    pub associated_node: Option<String>,
}

#[php_impl]
impl CommentInfo {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(text: String, kind: String, associatedNode: Option<String>) -> Self {
        Self {
            text,
            kind,
            span: Default::default(),
            associated_node: associatedNode,
        }
    }

    pub fn get_text(&self) -> String {
        self.text.clone()
    }

    pub fn get_kind(&self) -> String {
        self.kind.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }

    pub fn get_associated_node(&self) -> Option<String> {
        self.associated_node.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\DocstringInfo")]
#[serde(default, rename_all = "camelCase")]
pub struct DocstringInfo {
    #[php(prop, name = "text")]
    pub text: String,
    #[php(prop, name = "format")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub format: String,
    pub span: Span,
    #[php(prop, name = "associatedItem")]
    pub associated_item: Option<String>,
    pub parsed_sections: Vec<DocSection>,
}

#[php_impl]
impl DocstringInfo {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(text: String, format: String, associatedItem: Option<String>) -> Self {
        Self {
            text,
            format,
            span: Default::default(),
            associated_item: associatedItem,
            parsed_sections: Default::default(),
        }
    }

    pub fn get_text(&self) -> String {
        self.text.clone()
    }

    pub fn get_format(&self) -> String {
        self.format.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }

    pub fn get_associated_item(&self) -> Option<String> {
        self.associated_item.clone()
    }

    pub fn get_parsed_sections(&self) -> Vec<DocSection> {
        self.parsed_sections.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\DocSection")]
#[serde(default, rename_all = "camelCase")]
pub struct DocSection {
    #[php(prop, name = "kind")]
    pub kind: String,
    #[php(prop, name = "name")]
    pub name: Option<String>,
    #[php(prop, name = "description")]
    pub description: String,
}

#[php_impl]
impl DocSection {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(kind: String, name: Option<String>, description: String) -> Self {
        Self {
            kind,
            name,
            description,
        }
    }

    pub fn get_kind(&self) -> String {
        self.kind.clone()
    }

    pub fn get_name(&self) -> Option<String> {
        self.name.clone()
    }

    pub fn get_description(&self) -> String {
        self.description.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ImportInfo")]
#[serde(default, rename_all = "camelCase")]
pub struct ImportInfo {
    #[php(prop, name = "source")]
    pub source: String,
    #[php(prop, name = "items")]
    pub items: Vec<String>,
    #[php(prop, name = "alias")]
    pub alias: Option<String>,
    #[php(prop, name = "isWildcard")]
    pub is_wildcard: bool,
    pub span: Span,
}

#[php_impl]
impl ImportInfo {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(source: String, items: Vec<String>, alias: Option<String>, isWildcard: bool) -> Self {
        Self {
            source,
            items,
            alias,
            is_wildcard: isWildcard,
            span: Default::default(),
        }
    }

    pub fn get_source(&self) -> String {
        self.source.clone()
    }

    pub fn get_items(&self) -> Vec<String> {
        self.items.clone()
    }

    pub fn get_alias(&self) -> Option<String> {
        self.alias.clone()
    }

    pub fn get_is_wildcard(&self) -> bool {
        self.is_wildcard.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ExportInfo")]
#[serde(default, rename_all = "camelCase")]
pub struct ExportInfo {
    #[php(prop, name = "name")]
    pub name: String,
    #[php(prop, name = "kind")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub kind: String,
    pub span: Span,
}

#[php_impl]
impl ExportInfo {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(name: String, kind: String) -> Self {
        Self {
            name,
            kind,
            span: Default::default(),
        }
    }

    pub fn get_name(&self) -> String {
        self.name.clone()
    }

    pub fn get_kind(&self) -> String {
        self.kind.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\SymbolInfo")]
#[serde(default, rename_all = "camelCase")]
pub struct SymbolInfo {
    #[php(prop, name = "name")]
    pub name: String,
    #[php(prop, name = "kind")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub kind: String,
    pub span: Span,
    #[php(prop, name = "typeAnnotation")]
    pub type_annotation: Option<String>,
    #[php(prop, name = "doc")]
    pub doc: Option<String>,
}

#[php_impl]
impl SymbolInfo {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(name: String, kind: String, typeAnnotation: Option<String>, doc: Option<String>) -> Self {
        Self {
            name,
            kind,
            span: Default::default(),
            type_annotation: typeAnnotation,
            doc,
        }
    }

    pub fn get_name(&self) -> String {
        self.name.clone()
    }

    pub fn get_kind(&self) -> String {
        self.kind.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }

    pub fn get_type_annotation(&self) -> Option<String> {
        self.type_annotation.clone()
    }

    pub fn get_doc(&self) -> Option<String> {
        self.doc.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Diagnostic")]
#[serde(default, rename_all = "camelCase")]
pub struct Diagnostic {
    #[php(prop, name = "message")]
    pub message: String,
    #[php(prop, name = "severity")]
    #[serde(skip_serializing_if = "String::is_empty")]
    pub severity: String,
    pub span: Span,
}

#[php_impl]
impl Diagnostic {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(message: String, severity: String) -> Self {
        Self {
            message,
            severity,
            span: Default::default(),
        }
    }

    pub fn get_message(&self) -> String {
        self.message.clone()
    }

    pub fn get_severity(&self) -> String {
        self.severity.clone()
    }

    pub fn get_span(&self) -> Span {
        self.span.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\CodeChunk")]
#[serde(default, rename_all = "camelCase")]
pub struct CodeChunk {
    #[php(prop, name = "content")]
    pub content: String,
    #[php(prop, name = "startByte")]
    pub start_byte: i64,
    #[php(prop, name = "endByte")]
    pub end_byte: i64,
    #[php(prop, name = "startLine")]
    pub start_line: i64,
    #[php(prop, name = "endLine")]
    pub end_line: i64,
    pub metadata: ChunkContext,
}

#[php_impl]
impl CodeChunk {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(content: String, startByte: i64, endByte: i64, startLine: i64, endLine: i64) -> Self {
        Self {
            content,
            start_byte: startByte,
            end_byte: endByte,
            start_line: startLine,
            end_line: endLine,
            metadata: Default::default(),
        }
    }

    pub fn get_content(&self) -> String {
        self.content.clone()
    }

    pub fn get_start_byte(&self) -> i64 {
        self.start_byte.clone()
    }

    pub fn get_end_byte(&self) -> i64 {
        self.end_byte.clone()
    }

    pub fn get_start_line(&self) -> i64 {
        self.start_line.clone()
    }

    pub fn get_end_line(&self) -> i64 {
        self.end_line.clone()
    }

    pub fn get_metadata(&self) -> ChunkContext {
        self.metadata.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ChunkContext")]
#[serde(default, rename_all = "camelCase")]
pub struct ChunkContext {
    #[php(prop, name = "language")]
    pub language: String,
    #[php(prop, name = "chunkIndex")]
    pub chunk_index: i64,
    #[php(prop, name = "totalChunks")]
    pub total_chunks: i64,
    #[php(prop, name = "nodeTypes")]
    pub node_types: Vec<String>,
    #[php(prop, name = "contextPath")]
    pub context_path: Vec<String>,
    #[php(prop, name = "symbolsDefined")]
    pub symbols_defined: Vec<String>,
    pub comments: Vec<CommentInfo>,
    pub docstrings: Vec<DocstringInfo>,
    #[php(prop, name = "hasErrorNodes")]
    pub has_error_nodes: bool,
}

#[php_impl]
impl ChunkContext {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(
        language: String,
        chunkIndex: i64,
        totalChunks: i64,
        nodeTypes: Vec<String>,
        contextPath: Vec<String>,
        symbolsDefined: Vec<String>,
        hasErrorNodes: bool,
    ) -> Self {
        Self {
            language,
            chunk_index: chunkIndex,
            total_chunks: totalChunks,
            node_types: nodeTypes,
            context_path: contextPath,
            symbols_defined: symbolsDefined,
            comments: Default::default(),
            docstrings: Default::default(),
            has_error_nodes: hasErrorNodes,
        }
    }

    pub fn get_language(&self) -> String {
        self.language.clone()
    }

    pub fn get_chunk_index(&self) -> i64 {
        self.chunk_index.clone()
    }

    pub fn get_total_chunks(&self) -> i64 {
        self.total_chunks.clone()
    }

    pub fn get_node_types(&self) -> Vec<String> {
        self.node_types.clone()
    }

    pub fn get_context_path(&self) -> Vec<String> {
        self.context_path.clone()
    }

    pub fn get_symbols_defined(&self) -> Vec<String> {
        self.symbols_defined.clone()
    }

    pub fn get_comments(&self) -> Vec<CommentInfo> {
        self.comments.clone()
    }

    pub fn get_docstrings(&self) -> Vec<DocstringInfo> {
        self.docstrings.clone()
    }

    pub fn get_has_error_nodes(&self) -> bool {
        self.has_error_nodes.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\PackConfig")]
#[serde(default, rename_all = "camelCase")]
pub struct PackConfig {
    /// Override default cache directory.
    ///
    /// Default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`
    #[php(prop, name = "cacheDir")]
    pub cache_dir: Option<String>,
    /// Languages to pre-download on init.
    ///
    /// Each entry is a language name (e.g. `"python"`, `"rust"`).
    #[php(prop, name = "languages")]
    pub languages: Option<Vec<String>>,
    /// Language groups to pre-download (e.g. `"web"`, `"systems"`, `"scripting"`).
    #[php(prop, name = "groups")]
    pub groups: Option<Vec<String>>,
}

#[php_impl]
impl PackConfig {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    pub fn get_cache_dir(&self) -> Option<String> {
        self.cache_dir.clone()
    }

    pub fn get_languages(&self) -> Option<Vec<String>> {
        self.languages.clone()
    }

    pub fn get_groups(&self) -> Option<Vec<String>> {
        self.groups.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Point")]
#[serde(default, rename_all = "camelCase")]
pub struct Point {
    /// Zero-indexed row number.
    #[php(prop, name = "row")]
    pub row: i64,
    /// Zero-indexed column number, in UTF-16 code units.
    #[php(prop, name = "column")]
    pub column: i64,
}

#[php_impl]
impl Point {
    #[php(constructor)]
    pub fn new(row: i64, column: i64) -> Self {
        Self { row, column }
    }

    pub fn get_row(&self) -> i64 {
        self.row.clone()
    }

    pub fn get_column(&self) -> i64 {
        self.column.clone()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ByteRange")]
#[serde(default, rename_all = "camelCase")]
pub struct ByteRange {
    /// Inclusive start byte offset.
    #[php(prop, name = "start")]
    pub start: i64,
    /// Exclusive end byte offset.
    #[php(prop, name = "end")]
    pub end: i64,
}

#[php_impl]
impl ByteRange {
    #[php(constructor)]
    pub fn new(start: i64, end: i64) -> Self {
        Self { start, end }
    }

    pub fn get_start(&self) -> i64 {
        self.start.clone()
    }

    pub fn get_end(&self) -> i64 {
        self.end.clone()
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Parser")]
pub struct Parser {
    inner: Arc<std::sync::Mutex<tree_sitter_language_pack::Parser>>,
}

#[php_impl]
impl Parser {
    /**
     * Configure the parser to use the language identified by name (e.g. `"python"`).
     *
     * Resolves the language through the global registry — auto-downloading
     * if necessary, when the `download` feature is enabled.
     * @throws TreeSitterLanguagePackException Returns `Error.LanguageNotFound` if the language is not recognized,
     * or `Error.ParserSetup` if the language ABI is incompatible.
     */
    pub fn set_language(&self, name: String) -> PhpResult<()> {
        self.inner
            .lock()
            .unwrap()
            .set_language(&name)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(())
    }

    /**
     * Parse a UTF-8 source string. Returns `None` if parsing was cancelled
     * or no language is set.
     */
    pub fn parse(&self, source: String) -> Option<Tree> {
        self.inner
            .lock()
            .unwrap()
            .parse(&source)
            .map(|v| Tree { inner: Arc::new(v) })
    }

    /**
     * Parse a raw byte slice. Returns `None` if parsing was cancelled or
     * no language is set.
     */
    pub fn parse_bytes(&self, source: PhpBytes) -> Option<Tree> {
        self.inner
            .lock()
            .unwrap()
            .parse_bytes(&source.0[..])
            .map(|v| Tree { inner: Arc::new(v) })
    }

    /**
     * Reset internal state. The next call to `parse`(Self.parse) will
     * not be incremental.
     */
    pub fn reset(&self) {
        self.inner.lock().unwrap().reset()
    }

    #[allow(clippy::should_implement_trait)]
    pub fn default() -> Parser {
        Self {
            inner: Arc::new(std::sync::Mutex::new(tree_sitter_language_pack::Parser::default())),
        }
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Tree")]
pub struct Tree {
    inner: Arc<tree_sitter_language_pack::Tree>,
}

#[php_impl]
impl Tree {
    /**
     * Return the root `Node` of this tree.
     */
    pub fn root_node(&self) -> Node {
        Node {
            inner: Arc::new(self.inner.root_node()),
        }
    }

    /**
     * Return a `TreeCursor` positioned at the root.
     */
    pub fn walk(&self) -> TreeCursor {
        TreeCursor {
            inner: Arc::new(std::sync::Mutex::new(self.inner.walk())),
        }
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Node")]
pub struct Node {
    inner: Arc<tree_sitter_language_pack::Node>,
}

#[php_impl]
impl Node {
    pub fn clone(&self) -> Node {
        Self {
            inner: self.inner.clone(),
        }
    }

    /**
     * Return the node's kind name (e.g. `"function_definition"`).
     */
    pub fn kind(&self) -> String {
        self.inner.kind()
    }

    /**
     * Return the node's numeric kind ID.
     *
     * Tree-sitter assigns a stable `u16` ID to every node kind in a grammar
     * (e.g. `"function_definition" → 42`). Comparing `kind_id()` is cheaper
     * than comparing the string `kind()`(Self.kind) in tight AST loops.
     */
    pub fn kind_id(&self) -> u16 {
        self.inner.kind_id()
    }

    /**
     * Return the inclusive start byte offset of this node.
     */
    pub fn start_byte(&self) -> i64 {
        self.inner.start_byte() as i64
    }

    /**
     * Return the exclusive end byte offset of this node.
     */
    pub fn end_byte(&self) -> i64 {
        self.inner.end_byte() as i64
    }

    /**
     * Return the node's byte range as a `ByteRange`.
     *
     * Callers should slice their own source bytes — this is a zero-copy
     * text accessor.
     */
    pub fn byte_range(&self) -> ByteRange {
        self.inner.byte_range().into()
    }

    /**
     * Return the start `Point` (row, column).
     */
    pub fn start_position(&self) -> Point {
        self.inner.start_position().into()
    }

    /**
     * Return the end `Point` (row, column).
     */
    pub fn end_position(&self) -> Point {
        self.inner.end_position().into()
    }

    /**
     * True when this node is named (not punctuation/whitespace).
     */
    pub fn is_named(&self) -> bool {
        self.inner.is_named()
    }

    /**
     * True when this is an error node.
     */
    pub fn is_error(&self) -> bool {
        self.inner.is_error()
    }

    /**
     * True when this is a missing-token node.
     */
    pub fn is_missing(&self) -> bool {
        self.inner.is_missing()
    }

    /**
     * True when this is an "extra" node (e.g. a comment).
     */
    pub fn is_extra(&self) -> bool {
        self.inner.is_extra()
    }

    /**
     * True when this node or any descendant is an error.
     */
    pub fn has_error(&self) -> bool {
        self.inner.has_error()
    }

    /**
     * Return this node's parent, if any.
     */
    pub fn parent(&self) -> Option<Node> {
        self.inner.parent().map(|v| Node { inner: Arc::new(v) })
    }

    /**
     * Return the i-th child of this node, if any.
     */
    pub fn child(&self, index: u32) -> Option<Node> {
        self.inner.child(index).map(|v| Node { inner: Arc::new(v) })
    }

    /**
     * Total number of children (including unnamed).
     */
    pub fn child_count(&self) -> i64 {
        self.inner.child_count() as i64
    }

    /**
     * Return the i-th named child of this node, if any.
     */
    pub fn named_child(&self, index: u32) -> Option<Node> {
        self.inner.named_child(index).map(|v| Node { inner: Arc::new(v) })
    }

    /**
     * Number of named children of this node.
     */
    pub fn named_child_count(&self) -> i64 {
        self.inner.named_child_count() as i64
    }

    /**
     * Look up a child by its grammar-defined field name.
     */
    pub fn child_by_field_name(&self, name: String) -> Option<Node> {
        self.inner
            .child_by_field_name(&name)
            .map(|v| Node { inner: Arc::new(v) })
    }

    /**
     * Return the S-expression form of this node's subtree.
     */
    pub fn to_sexp(&self) -> String {
        self.inner.to_sexp()
    }

    /**
     * Return a `TreeCursor` positioned at this node.
     */
    pub fn walk(&self) -> TreeCursor {
        TreeCursor {
            inner: Arc::new(std::sync::Mutex::new(self.inner.walk())),
        }
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\TreeCursor")]
pub struct TreeCursor {
    inner: Arc<std::sync::Mutex<tree_sitter_language_pack::TreeCursor>>,
}

#[php_impl]
impl TreeCursor {
    /**
     * Return the `Node` at the cursor's current position.
     */
    pub fn node(&self) -> Node {
        Node {
            inner: Arc::new(self.inner.lock().unwrap().node()),
        }
    }

    /**
     * Move the cursor to the first child of the current node.
     * Returns `true` if a child existed.
     */
    pub fn goto_first_child(&self) -> bool {
        self.inner.lock().unwrap().goto_first_child()
    }

    /**
     * Move the cursor to the parent of the current node.
     * Returns `true` if a parent existed.
     */
    pub fn goto_parent(&self) -> bool {
        self.inner.lock().unwrap().goto_parent()
    }

    /**
     * Move the cursor to the next sibling of the current node.
     * Returns `true` if a sibling existed.
     */
    pub fn goto_next_sibling(&self) -> bool {
        self.inner.lock().unwrap().goto_next_sibling()
    }

    /**
     * Return the field name for the current node, if any.
     */
    pub fn field_name(&self) -> Option<String> {
        self.inner.lock().unwrap().field_name()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize, Default)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\ProcessConfig")]
#[serde(default, rename_all = "camelCase")]
#[allow(clippy::similar_names)]
pub struct ProcessConfig {
    /// Language name (required).
    #[php(prop, name = "language")]
    pub language: String,
    /// Extract structural items (functions, classes, etc.). Default: true.
    #[php(prop, name = "structure")]
    #[serde(default = "crate::serde_defaults::bool_true")]
    pub structure: bool,
    /// Extract import statements. Default: true.
    #[php(prop, name = "imports")]
    #[serde(default = "crate::serde_defaults::bool_true")]
    pub imports: bool,
    /// Extract export statements. Default: true.
    #[php(prop, name = "exports")]
    #[serde(default = "crate::serde_defaults::bool_true")]
    pub exports: bool,
    /// Extract comments. Default: false.
    #[php(prop, name = "comments")]
    pub comments: bool,
    /// Extract docstrings. Default: false.
    #[php(prop, name = "docstrings")]
    pub docstrings: bool,
    /// Extract symbol definitions. Default: false.
    #[php(prop, name = "symbols")]
    pub symbols: bool,
    /// Include parse diagnostics. Default: false.
    #[php(prop, name = "diagnostics")]
    pub diagnostics: bool,
    /// Maximum chunk size in bytes. `None` disables chunking.
    #[php(prop, name = "chunkMaxSize")]
    pub chunk_max_size: Option<i64>,
}

#[php_impl]
impl ProcessConfig {
    #[php(name = "from_json")]
    pub fn from_json(json: String) -> PhpResult<Self> {
        serde_json::from_str(&json).map_err(|e| PhpException::default(e.to_string()))
    }

    #[php(constructor)]
    pub fn new(
        language: String,
        structure: bool,
        imports: bool,
        exports: bool,
        comments: bool,
        docstrings: bool,
        symbols: bool,
        diagnostics: bool,
        chunkMaxSize: Option<i64>,
    ) -> Self {
        Self {
            language,
            structure,
            imports,
            exports,
            comments,
            docstrings,
            symbols,
            diagnostics,
            chunk_max_size: chunkMaxSize,
        }
    }

    pub fn get_language(&self) -> String {
        self.language.clone()
    }

    pub fn get_structure(&self) -> bool {
        self.structure.clone()
    }

    pub fn get_imports(&self) -> bool {
        self.imports.clone()
    }

    pub fn get_exports(&self) -> bool {
        self.exports.clone()
    }

    pub fn get_comments(&self) -> bool {
        self.comments.clone()
    }

    pub fn get_docstrings(&self) -> bool {
        self.docstrings.clone()
    }

    pub fn get_symbols(&self) -> bool {
        self.symbols.clone()
    }

    pub fn get_diagnostics(&self) -> bool {
        self.diagnostics.clone()
    }

    pub fn get_chunk_max_size(&self) -> Option<i64> {
        self.chunk_max_size.clone()
    }

    pub fn with_chunking(&self, maxSize: i64) -> ProcessConfig {
        let core_self = tree_sitter_language_pack::ProcessConfig {
            language: Default::default(),
            structure: self.structure,
            imports: self.imports,
            exports: self.exports,
            comments: self.comments,
            docstrings: self.docstrings,
            symbols: self.symbols,
            diagnostics: self.diagnostics,
            chunk_max_size: self.chunk_max_size.map(|v| v as usize),
        };
        core_self.with_chunking(maxSize as usize).into()
    }

    pub fn all(&self) -> ProcessConfig {
        let core_self = tree_sitter_language_pack::ProcessConfig {
            language: Default::default(),
            structure: self.structure,
            imports: self.imports,
            exports: self.exports,
            comments: self.comments,
            docstrings: self.docstrings,
            symbols: self.symbols,
            diagnostics: self.diagnostics,
            chunk_max_size: self.chunk_max_size.map(|v| v as usize),
        };
        core_self.all().into()
    }

    pub fn minimal(&self) -> ProcessConfig {
        let core_self = tree_sitter_language_pack::ProcessConfig {
            language: Default::default(),
            structure: self.structure,
            imports: self.imports,
            exports: self.exports,
            comments: self.comments,
            docstrings: self.docstrings,
            symbols: self.symbols,
            diagnostics: self.diagnostics,
            chunk_max_size: self.chunk_max_size.map(|v| v as usize),
        };
        core_self.minimal().into()
    }

    #[allow(clippy::should_implement_trait)]
    pub fn default() -> ProcessConfig {
        tree_sitter_language_pack::ProcessConfig::default().into()
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\LanguageRegistry")]
pub struct LanguageRegistry {
    inner: Arc<tree_sitter_language_pack::LanguageRegistry>,
}

#[php_impl]
impl LanguageRegistry {
    /**
     * Get a tree-sitter `Language` by name.
     *
     * Resolves aliases (e.g., `"shell"` -> `"bash"`, `"makefile"` -> `"make"`),
     * then looks up the language in the static table. When the `dynamic-loading`
     * feature is enabled, falls back to loading a shared library on demand.
     * @throws TreeSitterLanguagePackException Returns `Error.LanguageNotFound` if the name (after alias resolution)
     * does not match any known grammar.
     */
    pub fn get_language(&self, name: String) -> PhpResult<Language> {
        let result = self
            .inner
            .get_language(&name)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(Language {
            inner: Arc::new(result),
        })
    }

    /**
     * List all available language names, sorted and deduplicated.
     *
     * Includes statically compiled languages, dynamically loadable languages
     * (if the `dynamic-loading` feature is enabled), and all configured aliases.
     */
    pub fn available_languages(&self) -> Vec<String> {
        self.inner.available_languages()
    }

    /**
     * Check whether a language is available by name or alias.
     *
     * Returns `true` if the language can be loaded, either from the static
     * table or from a dynamic library on disk.
     */
    pub fn has_language(&self, name: String) -> bool {
        self.inner.has_language(&name)
    }

    /**
     * Return the total number of available languages (including aliases).
     */
    pub fn language_count(&self) -> i64 {
        self.inner.language_count() as i64
    }

    /**
     * Parse source code and extract file intelligence based on config in a single pass.
     */
    pub fn process(&self, source: String, config: &ProcessConfig) -> PhpResult<ProcessResult> {
        let config_core: tree_sitter_language_pack::ProcessConfig = config.clone().into();
        let result = self
            .inner
            .process(&source, &config_core)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result.into())
    }

    #[allow(clippy::should_implement_trait)]
    pub fn default() -> LanguageRegistry {
        Self {
            inner: Arc::new(tree_sitter_language_pack::LanguageRegistry::default()),
        }
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\DownloadManager")]
pub struct DownloadManager {
    inner: Arc<tree_sitter_language_pack::DownloadManager>,
}

#[php_impl]
impl DownloadManager {
    /**
     * List languages that are already downloaded and cached.
     */
    pub fn installed_languages(&self) -> Vec<String> {
        self.inner.installed_languages()
    }

    /**
     * Download the platform bundle and extract every library file it contains.
     *
     * Unlike `ensure_languages`, this does not check the manifest language list
     * against archive contents — it simply extracts all `.so`/`.dylib`/`.dll` files
     * from the bundle. Languages in the manifest that are missing from the archive
     * are silently ignored rather than returning an error.
     *
     * Returns the number of library files extracted (including those already cached).
     */
    pub fn download_all_best_effort(&self) -> PhpResult<i64> {
        let result = self
            .inner
            .download_all_best_effort()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result as i64)
    }

    /**
     * Remove all cached parser libraries.
     */
    pub fn clean_cache(&self) -> PhpResult<()> {
        self.inner
            .clean_cache()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(())
    }

    /**
     * Create a new download manager for the given version.
     */
    pub fn new(version: String) -> PhpResult<DownloadManager> {
        tree_sitter_language_pack::DownloadManager::new(&version)
            .map(|val| Self { inner: Arc::new(val) })
            .map_err(|e| PhpException::default(e.to_string()))
    }

    /**
     * Create a download manager with a custom cache directory.
     */
    pub fn with_cache_dir(version: String, cacheDir: String) -> DownloadManager {
        Self {
            inner: Arc::new(tree_sitter_language_pack::DownloadManager::with_cache_dir(
                &version,
                std::path::PathBuf::from(cacheDir),
            )),
        }
    }
}

#[derive(Clone)]
#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\Language")]
pub struct Language {
    inner: Arc<tree_sitter_language_pack::Language>,
}

#[php_impl]
impl Language {}

// StructureKind enum values
pub const STRUCTUREKIND_FUNCTION: &str = "Function";
pub const STRUCTUREKIND_METHOD: &str = "Method";
pub const STRUCTUREKIND_CLASS: &str = "Class";
pub const STRUCTUREKIND_STRUCT: &str = "Struct";
pub const STRUCTUREKIND_INTERFACE: &str = "Interface";
pub const STRUCTUREKIND_ENUM: &str = "Enum";
pub const STRUCTUREKIND_MODULE: &str = "Module";
pub const STRUCTUREKIND_TRAIT: &str = "Trait";
pub const STRUCTUREKIND_IMPL: &str = "Impl";
pub const STRUCTUREKIND_NAMESPACE: &str = "Namespace";
pub const STRUCTUREKIND_OTHER: &str = "Other";

// CommentKind enum values
pub const COMMENTKIND_LINE: &str = "Line";
pub const COMMENTKIND_BLOCK: &str = "Block";
pub const COMMENTKIND_DOC: &str = "Doc";

// DocstringFormat enum values
pub const DOCSTRINGFORMAT_PYTHONTRIPLEQUOTE: &str = "PythonTripleQuote";
pub const DOCSTRINGFORMAT_JSDOC: &str = "JSDoc";
pub const DOCSTRINGFORMAT_RUSTDOC: &str = "Rustdoc";
pub const DOCSTRINGFORMAT_GODOC: &str = "GoDoc";
pub const DOCSTRINGFORMAT_JAVADOC: &str = "JavaDoc";
pub const DOCSTRINGFORMAT_OTHER: &str = "Other";

// ExportKind enum values
pub const EXPORTKIND_NAMED: &str = "Named";
pub const EXPORTKIND_DEFAULT: &str = "Default";
pub const EXPORTKIND_REEXPORT: &str = "ReExport";

// SymbolKind enum values
pub const SYMBOLKIND_VARIABLE: &str = "Variable";
pub const SYMBOLKIND_CONSTANT: &str = "Constant";
pub const SYMBOLKIND_FUNCTION: &str = "Function";
pub const SYMBOLKIND_CLASS: &str = "Class";
pub const SYMBOLKIND_TYPE: &str = "Type";
pub const SYMBOLKIND_INTERFACE: &str = "Interface";
pub const SYMBOLKIND_ENUM: &str = "Enum";
pub const SYMBOLKIND_MODULE: &str = "Module";
pub const SYMBOLKIND_OTHER: &str = "Other";

// DiagnosticSeverity enum values
pub const DIAGNOSTICSEVERITY_ERROR: &str = "Error";
pub const DIAGNOSTICSEVERITY_WARNING: &str = "Warning";
pub const DIAGNOSTICSEVERITY_INFO: &str = "Info";

#[php_class]
#[php(name = "Tree\\Sitter\\Language\\Pack\\TreeSitterLanguagePackApi")]
pub struct TreeSitterLanguagePackApi;

#[php_impl]
impl TreeSitterLanguagePackApi {
    /**
     * Detect language name from a file extension (without leading dot).
     *
     * Returns `None` for unrecognized extensions. The match is case-insensitive.
     */
    pub fn detect_language_from_extension(ext: String) -> Option<String> {
        tree_sitter_language_pack::detect_language_from_extension(&ext).map(Into::into)
    }

    /**
     * Detect language name from a file path.
     *
     * Extracts the file extension and looks it up. Returns `None` if the
     * path has no extension or the extension is not recognized.
     */
    pub fn detect_language_from_path(path: String) -> Option<String> {
        tree_sitter_language_pack::detect_language_from_path(&path).map(Into::into)
    }

    /**
     * Detect language name from file content using the shebang line (`#!`).
     *
     * Inspects only the first line of `content`. If it begins with `#!`, the
     * interpreter name is extracted and mapped to a language name.
     *
     * Handles common patterns:
     * - `#!/usr/bin/env python3` → `"python"`
     * - `#!/bin/bash` → `"bash"`
     * - `#!/usr/bin/env node` → `"javascript"`
     *
     * The `-S` flag accepted by some `env` implementations is skipped automatically.
     * Version suffixes (e.g. `python3.11`, `ruby3.2`) are stripped before matching.
     *
     * Returns `None` when content does not start with `#!`, the shebang is
     * malformed, or the interpreter is not recognised.
     */
    pub fn detect_language_from_content(content: String) -> Option<String> {
        tree_sitter_language_pack::detect_language_from_content(&content).map(Into::into)
    }

    /**
     * Get the highlights query for a language, if bundled.
     *
     * Returns the contents of `highlights.scm` as a static string, or `None`
     * if no highlights query is bundled for this language.
     *
     * # Example
     */
    pub fn get_highlights_query(language: String) -> Option<String> {
        tree_sitter_language_pack::get_highlights_query(&language).map(Into::into)
    }

    /**
     * Get the injections query for a language, if bundled.
     *
     * Returns the contents of `injections.scm` as a static string, or `None`
     * if no injections query is bundled for this language.
     *
     * # Example
     */
    pub fn get_injections_query(language: String) -> Option<String> {
        tree_sitter_language_pack::get_injections_query(&language).map(Into::into)
    }

    /**
     * Get the locals query for a language, if bundled.
     *
     * Returns the contents of `locals.scm` as a static string, or `None`
     * if no locals query is bundled for this language.
     *
     * # Example
     */
    pub fn get_locals_query(language: String) -> Option<String> {
        tree_sitter_language_pack::get_locals_query(&language).map(Into::into)
    }

    /**
     * Get a tree-sitter `Language` by name using the global registry.
     *
     * Resolves language aliases (e.g., `"shell"` maps to `"bash"`).
     * When the `download` feature is enabled (default), automatically downloads
     * the parser from GitHub releases if not found locally.
     * @throws TreeSitterLanguagePackException Returns `Error.LanguageNotFound` if the language is not recognized,
     * or `Error.Download` if auto-download fails.
     */
    pub fn get_language(name: String) -> PhpResult<Language> {
        let result = tree_sitter_language_pack::get_language(&name)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(Language {
            inner: Arc::new(result),
        })
    }

    /**
     * Get a `Parser` pre-configured for the given language.
     *
     * This is a convenience function that calls `get_language` and configures
     * a new parser in one step.
     * @throws TreeSitterLanguagePackException Returns `Error.LanguageNotFound` if the language is not recognized, or
     * `Error.ParserSetup` if the language cannot be applied to the parser.
     */
    pub fn get_parser(name: String) -> PhpResult<Parser> {
        let result = tree_sitter_language_pack::get_parser(&name)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(Parser {
            inner: Arc::new(std::sync::Mutex::new(result)),
        })
    }

    /**
     * Detect language name from a file path or extension.
     *
     * This compatibility alias matches the pre-Alef Python binding API.
     */
    pub fn detect_language(path: String) -> Option<String> {
        tree_sitter_language_pack::detect_language(&path).map(Into::into)
    }

    /**
     * List all available language names (sorted, deduplicated, includes aliases).
     *
     * Returns names of both statically compiled and dynamically loadable languages,
     * plus any configured aliases.
     *
     * # Example
     */
    pub fn available_languages() -> Vec<String> {
        tree_sitter_language_pack::available_languages()
    }

    /**
     * Check if a language is available by name or alias.
     *
     * Returns `true` if the language can be loaded (statically compiled,
     * dynamically available, or a known alias for one of these).
     *
     * # Example
     */
    pub fn has_language(name: String) -> bool {
        tree_sitter_language_pack::has_language(&name)
    }

    /**
     * Return the number of available languages.
     *
     * Includes statically compiled languages, dynamically loadable languages,
     * and aliases.
     *
     * # Example
     */
    pub fn language_count() -> i64 {
        tree_sitter_language_pack::language_count() as i64
    }

    /**
     * Process source code and extract file intelligence using the global registry.
     *
     * Parses the source with tree-sitter and extracts metrics, structure, imports,
     * exports, comments, docstrings, symbols, diagnostics, and/or chunks based on
     * the flags set in `ProcessConfig`.
     * @throws TreeSitterLanguagePackException Returns an error if the language is not found or parsing fails.
     */
    pub fn process(source: String, config: &ProcessConfig) -> PhpResult<ProcessResult> {
        let config_core: tree_sitter_language_pack::ProcessConfig = config.clone().into();
        let result = tree_sitter_language_pack::process(&source, &config_core)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result.into())
    }

    /**
     * Initialize the language pack with the given configuration.
     *
     * Applies any custom cache directory, then downloads all languages and groups
     * specified in the config. This is the recommended entry point when you want
     * to pre-warm the cache before use.
     * @throws TreeSitterLanguagePackException Returns an error if configuration cannot be applied or if downloads fail.
     */
    pub fn init(config: &PackConfig) -> PhpResult<()> {
        let config_core: tree_sitter_language_pack::PackConfig = config.clone().into();
        let result = tree_sitter_language_pack::init(&config_core)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result)
    }

    /**
     * Apply download configuration without downloading anything.
     *
     * Use this to set a custom cache directory before the first call to
     * `get_language` or any download function. Changing the cache dir
     * after languages have been registered has no effect on already-loaded
     * languages.
     * @throws TreeSitterLanguagePackException Returns an error if the lock cannot be acquired.
     */
    pub fn configure(config: &PackConfig) -> PhpResult<()> {
        let config_core: tree_sitter_language_pack::PackConfig = config.clone().into();
        let result = tree_sitter_language_pack::configure(&config_core)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result)
    }

    /**
     * Download specific languages to the local cache.
     *
     * Returns the number of requested languages available after the call. Already
     * compiled or cached languages are included in the count.
     * @throws TreeSitterLanguagePackException Returns an error if any language is not available in the manifest or if
     * the download fails.
     */
    pub fn download(names: Vec<String>) -> PhpResult<i64> {
        let names_refs: Vec<&str> = names.iter().map(|s| s.as_str()).collect();
        let result = tree_sitter_language_pack::download(&names_refs)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result as i64)
    }

    /**
     * Download all available languages from the remote manifest.
     *
     * Downloads the platform bundle and extracts every library it contains.
     * Languages that appear in the manifest but are absent from the bundle
     * (e.g. grammars that failed to compile at release time) are silently
     * skipped — they are not treated as an error.
     *
     * Returns the total number of languages now available (statically compiled
     * plus downloaded and cached).
     * @throws TreeSitterLanguagePackException Returns an error if the manifest cannot be fetched or the bundle download fails.
     */
    pub fn download_all() -> PhpResult<i64> {
        let result = tree_sitter_language_pack::download_all()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result as i64)
    }

    /**
     * Download every language in a named group (e.g. `"web"`, `"data"`).
     *
     * Groups are defined in the remote manifest and let you ensure a curated
     * set of related grammars in one call instead of listing each name to
     * `download`. Already-cached languages are skipped.
     *
     * Returns the total number of languages now available (statically compiled
     * plus downloaded and cached).
     * @throws TreeSitterLanguagePackException Returns an error if the manifest cannot be fetched, the group is unknown,
     * or any constituent language fails to download.
     */
    pub fn download_group(name: String) -> PhpResult<i64> {
        let result = tree_sitter_language_pack::download_group(&name)
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result as i64)
    }

    /**
     * Return all language names available in the remote manifest (305).
     *
     * Fetches (and caches) the remote manifest to discover the full list of
     * downloadable languages. Use `downloaded_languages` to list what is
     * already cached locally.
     * @throws TreeSitterLanguagePackException Returns an error if the manifest cannot be fetched.
     */
    pub fn manifest_languages() -> PhpResult<Vec<String>> {
        let result = tree_sitter_language_pack::manifest_languages()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result)
    }

    /**
     * Return languages that are already downloaded and cached locally.
     *
     * Does not perform any network requests. Returns an empty list if the
     * cache directory does not exist or cannot be read.
     *
     * # Example
     */
    pub fn downloaded_languages() -> Vec<String> {
        tree_sitter_language_pack::downloaded_languages()
    }

    /**
     * Delete all cached parser shared libraries.
     *
     * Resets the cache registration so the next call to `get_language` or
     * a download function will re-register the (now empty) cache directory.
     * @throws TreeSitterLanguagePackException Returns an error if the cache directory cannot be removed.
     */
    pub fn clean_cache() -> PhpResult<()> {
        let result = tree_sitter_language_pack::clean_cache()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result)
    }

    /**
     * Return the effective cache directory path.
     *
     * This is either the custom path set via `configure` / `init` or the
     * default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`.
     * @throws TreeSitterLanguagePackException Returns an error if the system cache directory cannot be determined.
     */
    pub fn cache_dir() -> PhpResult<String> {
        let result = tree_sitter_language_pack::cache_dir()
            .map_err(|e| ext_php_rs::exception::PhpException::default(e.to_string()))?;
        Ok(result)
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<Span> for tree_sitter_language_pack::Span {
    fn from(val: Span) -> Self {
        Self {
            start_byte: val.start_byte as usize,
            end_byte: val.end_byte as usize,
            start_line: val.start_line as usize,
            start_column: val.start_column as usize,
            end_line: val.end_line as usize,
            end_column: val.end_column as usize,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::Span> for Span {
    fn from(val: tree_sitter_language_pack::Span) -> Self {
        Self {
            start_byte: val.start_byte as i64,
            end_byte: val.end_byte as i64,
            start_line: val.start_line as i64,
            start_column: val.start_column as i64,
            end_line: val.end_line as i64,
            end_column: val.end_column as i64,
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<ProcessResult> for tree_sitter_language_pack::ProcessResult {
    fn from(val: ProcessResult) -> Self {
        Self {
            language: val.language,
            metrics: val.metrics.into(),
            structure: val.structure.into_iter().map(Into::into).collect(),
            imports: val.imports.into_iter().map(Into::into).collect(),
            exports: val.exports.into_iter().map(Into::into).collect(),
            comments: val.comments.into_iter().map(Into::into).collect(),
            docstrings: val.docstrings.into_iter().map(Into::into).collect(),
            symbols: val.symbols.into_iter().map(Into::into).collect(),
            diagnostics: val.diagnostics.into_iter().map(Into::into).collect(),
            chunks: val.chunks.into_iter().map(Into::into).collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ProcessResult> for ProcessResult {
    fn from(val: tree_sitter_language_pack::ProcessResult) -> Self {
        Self {
            language: val.language,
            metrics: val.metrics.into(),
            structure: val.structure.into_iter().map(Into::into).collect(),
            imports: val.imports.into_iter().map(Into::into).collect(),
            exports: val.exports.into_iter().map(Into::into).collect(),
            comments: val.comments.into_iter().map(Into::into).collect(),
            docstrings: val.docstrings.into_iter().map(Into::into).collect(),
            symbols: val.symbols.into_iter().map(Into::into).collect(),
            diagnostics: val.diagnostics.into_iter().map(Into::into).collect(),
            chunks: val.chunks.into_iter().map(Into::into).collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<FileMetrics> for tree_sitter_language_pack::FileMetrics {
    fn from(val: FileMetrics) -> Self {
        Self {
            total_lines: val.total_lines as usize,
            code_lines: val.code_lines as usize,
            comment_lines: val.comment_lines as usize,
            blank_lines: val.blank_lines as usize,
            total_bytes: val.total_bytes as usize,
            node_count: val.node_count as usize,
            error_count: val.error_count as usize,
            max_depth: val.max_depth as usize,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::FileMetrics> for FileMetrics {
    fn from(val: tree_sitter_language_pack::FileMetrics) -> Self {
        Self {
            total_lines: val.total_lines as i64,
            code_lines: val.code_lines as i64,
            comment_lines: val.comment_lines as i64,
            blank_lines: val.blank_lines as i64,
            total_bytes: val.total_bytes as i64,
            node_count: val.node_count as i64,
            error_count: val.error_count as i64,
            max_depth: val.max_depth as i64,
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<StructureItem> for tree_sitter_language_pack::StructureItem {
    fn from(val: StructureItem) -> Self {
        Self {
            kind: match val.kind.as_str() {
                "Function" => tree_sitter_language_pack::StructureKind::Function,
                "Method" => tree_sitter_language_pack::StructureKind::Method,
                "Class" => tree_sitter_language_pack::StructureKind::Class,
                "Struct" => tree_sitter_language_pack::StructureKind::Struct,
                "Interface" => tree_sitter_language_pack::StructureKind::Interface,
                "Enum" => tree_sitter_language_pack::StructureKind::Enum,
                "Module" => tree_sitter_language_pack::StructureKind::Module,
                "Trait" => tree_sitter_language_pack::StructureKind::Trait,
                "Impl" => tree_sitter_language_pack::StructureKind::Impl,
                "Namespace" => tree_sitter_language_pack::StructureKind::Namespace,
                "Other" => tree_sitter_language_pack::StructureKind::Other(Default::default()),
                _ => Default::default(),
            },
            name: val.name,
            visibility: val.visibility,
            span: val.span.into(),
            children: val.children.into_iter().map(Into::into).collect(),
            decorators: val.decorators.into_iter().collect(),
            doc_comment: val.doc_comment,
            signature: val.signature,
            body_span: val.body_span.map(Into::into),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::StructureItem> for StructureItem {
    fn from(val: tree_sitter_language_pack::StructureItem) -> Self {
        Self {
            kind: serde_json::to_value(val.kind)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            name: val.name,
            visibility: val.visibility,
            span: val.span.into(),
            children: val.children.into_iter().map(Into::into).collect(),
            decorators: val.decorators.into_iter().collect(),
            doc_comment: val.doc_comment,
            signature: val.signature,
            body_span: val.body_span.map(Into::into),
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<CommentInfo> for tree_sitter_language_pack::CommentInfo {
    fn from(val: CommentInfo) -> Self {
        Self {
            text: val.text,
            kind: match val.kind.as_str() {
                "Line" => tree_sitter_language_pack::CommentKind::Line,
                "Block" => tree_sitter_language_pack::CommentKind::Block,
                "Doc" => tree_sitter_language_pack::CommentKind::Doc,
                _ => Default::default(),
            },
            span: val.span.into(),
            associated_node: val.associated_node,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::CommentInfo> for CommentInfo {
    fn from(val: tree_sitter_language_pack::CommentInfo) -> Self {
        Self {
            text: val.text,
            kind: serde_json::to_value(val.kind)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            span: val.span.into(),
            associated_node: val.associated_node,
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<DocstringInfo> for tree_sitter_language_pack::DocstringInfo {
    fn from(val: DocstringInfo) -> Self {
        Self {
            text: val.text,
            format: match val.format.as_str() {
                "PythonTripleQuote" => tree_sitter_language_pack::DocstringFormat::PythonTripleQuote,
                "JSDoc" => tree_sitter_language_pack::DocstringFormat::JSDoc,
                "Rustdoc" => tree_sitter_language_pack::DocstringFormat::Rustdoc,
                "GoDoc" => tree_sitter_language_pack::DocstringFormat::GoDoc,
                "JavaDoc" => tree_sitter_language_pack::DocstringFormat::JavaDoc,
                "Other" => tree_sitter_language_pack::DocstringFormat::Other(Default::default()),
                _ => Default::default(),
            },
            span: val.span.into(),
            associated_item: val.associated_item,
            parsed_sections: val.parsed_sections.into_iter().map(Into::into).collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::DocstringInfo> for DocstringInfo {
    fn from(val: tree_sitter_language_pack::DocstringInfo) -> Self {
        Self {
            text: val.text,
            format: serde_json::to_value(val.format)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            span: val.span.into(),
            associated_item: val.associated_item,
            parsed_sections: val.parsed_sections.into_iter().map(Into::into).collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<DocSection> for tree_sitter_language_pack::DocSection {
    fn from(val: DocSection) -> Self {
        Self {
            kind: val.kind,
            name: val.name,
            description: val.description,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::DocSection> for DocSection {
    fn from(val: tree_sitter_language_pack::DocSection) -> Self {
        Self {
            kind: val.kind,
            name: val.name,
            description: val.description,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<ImportInfo> for tree_sitter_language_pack::ImportInfo {
    fn from(val: ImportInfo) -> Self {
        Self {
            source: val.source,
            items: val.items.into_iter().collect(),
            alias: val.alias,
            is_wildcard: val.is_wildcard,
            span: val.span.into(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ImportInfo> for ImportInfo {
    fn from(val: tree_sitter_language_pack::ImportInfo) -> Self {
        Self {
            source: val.source,
            items: val.items.into_iter().collect(),
            alias: val.alias,
            is_wildcard: val.is_wildcard,
            span: val.span.into(),
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<ExportInfo> for tree_sitter_language_pack::ExportInfo {
    fn from(val: ExportInfo) -> Self {
        Self {
            name: val.name,
            kind: match val.kind.as_str() {
                "Named" => tree_sitter_language_pack::ExportKind::Named,
                "Default" => tree_sitter_language_pack::ExportKind::Default,
                "ReExport" => tree_sitter_language_pack::ExportKind::ReExport,
                _ => Default::default(),
            },
            span: val.span.into(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ExportInfo> for ExportInfo {
    fn from(val: tree_sitter_language_pack::ExportInfo) -> Self {
        Self {
            name: val.name,
            kind: serde_json::to_value(val.kind)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            span: val.span.into(),
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<SymbolInfo> for tree_sitter_language_pack::SymbolInfo {
    fn from(val: SymbolInfo) -> Self {
        Self {
            name: val.name,
            kind: match val.kind.as_str() {
                "Variable" => tree_sitter_language_pack::SymbolKind::Variable,
                "Constant" => tree_sitter_language_pack::SymbolKind::Constant,
                "Function" => tree_sitter_language_pack::SymbolKind::Function,
                "Class" => tree_sitter_language_pack::SymbolKind::Class,
                "Type" => tree_sitter_language_pack::SymbolKind::Type,
                "Interface" => tree_sitter_language_pack::SymbolKind::Interface,
                "Enum" => tree_sitter_language_pack::SymbolKind::Enum,
                "Module" => tree_sitter_language_pack::SymbolKind::Module,
                "Other" => tree_sitter_language_pack::SymbolKind::Other(Default::default()),
                _ => Default::default(),
            },
            span: val.span.into(),
            type_annotation: val.type_annotation,
            doc: val.doc,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::SymbolInfo> for SymbolInfo {
    fn from(val: tree_sitter_language_pack::SymbolInfo) -> Self {
        Self {
            name: val.name,
            kind: serde_json::to_value(val.kind)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            span: val.span.into(),
            type_annotation: val.type_annotation,
            doc: val.doc,
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<Diagnostic> for tree_sitter_language_pack::Diagnostic {
    fn from(val: Diagnostic) -> Self {
        Self {
            message: val.message,
            severity: match val.severity.as_str() {
                "Error" => tree_sitter_language_pack::DiagnosticSeverity::Error,
                "Warning" => tree_sitter_language_pack::DiagnosticSeverity::Warning,
                "Info" => tree_sitter_language_pack::DiagnosticSeverity::Info,
                _ => Default::default(),
            },
            span: val.span.into(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::Diagnostic> for Diagnostic {
    fn from(val: tree_sitter_language_pack::Diagnostic) -> Self {
        Self {
            message: val.message,
            severity: serde_json::to_value(val.severity)
                .ok()
                .and_then(|s| s.as_str().map(String::from))
                .unwrap_or_default(),
            span: val.span.into(),
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<CodeChunk> for tree_sitter_language_pack::CodeChunk {
    fn from(val: CodeChunk) -> Self {
        Self {
            content: val.content,
            start_byte: val.start_byte as usize,
            end_byte: val.end_byte as usize,
            start_line: val.start_line as usize,
            end_line: val.end_line as usize,
            metadata: val.metadata.into(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::CodeChunk> for CodeChunk {
    fn from(val: tree_sitter_language_pack::CodeChunk) -> Self {
        Self {
            content: val.content,
            start_byte: val.start_byte as i64,
            end_byte: val.end_byte as i64,
            start_line: val.start_line as i64,
            end_line: val.end_line as i64,
            metadata: val.metadata.into(),
        }
    }
}

#[allow(clippy::useless_conversion)]
impl From<ChunkContext> for tree_sitter_language_pack::ChunkContext {
    fn from(val: ChunkContext) -> Self {
        Self {
            language: val.language,
            chunk_index: val.chunk_index as usize,
            total_chunks: val.total_chunks as usize,
            node_types: val.node_types.into_iter().collect(),
            context_path: val.context_path.into_iter().collect(),
            symbols_defined: val.symbols_defined.into_iter().collect(),
            comments: val.comments.into_iter().map(Into::into).collect(),
            docstrings: val.docstrings.into_iter().map(Into::into).collect(),
            has_error_nodes: val.has_error_nodes,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ChunkContext> for ChunkContext {
    fn from(val: tree_sitter_language_pack::ChunkContext) -> Self {
        Self {
            language: val.language,
            chunk_index: val.chunk_index as i64,
            total_chunks: val.total_chunks as i64,
            node_types: val.node_types.into_iter().collect(),
            context_path: val.context_path.into_iter().collect(),
            symbols_defined: val.symbols_defined.into_iter().collect(),
            comments: val.comments.into_iter().map(Into::into).collect(),
            docstrings: val.docstrings.into_iter().map(Into::into).collect(),
            has_error_nodes: val.has_error_nodes,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<PackConfig> for tree_sitter_language_pack::PackConfig {
    fn from(val: PackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir.map(Into::into),
            languages: val.languages.map(|v| v.into_iter().collect()),
            groups: val.groups.map(|v| v.into_iter().collect()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::PackConfig> for PackConfig {
    fn from(val: tree_sitter_language_pack::PackConfig) -> Self {
        Self {
            cache_dir: val.cache_dir.map(|p| p.to_string_lossy().to_string()),
            languages: val.languages.map(|v| v.into_iter().collect()),
            groups: val.groups.map(|v| v.into_iter().collect()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<Point> for tree_sitter_language_pack::Point {
    fn from(val: Point) -> Self {
        Self {
            row: val.row as usize,
            column: val.column as usize,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::Point> for Point {
    fn from(val: tree_sitter_language_pack::Point) -> Self {
        Self {
            row: val.row as i64,
            column: val.column as i64,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<ByteRange> for tree_sitter_language_pack::ByteRange {
    fn from(val: ByteRange) -> Self {
        Self {
            start: val.start as usize,
            end: val.end as usize,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ByteRange> for ByteRange {
    fn from(val: tree_sitter_language_pack::ByteRange) -> Self {
        Self {
            start: val.start as i64,
            end: val.end as i64,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<ProcessConfig> for tree_sitter_language_pack::ProcessConfig {
    fn from(val: ProcessConfig) -> Self {
        Self {
            language: val.language.into(),
            structure: val.structure,
            imports: val.imports,
            exports: val.exports,
            comments: val.comments,
            docstrings: val.docstrings,
            symbols: val.symbols,
            diagnostics: val.diagnostics,
            chunk_max_size: val.chunk_max_size.map(|v| v as usize),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<tree_sitter_language_pack::ProcessConfig> for ProcessConfig {
    fn from(val: tree_sitter_language_pack::ProcessConfig) -> Self {
        Self {
            language: val.language.to_string(),
            structure: val.structure,
            imports: val.imports,
            exports: val.exports,
            comments: val.comments,
            docstrings: val.docstrings,
            symbols: val.symbols,
            diagnostics: val.diagnostics,
            chunk_max_size: val.chunk_max_size.map(|v| v as i64),
        }
    }
}

/// Convert a `tree_sitter_language_pack::error::Error` error to a PHP exception.
#[allow(dead_code)]
fn error_to_php_err(e: tree_sitter_language_pack::error::Error) -> ext_php_rs::exception::PhpException {
    let msg = e.to_string();
    #[allow(unreachable_patterns)]
    match &e {
        tree_sitter_language_pack::error::Error::LanguageNotFound(..) => {
            ext_php_rs::exception::PhpException::default(format!("[LanguageNotFound] {}", msg))
        }
        tree_sitter_language_pack::error::Error::DynamicLoad(..) => {
            ext_php_rs::exception::PhpException::default(format!("[DynamicLoad] {}", msg))
        }
        tree_sitter_language_pack::error::Error::NullLanguagePointer(..) => {
            ext_php_rs::exception::PhpException::default(format!("[NullLanguagePointer] {}", msg))
        }
        tree_sitter_language_pack::error::Error::ParserSetup(..) => {
            ext_php_rs::exception::PhpException::default(format!("[ParserSetup] {}", msg))
        }
        tree_sitter_language_pack::error::Error::LockPoisoned(..) => {
            ext_php_rs::exception::PhpException::default(format!("[LockPoisoned] {}", msg))
        }
        tree_sitter_language_pack::error::Error::Config(..) => {
            ext_php_rs::exception::PhpException::default(format!("[Config] {}", msg))
        }
        tree_sitter_language_pack::error::Error::ParseFailed => {
            ext_php_rs::exception::PhpException::default(format!("[ParseFailed] {}", msg))
        }
        tree_sitter_language_pack::error::Error::QueryError(..) => {
            ext_php_rs::exception::PhpException::default(format!("[QueryError] {}", msg))
        }
        tree_sitter_language_pack::error::Error::InvalidRange(..) => {
            ext_php_rs::exception::PhpException::default(format!("[InvalidRange] {}", msg))
        }
        tree_sitter_language_pack::error::Error::Io(..) => {
            ext_php_rs::exception::PhpException::default(format!("[Io] {}", msg))
        }
        _ => ext_php_rs::exception::PhpException::default(msg),
    }
}

mod serde_defaults {
    pub fn bool_true() -> bool {
        true
    }
    pub fn max_archive_size() -> i64 {
        500 * 1024 * 1024
    }
    pub fn max_compression_ratio() -> i64 {
        100
    }
    pub fn max_files_in_archive() -> i64 {
        10_000
    }
    pub fn max_nesting_depth() -> i64 {
        1024
    }
    pub fn max_entity_length() -> i64 {
        1024 * 1024
    }
    pub fn max_content_size() -> i64 {
        100 * 1024 * 1024
    }
    pub fn max_iterations() -> i64 {
        10_000_000
    }
    pub fn max_xml_depth() -> i64 {
        1024
    }
    pub fn max_table_cells() -> i64 {
        100_000
    }
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module
        .class::<Span>()
        .class::<ProcessResult>()
        .class::<FileMetrics>()
        .class::<StructureItem>()
        .class::<CommentInfo>()
        .class::<DocstringInfo>()
        .class::<DocSection>()
        .class::<ImportInfo>()
        .class::<ExportInfo>()
        .class::<SymbolInfo>()
        .class::<Diagnostic>()
        .class::<CodeChunk>()
        .class::<ChunkContext>()
        .class::<PackConfig>()
        .class::<Point>()
        .class::<ByteRange>()
        .class::<Parser>()
        .class::<Tree>()
        .class::<Node>()
        .class::<TreeCursor>()
        .class::<ProcessConfig>()
        .class::<LanguageRegistry>()
        .class::<DownloadManager>()
        .class::<Language>()
        .class::<TreeSitterLanguagePackApi>()
}
