# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3ad7bc0ec3adca36ba1a91ce8688d8ae4a66ffe52844666e4b2fb36959f4c8b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: parsing
defmodule E2e.ParsingTest do
  use ExUnit.Case, async: false

  describe "parsing_go_function" do
    @tag :skip
    test "Parse a Go function declaration and assert node type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_html_element" do
    @tag :skip
    test "Parse an HTML element and assert node type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_javascript_class" do
    @tag :skip
    test "Parse a JavaScript class declaration." do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_javascript_variable" do
    @tag :skip
    test "Parse a JavaScript variable declaration and assert node type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_python_function" do
    @tag :skip
    test "Parse a Python function definition and assert node type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_rust_function" do
    @tag :skip
    test "Parse a Rust function definition and assert node type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "parsing_rust_struct" do
    @tag :skip
    test "Parse a Rust struct definition." do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
