# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:35ddf749dc6d971bb073e0817f87043ea8181bcb9c31a17bf4618a54eb80cca2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: truerequire 'tree_sitter_language_pack'require 'json'
RSpec.describe 'process' do
  def alef_e2e_item_texts(item)
    [:kind, :name, :signature, :path, :alias, :text, :source].filter_map do |attr|
      item.respond_to?(attr) ? item.send(attr).to_s : nil
    end
  end
  it 'c_function_process: Intel: C function with include' do    result = TreeSitterLanguagePack.process("\#include <stdio.h>\n\nint main() {\n    printf(\"hello\");\n    return 0;\n}\n", { 'language' => 'c' })
    expect(result.language).to eq('c')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'config_all_python: Intel: process with all features enabled' do    result = TreeSitterLanguagePack.process("\# A comment\ndef greet(name):\n    \"\"\"Say hello.\"\"\"\n    return f'Hi {name}'\n\nimport os\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'config_minimal_python: Intel: process with minimal config - only metrics' do    result = TreeSitterLanguagePack.process("def hello():\n    pass\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.metrics.total_lines).to be >= 2
  end

  it 'go_function_process: Intel: extract structure from Go function definition' do    result = TreeSitterLanguagePack.process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", { 'language' => 'go' })
    expect(result.language).to eq('go')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 7
    expect(result.metrics.error_count).to eq(0)
  end

  it 'go_function_process_detail: Intel: extract structure from Go function definition' do    result = TreeSitterLanguagePack.process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", { 'language' => 'go' })
    expect(result.language).to eq('go')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 7
    expect(result.metrics.error_count).to eq(0)
  end

  it 'java_class_process: Intel: Java class with methods and imports' do    result = TreeSitterLanguagePack.process("import java.util.List;\n\npublic class Greeter {\n    public String greet(String name) {\n        return \"Hello \" + name;\n    }\n}\n", { 'language' => 'java' })
    expect(result.language).to eq('java')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 7
    expect(result.metrics.error_count).to eq(0)
  end

  it 'java_package_declaration_process: Intel: Java package declaration emitted as Module so callers can build FQNs (#112)' do    result = TreeSitterLanguagePack.process("package com.example.widget;\n\npublic class Widget {\n    public String name() { return \"w\"; }\n}\n", { 'language' => 'java' })
    expect(result.language).to eq('java')
    expect(result.structure.length).to be >= 2
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Module') } }).to be(true)
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.metrics.error_count).to eq(0)
  end

  it 'javascript_multi_import_process: Intel: detect multiple imports and function in JavaScript' do    result = TreeSitterLanguagePack.process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", { 'language' => 'javascript' })
    expect(result.language).to eq('javascript')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 2
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'javascript_multi_import_process_detail: Intel: detect multiple imports and function in JavaScript' do    result = TreeSitterLanguagePack.process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", { 'language' => 'javascript' })
    expect(result.language).to eq('javascript')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 2
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'kotlin_package_class_process: Intel: Kotlin package header emitted as Module and class name resolved via type_identifier fallback (#111, #112)' do    result = TreeSitterLanguagePack.process("package foo.bar\n\nclass Widget {\n    fun greet(): String = \"hi\"\n}\n", { 'language' => 'kotlin' })
    expect(result.language).to eq('kotlin')
    expect(result.structure.length).to be >= 2
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Module') } }).to be(true)
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.metrics.error_count).to eq(0)
  end

  it 'process_javascript_exports_count: JavaScript with multiple exports, verify export count' do    result = TreeSitterLanguagePack.process("export function greet() { return 'hi'; }\nexport const VERSION = '1.0';\nexport default class App {}\n", { 'language' => 'javascript' })
    expect(result.language).to eq('javascript')
    expect(result.exports.length).to be >= 2
  end

  it 'process_javascript_exports_detail: JavaScript with exports, verify export count' do    result = TreeSitterLanguagePack.process("export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n", { 'language' => 'javascript' })
    expect(result.language).to eq('javascript')
    expect(result.exports.length).to be >= 1
  end

  it 'process_python_all_features: Python comprehensive source with all feature extraction enabled' do    result = TreeSitterLanguagePack.process("import os\nfrom pathlib import Path\n\n\# Configuration\nMY_CONST = 42\n\ndef process_file(path):\n    \"\"\"Process a file and return contents.\"\"\"\n    with open(path) as f:\n        return f.read()\n\nclass FileProcessor:\n    def __init__(self, base_dir):\n        self.base_dir = base_dir\n", { 'comments' => true, 'docstrings' => true, 'imports' => true, 'language' => 'python', 'structure' => true, 'symbols' => true })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 2
    expect(result.imports.length).to be >= 1
    expect(result.comments.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 10
  end

  it 'process_python_comments: Python with comments, verify comment count' do    result = TreeSitterLanguagePack.process("\# This is a comment\n\# Another comment\ndef hello():\n    \# inline comment\n    pass\n", { 'comments' => true, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.comments.length).to be >= 1
  end

  it 'process_python_docstrings: Python with function docstring, verify docstring count' do    result = TreeSitterLanguagePack.process("def greet(name):\n    \"\"\"Say hello to someone.\"\"\"\n    return f\"Hello {name}\"\n", { 'docstrings' => true, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.metrics.total_lines).to be >= 3
  end

  it 'process_python_imports_detail: Python with multiple imports, verify imports contain specific source' do    result = TreeSitterLanguagePack.process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.imports.length).to be >= 2
    expect(result.imports.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('os') } }).to be(true)
  end

  it 'process_python_metrics_detail: Python code with metrics assertions' do    result = TreeSitterLanguagePack.process("\# module docstring\nimport os\n\ndef hello():\n    \# greeting\n    print('hello')\n\ndef world():\n    print('world')\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.metrics.code_lines).to be >= 4
    expect(result.metrics.comment_lines).to be >= 1
    expect(result.metrics.max_depth).to be >= 1
  end

  it 'process_python_symbols: Python with class and functions, verify symbol count' do    result = TreeSitterLanguagePack.process("MY_CONST = 42\ndef helper(): pass\nclass Widget: pass\n", { 'language' => 'python', 'symbols' => true })
    expect(result.language).to eq('python')
    expect(result.symbols.length).to be >= 1
  end

  it 'process_rust_structure_name: Rust struct with name, verify structure name contains value' do    result = TreeSitterLanguagePack.process("pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n", { 'language' => 'rust' })
    expect(result.language).to eq('rust')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('MyConfig') } }).to be(true)
  end

  it 'python_chunking_medium: Intel: Python code with medium chunk size' do    result = TreeSitterLanguagePack.process("def first():\n    x = 1\n    return x\n\ndef second():\n    y = 2\n    return y\n\ndef third():\n    z = 3\n    return z\n", { 'chunk_max_size' => 50, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 3
    expect(result.metrics.error_count).to eq(0)
    expect(result.chunks.length).to be >= 2
  end

  it 'python_chunking_process_detail: Intel: chunk multi-function Python source into multiple pieces' do    result = TreeSitterLanguagePack.process("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", { 'chunk_max_size' => 30, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.metrics.total_lines).to be >= 8
    expect(result.chunks.length).to be >= 2
  end

  it 'python_class_with_methods_process: Intel: extract nested structure from Python class with methods' do    result = TreeSitterLanguagePack.process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'python_class_with_methods_process_detail: Intel: extract nested structure from Python class with methods' do    result = TreeSitterLanguagePack.process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 6
    expect(result.metrics.error_count).to eq(0)
  end

  it 'python_error_diagnostics: Intel: Python code with syntax errors should report diagnostics' do    result = TreeSitterLanguagePack.process("def broken(\n    pass\n", { 'diagnostics' => true, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.metrics.error_count).to eq(1)
    expect(result.diagnostics.to_s).not_to be_empty
  end

  it 'python_function_process: Intel: extract structure from Python function definition' do    result = TreeSitterLanguagePack.process("def greet(name):\n    return f'Hello, {name}!'\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 2
    expect(result.metrics.error_count).to eq(0)
  end

  it 'python_function_process_detail: Intel: extract structure from Python function definition' do    result = TreeSitterLanguagePack.process("def greet(name):\n    return f'Hello, {name}!'\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 2
    expect(result.metrics.error_count).to eq(0)
  end

  it 'python_malformed_code_process: Intel: detect diagnostics in malformed Python code' do    result = TreeSitterLanguagePack.process("def broken(\n    return\nclass", { 'diagnostics' => true, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.diagnostics.to_s).not_to be_empty
  end

  it 'python_malformed_code_process_detail: Intel: detect diagnostics in malformed Python code' do    result = TreeSitterLanguagePack.process("def broken(\n    return\nclass", { 'diagnostics' => true, 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.diagnostics.to_s).not_to be_empty
  end

  it 'python_multi_import_process: Intel: detect multiple Python imports' do    result = TreeSitterLanguagePack.process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.imports.length).to be >= 3
    expect(result.metrics.total_lines).to be >= 5
    expect(result.metrics.error_count).to eq(0)
  end

  it 'python_multi_import_process_detail: Intel: detect multiple Python imports' do    result = TreeSitterLanguagePack.process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", { 'language' => 'python' })
    expect(result.language).to eq('python')
    expect(result.structure.length).to be >= 1
    expect(result.imports.length).to be >= 3
    expect(result.metrics.total_lines).to be >= 5
    expect(result.metrics.error_count).to eq(0)
  end

  it 'ruby_class_process: Intel: Ruby class with method' do    result = TreeSitterLanguagePack.process("require 'json'\n\nclass Greeter\n  def greet(name)\n    \"Hello \#{name}\"\n  end\nend\n", { 'language' => 'ruby' })
    expect(result.language).to eq('ruby')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Class') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 7
    expect(result.metrics.error_count).to eq(0)
  end

  it 'rust_chunking_process: Intel: chunk multi-function Rust source into pieces' do    result = TreeSitterLanguagePack.process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", { 'chunk_max_size' => 30, 'language' => 'rust' })
    expect(result.language).to eq('rust')
    expect(result.metrics.total_lines).to be >= 7
    expect(result.chunks.length).to be >= 2
  end

  it 'rust_chunking_process_detail: Intel: chunk multi-function Rust source into pieces' do    result = TreeSitterLanguagePack.process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", { 'chunk_max_size' => 30, 'language' => 'rust' })
    expect(result.language).to eq('rust')
    expect(result.metrics.total_lines).to be >= 7
    expect(result.chunks.length).to be >= 2
  end

  it 'rust_function_process: Intel: extract structure from Rust function definition' do    result = TreeSitterLanguagePack.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", { 'language' => 'rust' })
    expect(result.language).to eq('rust')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 3
    expect(result.metrics.error_count).to eq(0)
  end

  it 'rust_function_process_detail: Intel: extract structure from Rust function definition' do    result = TreeSitterLanguagePack.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", { 'language' => 'rust' })
    expect(result.language).to eq('rust')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.metrics.total_lines).to be >= 3
    expect(result.metrics.error_count).to eq(0)
  end

  it 'typescript_function_process: Intel: extract structure from TypeScript function' do    result = TreeSitterLanguagePack.process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", { 'language' => 'typescript' })
    expect(result.language).to eq('typescript')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 5
    expect(result.metrics.error_count).to eq(0)
  end

  it 'typescript_function_process_detail: Intel: extract structure from TypeScript function' do    result = TreeSitterLanguagePack.process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", { 'language' => 'typescript' })
    expect(result.language).to eq('typescript')
    expect(result.structure.length).to be >= 1
    expect(result.structure.any? { |item| alef_e2e_item_texts(item).any? { |t| t.include?('Function') } }).to be(true)
    expect(result.imports.length).to be >= 1
    expect(result.metrics.total_lines).to be >= 5
    expect(result.metrics.error_count).to eq(0)
  end
end
