# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4a80cf158d12cd198d149d1570f2761b6432b11febc4f0b5e92a7d90977d71e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "ts_pack_core_rb"
