# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c12a0c91b350f00ea392220382bd9dbc251a243082ac1fcb1980863619a973b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "ts_pack_core_rb"
