# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5350ac4762a8031cc74c8c916da39e763ae845fe8b34e7805b87c01e7c2f56bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module TreeSitterLanguagePack
  VERSION = "1.9.0.pre.rc.7"
end
