# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ef492b9fed5c51f426bf570aead00ef7d3ce2a7f5a5e958558fb1d48e9c8a6a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.11.0.pre.rc.2"
end
