# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:77e026bd773d6d9f86385b7ed6896453a6577be5718b969522de9f9f0a69a0a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  VERSION = "1.9.0.pre.rc.18"
end
