/*
 * This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:662c8c2da42487acd47935e52f906833d5bf9fc340a0b376139bea666a13b74c
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 * Issues & docs: https://github.com/kreuzberg-dev/alef
 */
/* E2e tests for category: query */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "tree_sitter_language_pack.h"
#include "test_runner.h"

void test_highlights_nonexistent_language(void) {
    /* Get highlights query for nonexistent language returns null/empty */
    TS_PACKGetHighlightsQuery* result = get_highlights_query("zzz_nonexistent_lang");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) == 0 && "expected empty value");
    ts_pack_get_highlights_query_free(result);
}

void test_highlights_query_python(void) {
    /* get_highlights_query returns non-empty string for python */
    TS_PACKGetHighlightsQuery* result = get_highlights_query("python");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) > 0 && "expected non-empty value");
    ts_pack_get_highlights_query_free(result);
}

void test_highlights_query_unknown_language(void) {
    /* get_highlights_query returns None for unknown language */
    TS_PACKGetHighlightsQuery* result = get_highlights_query("nonexistent_language_xyz");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) == 0 && "expected empty value");
    ts_pack_get_highlights_query_free(result);
}

void test_injections_query_javascript(void) {
    /* get_injections_query returns non-empty for javascript (has embedded languages) */
    TS_PACKGetInjectionsQuery* result = get_injections_query("javascript");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) > 0 && "expected non-empty value");
    ts_pack_get_injections_query_free(result);
}

void test_injections_query_unknown_language(void) {
    /* get_injections_query returns empty for unknown language */
    TS_PACKGetInjectionsQuery* result = get_injections_query("nonexistent_xyz");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) == 0 && "expected empty value");
    ts_pack_get_injections_query_free(result);
}

void test_locals_query_python(void) {
    /* get_locals_query returns non-empty for python */
    TS_PACKGetLocalsQuery* result = get_locals_query("python");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) > 0 && "expected non-empty value");
    ts_pack_get_locals_query_free(result);
}

void test_locals_query_unknown_language(void) {
    /* get_locals_query returns empty for unknown language */
    TS_PACKGetLocalsQuery* result = get_locals_query("nonexistent_xyz");
    assert(result != NULL && "expected call to succeed");
    assert(strlen(result) == 0 && "expected empty value");
    ts_pack_get_locals_query_free(result);
}
