// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fd5b7740ad2bb554e961acb557907f4517bc06020247d8c25c7815d41368365
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: query

use tree_sitter_language_pack::{get_highlights_query, get_injections_query, get_locals_query};

#[test]
fn test_highlights_nonexistent_language() {
    // Get highlights query for nonexistent language returns null/empty
    let language = r#"zzz_nonexistent_lang"#;
    let result = get_highlights_query(language);
    assert!(result.is_none(), "expected Option to be is_none");
}

#[test]
fn test_highlights_query_rust() {
    // get_highlights_query returns non-empty string for rust
    let language = r#"rust"#;
    let result = get_highlights_query(language);
    assert!(result.is_some(), "expected Option to be is_some");
}

#[test]
fn test_highlights_query_unknown_language() {
    // get_highlights_query returns None for unknown language
    let language = r#"nonexistent_language_xyz"#;
    let result = get_highlights_query(language);
    assert!(result.is_none(), "expected Option to be is_none");
}

#[test]
fn test_injections_query_rust() {
    // get_injections_query returns non-empty for rust
    let language = r#"rust"#;
    let result = get_injections_query(language);
    assert!(result.is_some(), "expected Option to be is_some");
}

#[test]
fn test_injections_query_unknown_language() {
    // get_injections_query returns empty for unknown language
    let language = r#"nonexistent_xyz"#;
    let result = get_injections_query(language);
    assert!(result.is_none(), "expected Option to be is_none");
}

#[test]
fn test_locals_query_cue() {
    // get_locals_query returns non-empty for cue
    let language = r#"cue"#;
    let result = get_locals_query(language);
    assert!(result.is_some(), "expected Option to be is_some");
}

#[test]
fn test_locals_query_unknown_language() {
    // get_locals_query returns empty for unknown language
    let language = r#"nonexistent_xyz"#;
    let result = get_locals_query(language);
    assert!(result.is_none(), "expected Option to be is_none");
}
