// DO NOT EDIT - auto-generated by alef
// alef:hash:d5cec6c9d6670c8784127b4b9b50fa3b267f840a375e95e33e28533e39887f8a
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The downloaded file's SHA-256 digest did not match the manifest's expected value.
 */
public class ChecksumMismatchException extends ErrorException {
  /** Creates a new ChecksumMismatchException with the given message. */
  public ChecksumMismatchException(final String message) {
    super(message);
  }

  /** Creates a new ChecksumMismatchException with the given message and cause. */
  public ChecksumMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
