// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2713349db285eae0f6d53c929f35d26579202157f39a471885a509db75eebad4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonAlias;

/**
 * A chunk of source code with rich metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class CodeChunkBuilder {

    private String content = "";
    @JsonProperty("startByte")
    @JsonAlias("start_byte")
    private long startByte = 0;
    @JsonProperty("endByte")
    @JsonAlias("end_byte")
    private long endByte = 0;
    @JsonProperty("startLine")
    @JsonAlias("start_line")
    private long startLine = 0;
    @JsonProperty("endLine")
    @JsonAlias("end_line")
    private long endLine = 0;
    private ChunkContext metadata = null;

    /** Sets the content field. */
    public CodeChunkBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the startByte field. */
    @JsonProperty("startByte")
    @JsonAlias("start_byte")
    public CodeChunkBuilder withStartByte(final long value) {
        this.startByte = value;
        return this;
    }

    /** Sets the endByte field. */
    @JsonProperty("endByte")
    @JsonAlias("end_byte")
    public CodeChunkBuilder withEndByte(final long value) {
        this.endByte = value;
        return this;
    }

    /** Sets the startLine field. */
    @JsonProperty("startLine")
    @JsonAlias("start_line")
    public CodeChunkBuilder withStartLine(final long value) {
        this.startLine = value;
        return this;
    }

    /** Sets the endLine field. */
    @JsonProperty("endLine")
    @JsonAlias("end_line")
    public CodeChunkBuilder withEndLine(final long value) {
        this.endLine = value;
        return this;
    }

    /** Sets the metadata field. */
    public CodeChunkBuilder withMetadata(final ChunkContext value) {
        this.metadata = value;
        return this;
    }

    /** Builds the CodeChunk instance. */
    public CodeChunk build() {
        return new CodeChunk(content, startByte, endByte, startLine, endLine, metadata);
    }
}
