// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d5cec6c9d6670c8784127b4b9b50fa3b267f840a375e95e33e28533e39887f8a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A comment extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CommentInfo.Builder.class)
@SuppressWarnings("PMD")
public record CommentInfo(
    @JsonProperty("text") String text,
    @JsonProperty("kind") CommentKind kind,
    @JsonProperty("span") Span span,
    @Nullable @JsonProperty("associated_node") String associatedNode) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String text = "";
    private CommentKind kind = null;
    private Span span = null;

    @JsonProperty("associated_node")
    private String associatedNode = null;

    /** Sets the text field. */
    @JsonProperty("text")
    public Builder withText(final String value) {
      this.text = value;
      return this;
    }

    /** Sets the kind field. */
    @JsonProperty("kind")
    public Builder withKind(final CommentKind value) {
      this.kind = value;
      return this;
    }

    /** Sets the span field. */
    @JsonProperty("span")
    public Builder withSpan(final Span value) {
      this.span = value;
      return this;
    }

    /** Sets the associatedNode field. */
    @JsonProperty("associated_node")
    public Builder withAssociatedNode(final @Nullable String value) {
      this.associatedNode = value;
      return this;
    }

    /** Builds the CommentInfo instance. */
    public CommentInfo build() {
      return new CommentInfo(text, kind, span, associatedNode);
    }
  }
  // CPD-ON
}
