// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c34356ad8d16f7792615d4239cb919975a5c8d21d13fd9ca8630a023ec39c513
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.Optional;

/**
 * A comment extracted from source code.
 */
public class CommentInfoBuilder {

    private String text = "";
    private CommentKind kind = null;
    private Span span = null;
    private Optional<String> associatedNode = Optional.empty();

    /** Sets the text field. */
    public CommentInfoBuilder withText(final String value) {
        this.text = value;
        return this;
    }

    /** Sets the kind field. */
    public CommentInfoBuilder withKind(final CommentKind value) {
        this.kind = value;
        return this;
    }

    /** Sets the span field. */
    public CommentInfoBuilder withSpan(final Span value) {
        this.span = value;
        return this;
    }

    /** Sets the associatedNode field. */
    public CommentInfoBuilder withAssociatedNode(final Optional<String> value) {
        this.associatedNode = value;
        return this;
    }

    /** Builds the CommentInfo instance. */
    public CommentInfo build() {
        return new CommentInfo(text, kind, span, associatedNode);
    }
}
