// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fd5b7740ad2bb554e961acb557907f4517bc06020247d8c25c7815d41368365
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Severity level of a diagnostic produced during parsing.
 *
 * Used to classify parse errors, warnings, and informational messages
 * found in the syntax tree.
 */
public enum DiagnosticSeverity {
  Error("error"),
  Warning("warning"),
  Info("info");

  /** The string value. */
  private final String value;

  DiagnosticSeverity(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static DiagnosticSeverity fromValue(final String value) {
    for (DiagnosticSeverity e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown DiagnosticSeverity value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
