// DO NOT EDIT - auto-generated by alef
// alef:hash:3c151d14314449759d569362f0a875efa94b8855f8e2f8c545175edc5635de17
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A parser download from GitHub releases failed.
 */
public class DownloadException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DownloadException with the given message. */
  public DownloadException(final String message) {
    super(message);
  }

  /** Creates a new DownloadException with the given message and cause. */
  public DownloadException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
