// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6c258a20ebfddd074592606d754e7ca338d9ae406fd413fe81e0164d67af105a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * An export statement extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExportInfo.Builder.class)
@SuppressWarnings("PMD")
public record ExportInfo(
    @JsonProperty("name") String name,
    @JsonProperty("kind") ExportKind kind,
    @JsonProperty("span") Span span) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String name = "";
    private ExportKind kind = null;
    private Span span = null;

    /** Sets the name field. */
    @JsonProperty("name")
    public Builder withName(final String value) {
      this.name = value;
      return this;
    }

    /** Sets the kind field. */
    @JsonProperty("kind")
    public Builder withKind(final ExportKind value) {
      this.kind = value;
      return this;
    }

    /** Sets the span field. */
    @JsonProperty("span")
    public Builder withSpan(final Span value) {
      this.span = value;
      return this;
    }

    /** Builds the ExportInfo instance. */
    public ExportInfo build() {
      return new ExportInfo(name, kind, span);
    }
  }
  // CPD-ON
}
