// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76f3bac7536fa4e5b8ab9a93be197508306d06b566fe7cc519a38c1b9ebf9f42
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends TreeSitterLanguagePackRsException {
    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
