// DO NOT EDIT - auto-generated by alef
// alef:hash:cea39f27c7b86439ba4384f63c1434154e6c1b7e45a9ac9f165d495df848c358
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
