// DO NOT EDIT - auto-generated by alef
// alef:hash:fac0bd795b516381257c10b27a86279c82639b79d31e15965a37bcc80fa7ed48
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
