// DO NOT EDIT - auto-generated by alef
// alef:hash:4b429c75a5259a2bfb85ca3a02707766f9539046f769bda21b99081f8d95ea0d
package dev.kreuzberg.treesitterlanguagepack;

public class ParserSetupException extends ErrorException {
    /** Creates a new ParserSetupException with the given message. */
    public ParserSetupException(final String message) {
        super(message);
    }

    /** Creates a new ParserSetupException with the given message and cause. */
    public ParserSetupException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
