// DO NOT EDIT - auto-generated by alef
// alef:hash:c4a80cf158d12cd198d149d1570f2761b6432b11febc4f0b5e92a7d90977d71e
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The language could not be applied to the parser (e.g., ABI version mismatch).
 */
public class ParserSetupException extends ErrorException {
    /** Creates a new ParserSetupException with the given message. */
    public ParserSetupException(final String message) {
        super(message);
    }

    /** Creates a new ParserSetupException with the given message and cause. */
    public ParserSetupException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
