// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fa50f7110c4a4289a24006907fd79c77ae706dded59fd1c9b81bf8e9a3e116e5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PlatformBundle(String url, String sha256, long size) {
}
