// DO NOT EDIT - auto-generated by alef
// alef:hash:086b0ecfebe5a56c28571b782f7822fd94583b62b8cb3ca39f146df63bbaa326
package dev.kreuzberg.treesitterlanguagepack;

public class QueryErrorException extends ErrorException {
    /** Creates a new QueryErrorException with the given message. */
    public QueryErrorException(final String message) {
        super(message);
    }

    /** Creates a new QueryErrorException with the given message and cause. */
    public QueryErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
