// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:13daa663146126705b01675d33be00ca38900a990637793e0d82f579d36dafea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Byte and line/column range in source code.
 *
 * Represents both byte offsets (for slicing) and human-readable line/column positions (for display and diagnostics).
 */
@JsonPOJOBuilder(withPrefix = "with")
public class SpanBuilder {

    @JsonProperty("start_byte")
    private long startByte = 0;
    @JsonProperty("end_byte")
    private long endByte = 0;
    @JsonProperty("start_line")
    private long startLine = 0;
    @JsonProperty("start_column")
    private long startColumn = 0;
    @JsonProperty("end_line")
    private long endLine = 0;
    @JsonProperty("end_column")
    private long endColumn = 0;

    /** Sets the startByte field. */
    @JsonProperty("start_byte")
    public SpanBuilder withStartByte(final long value) {
        this.startByte = value;
        return this;
    }

    /** Sets the endByte field. */
    @JsonProperty("end_byte")
    public SpanBuilder withEndByte(final long value) {
        this.endByte = value;
        return this;
    }

    /** Sets the startLine field. */
    @JsonProperty("start_line")
    public SpanBuilder withStartLine(final long value) {
        this.startLine = value;
        return this;
    }

    /** Sets the startColumn field. */
    @JsonProperty("start_column")
    public SpanBuilder withStartColumn(final long value) {
        this.startColumn = value;
        return this;
    }

    /** Sets the endLine field. */
    @JsonProperty("end_line")
    public SpanBuilder withEndLine(final long value) {
        this.endLine = value;
        return this;
    }

    /** Sets the endColumn field. */
    @JsonProperty("end_column")
    public SpanBuilder withEndColumn(final long value) {
        this.endColumn = value;
        return this;
    }

    /** Builds the Span instance. */
    public Span build() {
        return new Span(startByte, endByte, startLine, startColumn, endLine, endColumn);
    }
}
