// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10aa1e9a92cfbf4b4c6ed24b19b15a5dd32dbc5c78fee9598c936dbe07ceb7e8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of structural item found in source code.
 *
 * Categorizes top-level and nested declarations such as functions, classes,
 * structs, enums, traits, and more. Use Other(StructureKind.Other) for
 * language-specific constructs that do not fit a standard category.
 */
@SuppressWarnings("PMD")
public enum StructureKind {
  /**
   * A free-standing or associated function.
   */
  Function("function"),
  /**
   * A method defined inside a class, struct, trait, or impl block.
   */
  Method("method"),
  /**
   * A class definition.
   */
  Class("class"),
  /**
   * A struct definition.
   */
  Struct("struct"),
  /**
   * An interface or protocol definition.
   */
  Interface("interface"),
  /**
   * An enum definition.
   */
  Enum("enum"),
  /**
   * A module or package declaration.
   */
  Module("module"),
  /**
   * A trait definition.
   */
  Trait("trait"),
  /**
   * An impl block (Rust) or similar implementation block.
   */
  Impl("impl"),
  /**
   * A namespace declaration.
   */
  Namespace("namespace"),
  /**
   * A language-specific construct that does not fit any standard category.
   */
  Other("other");

  /** The string value. */
  private final String value;

  StructureKind(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static StructureKind fromValue(final String value) {
    for (StructureKind e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown StructureKind value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
