// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:acea65785243ddcf3216cc7e3e5975421161e683fc7cd92dc563f8325a123417
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of a symbol definition found in source code.
 *
 * Categorizes symbol definitions such as variables, constants, functions,
 * classes, types, interfaces, enums, and modules.
 */
@SuppressWarnings("PMD")
public enum SymbolKind {
    /**
     * A variable binding.
     */
    Variable("variable"),
    /**
     * A constant (immutable binding).
     */
    Constant("constant"),
    /**
     * A function definition.
     */
    Function("function"),
    /**
     * A class definition.
     */
    Class("class"),
    /**
     * A type alias or typedef.
     */
    Type("type"),
    /**
     * An interface definition.
     */
    Interface("interface"),
    /**
     * An enum definition.
     */
    Enum("enum"),
    /**
     * A module declaration.
     */
    Module("module"),
    /**
     * A symbol kind not covered by the standard variants.
     */
    Other("other");


    /** The string value. */
    private final String value;

    SymbolKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static SymbolKind fromValue(final String value) {
        for (SymbolKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown SymbolKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
