// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f589ef0e90cd0dd3ac00f4d4743e5361d384979b83039a14a6c3b78bad94d7a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * A symbol (variable, function, type, etc.) extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SymbolInfoBuilder.class)
public record SymbolInfo(String name, Object kind, Span span,
        @Nullable @JsonProperty("type_annotation") String typeAnnotation, @Nullable String doc) {
    public static SymbolInfoBuilder builder() {
        return new SymbolInfoBuilder();
    }
}
