// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:784d27f93731854d18c43dcb00f35d51a222b4d9e461c8d31f9eb5d26755a612
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class TreeSitterLanguagePackRsException extends Exception {
  /** The error code. */
  private final int code;

  /** Creates a new TreeSitterLanguagePackRsException. */
  public TreeSitterLanguagePackRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new TreeSitterLanguagePackRsException with a cause. */
  public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
