# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7663cb2aa71115595496ea13ba09e75ec98b9d440f84b9ac3b086781aff35d9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy."""


class Error(Exception):
    """Errors that can occur when using the tree-sitter language pack."""


class LanguageNotFoundError(Error):
    """Language not found error."""


class DynamicLoadError(Error):
    """Dynamic load error."""


class NullLanguagePointerError(Error):
    """Null language pointer error."""


class ParserSetupError(Error):
    """Parser setup error."""


class LockPoisonedError(Error):
    """Lock poisoned error."""


class ConfigError(Error):
    """Config error."""


class ParseFailedError(Error):
    """Parse failed error."""


class QueryError(Error):
    """Query error."""


class InvalidRangeError(Error):
    """Invalid range error."""


class DownloadError(Error):
    """Download error."""


class ChecksumMismatchError(Error):
    """Checksum mismatch error."""


class CacheLockError(Error):
    """Cache lock error."""
