// Generated by alef. Do not edit by hand.
// alef:hash:26c4710d296d1ec8b0c7d2d0f8c8d60306d8234c2519a3c0009269a2d04dfa30
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/** Aggregate metrics for a source file. */
data class FileMetrics(
    /** Total number of lines (including blank and comment lines). */
    val totalLines: Long = 0L,
    /** Number of lines containing non-blank, non-comment source code. */
    val codeLines: Long = 0L,
    /** Number of lines that are entirely comments. */
    val commentLines: Long = 0L,
    /** Number of blank (whitespace-only) lines. */
    val blankLines: Long = 0L,
    /** Total byte length of the source file. */
    val totalBytes: Long = 0L,
    /** Total number of nodes in the syntax tree. */
    val nodeCount: Long = 0L,
    /** Number of error nodes in the syntax tree (parse errors). */
    val errorCount: Long = 0L,
    /** Maximum nesting depth reached in the syntax tree. */
    val maxDepth: Long = 0L,
)
