// Generated by alef. Do not edit by hand.
// alef:hash:ef0d506973d77d833c41a62537a6589d91d8518856847ee94cda1247349f9ff5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.tslp.android

/** A source position — row + column, zero-indexed. */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class Point(
    /** Zero-indexed row number. */
    val row: Long,
    /**
     * Zero-indexed column, counted in **bytes** from the start of the row.
     *
     * This is `tree_sitter.Point.column` verbatim, and tree-sitter defines it
     * as a byte offset — not characters, and not UTF-16 code units. Measured on
     * a row of the form `x = '<c>'` where `<c>` is a single 4-byte character
     * (an emoji), the string node reports columns `4..10`, identical to its
     * byte range; the character columns would be `4..7` and the UTF-16 columns
     * `4..8`.
     *
     * Anything that builds LSP positions (UTF-16) or editor caret columns
     * (characters) from this field is silently wrong on every row containing a
     * non-ASCII byte, and must re-measure the row against the source text
     * instead. Earlier releases documented this field as UTF-16 code units;
     * that was never what the value contained.
     */
    val column: Long,
)
