# frozen_string_literal: true

source 'https://rubygems.org'

gem 'tree_sitter_language_pack', path: '../../packages/ruby'
gem 'rspec', '~> 3.13'
gem 'rubocop', '~> 1.86'
gem 'rubocop-rspec', '~> 3.9'
gem 'faraday', '~> 2.0'
