// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc46a63a4ec02e916a212eedf7a4b7d5ccb0deb437ee6b5de2474985e9f582bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
