// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1c54af27d1b41b9f2152ed115bb5967dcdd5768818a55e4a1d090fd8559832c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
  },
});
