// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e454d132199a54f23e980eca266b41edc650e9fc44e16dd229505bddaa0f36f3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
