// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:26c4710d296d1ec8b0c7d2d0f8c8d60306d8234c2519a3c0009269a2d04dfa30
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
