// Generated by alef. Do not edit by hand.
//
// JNI shim for the Android AAR.  Every `pub unsafe extern "system" fn`
// here matches one `external fun native*` in the paired Kotlin Bridge object.

#![allow(non_snake_case)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::missing_safety_doc)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]

use futures_util::StreamExt;
use futures_util::stream::BoxStream;
use jni::JNIEnv;
use jni::objects::{JClass, JObject, JString};
use jni::sys::{jboolean, jbyteArray, jlong, jstring};
use std::sync::Mutex;
use std::sync::OnceLock;
use tokio::runtime::Runtime;

use core_crate::*;
use tree_sitter_language_pack as core_crate; // bring trait methods into scope

const ERROR_CLASS: &str = "dev/kreuzberg/tslp/android/TreeSitterLanguagePackBridgeException";

fn runtime() -> &'static Runtime {
    static RT: OnceLock<Runtime> = OnceLock::new();
    RT.get_or_init(|| Runtime::new().expect("create tokio runtime"))
}

fn jstring_to_string(env: &mut JNIEnv, s: JString) -> std::result::Result<String, jni::errors::Error> {
    let jstr = env.get_string(&s)?;
    Ok(jstr.into())
}

fn string_to_jstring(env: &mut JNIEnv, s: &str) -> jstring {
    match env.new_string(s) {
        Ok(o) => o.into_raw(),
        Err(_) => std::ptr::null_mut(),
    }
}

fn throw_jni_error(env: &mut JNIEnv, msg: &str) {
    let _ = env.throw_new(ERROR_CLASS, msg);
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDetectLanguageFromExtension(
    mut env: JNIEnv,
    _class: JClass,
    ext: JString,
) -> jstring {
    let ext = match jstring_to_string(&mut env, ext) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::detect_language_from_extension(&ext);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDetectLanguageFromPath(
    mut env: JNIEnv,
    _class: JClass,
    path: JString,
) -> jstring {
    let path = match jstring_to_string(&mut env, path) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::detect_language_from_path(&path);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDetectLanguageFromContent(
    mut env: JNIEnv,
    _class: JClass,
    content: JString,
) -> jstring {
    let content = match jstring_to_string(&mut env, content) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::detect_language_from_content(&content);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeGetHighlightsQuery(
    mut env: JNIEnv,
    _class: JClass,
    language: JString,
) -> jstring {
    let language = match jstring_to_string(&mut env, language) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::get_highlights_query(&language);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeGetInjectionsQuery(
    mut env: JNIEnv,
    _class: JClass,
    language: JString,
) -> jstring {
    let language = match jstring_to_string(&mut env, language) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::get_injections_query(&language);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeGetLocalsQuery(
    mut env: JNIEnv,
    _class: JClass,
    language: JString,
) -> jstring {
    let language = match jstring_to_string(&mut env, language) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::get_locals_query(&language);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeGetLanguage(
    mut env: JNIEnv,
    _class: JClass,
    name: JString,
) -> jlong {
    let name = match jstring_to_string(&mut env, name) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let result = core_crate::get_language(&name);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            0
        }
        Ok(v) => Box::into_raw(Box::new(v)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeGetParser(
    mut env: JNIEnv,
    _class: JClass,
    name: JString,
) -> jlong {
    let name = match jstring_to_string(&mut env, name) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let result = core_crate::get_parser(&name);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            0
        }
        Ok(v) => Box::into_raw(Box::new(v)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDetectLanguage(
    mut env: JNIEnv,
    _class: JClass,
    path: JString,
) -> jstring {
    let path = match jstring_to_string(&mut env, path) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::detect_language(&path);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeAvailableLanguages(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let v = core_crate::available_languages();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeHasLanguage(
    mut env: JNIEnv,
    _class: JClass,
    name: JString,
) -> jstring {
    let name = match jstring_to_string(&mut env, name) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let v = core_crate::has_language(&name);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageCount(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let v = core_crate::language_count();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeProcess(
    mut env: JNIEnv,
    _class: JClass,
    source: JString,
    config: JString,
) -> jstring {
    let source = match jstring_to_string(&mut env, source) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let config_str = match jstring_to_string(&mut env, config) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let config: core_crate::ProcessConfig = match serde_json::from_str(&config_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("deserialize: {e}"));
            return std::ptr::null_mut();
        }
    };
    let result = core_crate::process(&source, &config);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeInit(
    mut env: JNIEnv,
    _class: JClass,
    config: JString,
) -> jstring {
    let config_str = match jstring_to_string(&mut env, config) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let config: core_crate::PackConfig = match serde_json::from_str(&config_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("deserialize: {e}"));
            return std::ptr::null_mut();
        }
    };
    let result = core_crate::init(&config);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => string_to_jstring(&mut env, "null"),
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeConfigure(
    mut env: JNIEnv,
    _class: JClass,
    config: JString,
) -> jstring {
    let config_str = match jstring_to_string(&mut env, config) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let config: core_crate::PackConfig = match serde_json::from_str(&config_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("deserialize: {e}"));
            return std::ptr::null_mut();
        }
    };
    let result = core_crate::configure(&config);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => string_to_jstring(&mut env, "null"),
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownload(
    mut env: JNIEnv,
    _class: JClass,
    names: JString,
) -> jstring {
    let names_str = match jstring_to_string(&mut env, names) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let names: Vec<String> = match serde_json::from_str(&names_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("deserialize: {e}"));
            return std::ptr::null_mut();
        }
    };
    let result = core_crate::download(&names);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadAll(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let result = core_crate::download_all();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeManifestLanguages(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let result = core_crate::manifest_languages();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadedLanguages(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let v = core_crate::downloaded_languages();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeCleanCache(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let result = core_crate::clean_cache();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => string_to_jstring(&mut env, "null"),
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeCacheDir(
    mut env: JNIEnv,
    _class: JClass,
) -> jstring {
    let result = core_crate::cache_dir();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeParserSetLanguage(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::Parser = unsafe { &mut *(handle as *mut core_crate::Parser) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return ();
        }
    };
    let name: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let result = client.set_language(&name);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            ()
        }
        Ok(v) => {}
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeParserParse(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::Parser = unsafe { &mut *(handle as *mut core_crate::Parser) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let source: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let v = client.parse(&source);
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeParserParseBytes(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    source: jbyteArray,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::Parser = unsafe { &mut *(handle as *mut core_crate::Parser) };
    let source_jarr = unsafe { jni::objects::JByteArray::from_raw(source) };
    let source: Vec<u8> = match env.convert_byte_array(&source_jarr) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let v = client.parse_bytes(&source);
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeParserReset(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::Parser = unsafe { &mut *(handle as *mut core_crate::Parser) };
    let v = client.reset();
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeParser(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::Parser);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeRootNode(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Tree = unsafe { &*(handle as *const core_crate::Tree) };
    let v = client.root_node();
    Box::into_raw(Box::new(v)) as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeWalk(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Tree = unsafe { &*(handle as *const core_crate::Tree) };
    let v = client.walk();
    Box::into_raw(Box::new(v)) as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeTree(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::Tree);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeClone(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.clone();
    Box::into_raw(Box::new(v)) as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeKind(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.kind();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeKindId(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jni::sys::jshort {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.kind_id();
    v as jni::sys::jshort
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeStartByte(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.start_byte();
    v as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeEndByte(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.end_byte();
    v as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeByteRange(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.byte_range();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeStartPosition(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.start_position();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeEndPosition(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.end_position();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeIsNamed(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.is_named();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeIsError(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.is_error();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeIsMissing(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.is_missing();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeIsExtra(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.is_extra();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeHasError(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.has_error();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeParent(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.parent();
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeChild(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let index: u32 = match serde_json::from_str(&req_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("request deserialize: {e}"));
            return 0;
        }
    };
    let v = client.child(index);
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeChildCount(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.child_count();
    v as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeNamedChild(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let index: u32 = match serde_json::from_str(&req_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("request deserialize: {e}"));
            return 0;
        }
    };
    let v = client.named_child(index);
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeNamedChildCount(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.named_child_count();
    v as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeChildByFieldName(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let name: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let v = client.child_by_field_name(&name);
    match v {
        None => 0i64,
        Some(inner) => Box::into_raw(Box::new(inner)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeToSexp(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.to_sexp();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeNodeWalk(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::Node = unsafe { &*(handle as *const core_crate::Node) };
    let v = client.walk();
    Box::into_raw(Box::new(v)) as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeNode(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::Node);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeCursorNode(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::TreeCursor = unsafe { &*(handle as *const core_crate::TreeCursor) };
    let v = client.node();
    Box::into_raw(Box::new(v)) as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeCursorGotoFirstChild(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::TreeCursor = unsafe { &mut *(handle as *mut core_crate::TreeCursor) };
    let v = client.goto_first_child();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeCursorGotoParent(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::TreeCursor = unsafe { &mut *(handle as *mut core_crate::TreeCursor) };
    let v = client.goto_parent();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeCursorGotoNextSibling(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &mut core_crate::TreeCursor = unsafe { &mut *(handle as *mut core_crate::TreeCursor) };
    let v = client.goto_next_sibling();
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeTreeCursorFieldName(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::TreeCursor = unsafe { &*(handle as *const core_crate::TreeCursor) };
    let v = client.field_name();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeTreeCursor(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::TreeCursor);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryAddExtraLibsDir(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return ();
        }
    };
    let dir = std::path::PathBuf::from(req_str);
    let v = client.add_extra_libs_dir(dir);
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryGetLanguage(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0;
        }
    };
    let name: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let result = client.get_language(&name);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            0
        }
        Ok(v) => Box::into_raw(Box::new(v)) as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryAvailableLanguages(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let v = client.available_languages();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryHasLanguage(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jboolean {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return 0u8;
        }
    };
    let name: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let v = client.has_language(&name);
    v as jboolean
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryLanguageCount(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let v = client.language_count();
    v as jlong
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeLanguageRegistryProcess(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::LanguageRegistry = unsafe { &*(handle as *const core_crate::LanguageRegistry) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("invalid request_json: {e}"));
            return std::ptr::null_mut();
        }
    };
    let req_map: serde_json::Map<String, serde_json::Value> = match serde_json::from_str(&req_str) {
        Ok(m) => m,
        Err(e) => {
            throw_jni_error(&mut env, &format!("param deserialize: {e}"));
            return std::ptr::null_mut();
        }
    };
    let source: String = match req_map
        .get("source")
        .and_then(|v| serde_json::from_value(v.clone()).ok())
    {
        Some(v) => v,
        None => {
            throw_jni_error(&mut env, "missing param: source");
            return std::ptr::null_mut();
        }
    };
    let config: core_crate::ProcessConfig = match req_map
        .get("config")
        .and_then(|v| serde_json::from_value(v.clone()).ok())
    {
        Some(v) => v,
        None => {
            throw_jni_error(&mut env, "missing param: config");
            return std::ptr::null_mut();
        }
    };
    let result = client.process(&source, &config);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeLanguageRegistry(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::LanguageRegistry);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerCacheDir(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let v = client.cache_dir();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerInstalledLanguages(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let v = client.installed_languages();
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerEnsureLanguages(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return ();
        }
    };
    let names_vec: Vec<String> = match serde_json::from_str(&req_str) {
        Ok(v) => v,
        Err(e) => {
            throw_jni_error(&mut env, &format!("request deserialize: {e}"));
            return ();
        }
    };
    let names = names_vec.clone();
    let names_refs: Vec<&str> = names_vec.iter().map(String::as_str).collect();
    let result = client.ensure_languages(&names_refs);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            ()
        }
        Ok(v) => {}
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerEnsureGroup(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return ();
        }
    };
    let group: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let result = client.ensure_group(&group);
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            ()
        }
        Ok(v) => {}
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerLibPath(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
    request_json: JString,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let req_str = match jstring_to_string(&mut env, request_json) {
        Ok(s) => s,
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            return std::ptr::null_mut();
        }
    };
    let name: String = match serde_json::from_str(&req_str) {
        Ok(s) => s,
        Err(_) => req_str,
    };
    let v = client.lib_path(&name);
    let s = serde_json::to_string(&v).unwrap_or_default();
    string_to_jstring(&mut env, &s)
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerFetchManifest(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jstring {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let result = client.fetch_manifest();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            std::ptr::null_mut()
        }
        Ok(v) => {
            let s = serde_json::to_string(&v).unwrap_or_default();
            string_to_jstring(&mut env, &s)
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerDownloadAllBestEffort(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) -> jlong {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let result = client.download_all_best_effort();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            0
        }
        Ok(v) => v as jlong,
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeDownloadManagerCleanCache(
    mut env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    // SAFETY: handle was allocated by the matching constructor shim and remains
    // valid until nativeFree is called. The Kotlin AutoCloseable.close() guarantee
    // ensures the handle outlives this call.
    let client: &core_crate::DownloadManager = unsafe { &*(handle as *const core_crate::DownloadManager) };
    let result = client.clean_cache();
    match result {
        Err(e) => {
            throw_jni_error(&mut env, &format!("{e}"));
            ()
        }
        Ok(v) => {}
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeDownloadManager(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::DownloadManager);
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "system" fn Java_dev_kreuzberg_tslp_android_TreeSitterLanguagePackBridge_nativeFreeLanguage(
    _env: JNIEnv,
    _class: JClass,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    // SAFETY: `handle` was allocated by the matching constructor shim and
    // ownership is transferred back here for drop via Box::from_raw.
    unsafe {
        let _ = Box::from_raw(handle as *mut core_crate::Language);
    }
}
