// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:79c6eab795fde63c4edfa96214b4a1b9a86ea3131238c6ad76bbe0c5936ccdab
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/ts_pack.h");

    // Set @rpath-relative install_name on macOS so the cdylib can be relocated
    // (bundled into language packages like packages/go/.lib/<rid>/, packages/
    // java/src/main/resources/natives/<rid>/, etc.) and located via the consumer
    // binary's rpath at runtime. Without this, the install_name embeds the CI
    // runner build path (`/Users/runner/work/.../target/.../deps/lib<name>.dylib`)
    // and dyld fails to load the bundled copy from its actual location.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-arg-cdylib=-Wl,-install_name,@rpath/libts_pack_core_ffi.dylib");
    }

    let go_include_dir = std::path::Path::new("../../packages/go/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/ts_pack.h", go_include_dir.join("ts_pack.h"))
        .expect("Unable to copy header to Go include directory");
}
