// DO NOT EDIT - auto-generated by alef
// alef:hash:d0b7cd41ab5c9284ea1bdf3bc59373cf38b0a5148eb158533b7694f35060156f
package io.xberg.treesitterlanguagepack;

/**
 * A byte range was invalid (e.g., end before start, or out of bounds).
 */
public class InvalidRangeException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidRangeException with the given message. */
  public InvalidRangeException(final String message) {
    super(message);
  }

  /** Creates a new InvalidRangeException with the given message and cause. */
  public InvalidRangeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
