// DO NOT EDIT - auto-generated by alef
// alef:hash:ef492b9fed5c51f426bf570aead00ef7d3ce2a7f5a5e958558fb1d48e9c8a6a5
package io.xberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
