// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:acea65785243ddcf3216cc7e3e5975421161e683fc7cd92dc563f8325a123417
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const tree_sitter_language_pack = @import("tree_sitter_language_pack");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: smoke

test "smoke_bash" {
    // Smoke test: load bash and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("echo hello", "{\"language\":\"bash\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_c" {
    // Smoke test: load c and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("int main() { return 0; }", "{\"language\":\"c\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_cpp" {
    // Smoke test: load cpp and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("int main() { return 0; }", "{\"language\":\"cpp\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_css" {
    // Smoke test: load css and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("body { color: red; }", "{\"language\":\"css\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_go" {
    // Smoke test: load go and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("package main", "{\"language\":\"go\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_html" {
    // Smoke test: load html and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("<p>hello</p>", "{\"language\":\"html\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_java" {
    // Smoke test: load java and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("class Main {}", "{\"language\":\"java\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_javascript" {
    // Smoke test: load javascript and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("console.log('hello');", "{\"language\":\"javascript\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_json" {
    // Smoke test: load json and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("{\"key\": \"value\"}", "{\"language\":\"json\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_kotlin" {
    // Smoke test: load kotlin and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("fun main() {}", "{\"language\":\"kotlin\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_mojo" {
    // Smoke test: load mojo and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("x", "{\"language\":\"mojo\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_nim" {
    // Smoke test: load nim and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("echo \"hello\"", "{\"language\":\"nim\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_norg" {
    // Smoke test: load norg and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("x", "{\"language\":\"norg\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_python" {
    // Smoke test: load python and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("print('hello')", "{\"language\":\"python\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_ruby" {
    // Smoke test: load ruby and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("puts 'hello'", "{\"language\":\"ruby\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_rust" {
    // Smoke test: load rust and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("fn main() {}", "{\"language\":\"rust\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_swift" {
    // Smoke test: load swift and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("print(\"hello\")", "{\"language\":\"swift\"}");
    defer std.heap.c_allocator.free(_result_json);
}

test "smoke_typescript" {
    // Smoke test: load typescript and parse a simple snippet
    suppress_abort();
    const _result_json = try tree_sitter_language_pack.process("const x: number = 42;", "{\"language\":\"typescript\"}");
    defer std.heap.c_allocator.free(_result_json);
}
