<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14bae4a1bd6da3a86ca49b9bd1d955e74385ced3021f8d6f87e63660e7030b24
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A parsed syntax tree. Cheap to clone (refcount bump).
 */
final class Tree
{
    /**
     * Return the root `Node` of this tree.
     */
    public function rootNode(): Node
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Return a `TreeCursor` positioned at the root.
     */
    public function walk(): TreeCursor
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
