<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d5cec6c9d6670c8784127b4b9b50fa3b267f840a375e95e33e28533e39887f8a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A cursor for traversing a `Tree`.
 */
final class TreeCursor
{
    /**
     * Return the `Node` at the cursor's current position.
     */
    public function node(): Node
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Move the cursor to the first child of the current node.
     */
    public function gotoFirstChild(): bool
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Move the cursor to the parent of the current node.
     */
    public function gotoParent(): bool
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Move the cursor to the next sibling of the current node.
     */
    public function gotoNextSibling(): bool
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Return the field name for the current node, if any.
     */
    public function fieldName(): ?string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
