<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d5cec6c9d6670c8784127b4b9b50fa3b267f840a375e95e33e28533e39887f8a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A parsed syntax tree. Cheap to clone (refcount bump).
 */
final class Tree
{
    /**
     * Return the root `Node` of this tree.
     */
    public function rootNode(): Node
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Return a `TreeCursor` positioned at the root.
     */
    public function walk(): TreeCursor
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
