# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e36e29fa3708f2b3bef2700d24af80a550f146a8fdaee10e844b14c19acac509
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: download."""

from tree_sitter_language_pack import (
    download_all,
    cache_dir,
    clean_cache,
    configure,
    downloaded_languages,
    init,
    manifest_languages,
    download,
)


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


def test_download_all_languages() -> None:
    """Download all language parsers and verify count is positive."""
    result = download_all()
    assert result > 0  # noqa: S101


def test_download_cache_dir() -> None:
    """Get the cache directory path and verify it is non-empty."""
    result = cache_dir()
    assert result  # noqa: S101


def test_download_clean_cache() -> None:
    """Clean the parser cache directory."""
    _ = clean_cache()


def test_download_configure_custom_dir() -> None:
    """Configure language pack with a custom cache directory."""
    config = {"cache_dir": "/tmp/tslp_test_cache"}  # noqa: S108
    _ = configure(config=config)


def test_download_downloaded_empty() -> None:
    """List downloaded languages (may be empty before any downloads)."""
    _ = downloaded_languages()


def test_download_init_default() -> None:
    """Initialize language pack with default config."""
    config = {}
    _ = init(config=config)


def test_download_manifest_languages() -> None:
    """List manifest languages and verify the full downloadable catalog."""
    result = manifest_languages()
    assert result  # noqa: S101
    assert len(result) >= 300  # noqa: S101
    assert "python" in result  # noqa: S101


def test_download_single_language() -> None:
    """Download a single language parser and verify count."""
    names = ["python"]
    result = download(names=names)
    assert result >= 1  # noqa: S101
