// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:966b101e2b4cacb4cb93c43f34e30e8bab6e2478b171704ec0a66561b9335a89
pub const api = @import("tree_sitter_language_pack.zig");
