<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5667968889e591e77e0ad9857f45ce9aec26e5e7fff95847e604343f73d3e2dc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Type stubs for the native PHP extension — declares classes
// provided at runtime by the compiled Rust extension (.so/.dll).
// Include this in phpstan.neon scanFiles for static analysis.

declare(strict_types=1);

namespace Tree\Sitter\Language\Pack {
class TreeSitterLanguagePackException extends \RuntimeException
{
    public function getErrorCode(): int { throw new \RuntimeException('Not implemented.'); }
}

/**
 * Byte and line/column range in source code.
 *
 * Represents both byte offsets (for slicing) and human-readable line/column
 * positions (for display and diagnostics).
 */
final class Span
{
    public function __construct(
        /** @var int */
        public readonly int $startByte,
        /** @var int */
        public readonly int $endByte,
        /** @var int */
        public readonly int $startLine,
        /** @var int */
        public readonly int $startColumn,
        /** @var int */
        public readonly int $endLine,
        /** @var int */
        public readonly int $endColumn
    ) { }
}

/**
 * Complete analysis result from processing a source file.
 *
 * Contains metrics, structural analysis, imports/exports, comments,
 * docstrings, symbols, diagnostics, and optionally chunked code segments.
 * Fields are populated based on the `ProcessConfig` flags.
 *
 * # Fields
 *
 * - `language` - The language used for parsing
 * - `metrics` - Always computed: line counts, byte sizes, error counts
 * - `structure` - Functions, classes, structs (when `config.structure = true`)
 * - `imports` - Import statements (when `config.imports = true`)
 * - `exports` - Export statements (when `config.exports = true`)
 * - `comments` - Comments (when `config.comments = true`)
 * - `docstrings` - Docstrings (when `config.docstrings = true`)
 * - `symbols` - Symbol definitions (when `config.symbols = true`)
 * - `diagnostics` - Parse errors (when `config.diagnostics = true`)
 * - `chunks` - Chunked code segments (when `config.chunk_max_size` is set)
 */
final class ProcessResult
{
    public function __construct(
        /** @var string */
        public readonly string $language,
        /** @var FileMetrics */
        public readonly FileMetrics $metrics,
        /** @var array<StructureItem> */
        public readonly array $structure,
        /** @var array<ImportInfo> */
        public readonly array $imports,
        /** @var array<ExportInfo> */
        public readonly array $exports,
        /** @var array<CommentInfo> */
        public readonly array $comments,
        /** @var array<DocstringInfo> */
        public readonly array $docstrings,
        /** @var array<SymbolInfo> */
        public readonly array $symbols,
        /** @var array<Diagnostic> */
        public readonly array $diagnostics,
        /** @var array<CodeChunk> */
        public readonly array $chunks
    ) { }
}

/**
 * Aggregate metrics for a source file.
 */
final class FileMetrics
{
    public function __construct(
        /** @var int */
        public readonly int $totalLines,
        /** @var int */
        public readonly int $codeLines,
        /** @var int */
        public readonly int $commentLines,
        /** @var int */
        public readonly int $blankLines,
        /** @var int */
        public readonly int $totalBytes,
        /** @var int */
        public readonly int $nodeCount,
        /** @var int */
        public readonly int $errorCount,
        /** @var int */
        public readonly int $maxDepth
    ) { }
}

/**
 * A structural item (function, class, struct, etc.) in source code.
 */
final class StructureItem
{
    public function __construct(
        /** @var StructureKind */
        public readonly StructureKind $kind,
        /** @var Span */
        public readonly Span $span,
        /** @var array<StructureItem> */
        public readonly array $children,
        /** @var array<string> */
        public readonly array $decorators,
        /** @var ?string */
        public readonly ?string $name = null,
        /** @var ?string */
        public readonly ?string $visibility = null,
        /** @var ?string */
        public readonly ?string $docComment = null,
        /** @var ?string */
        public readonly ?string $signature = null,
        /** @var ?Span */
        public readonly ?Span $bodySpan = null
    ) { }
}

/**
 * A comment extracted from source code.
 */
final class CommentInfo
{
    public function __construct(
        /** @var string */
        public readonly string $text,
        /** @var CommentKind */
        public readonly CommentKind $kind,
        /** @var Span */
        public readonly Span $span,
        /** @var ?string */
        public readonly ?string $associatedNode = null
    ) { }
}

/**
 * A docstring extracted from source code.
 */
final class DocstringInfo
{
    public function __construct(
        /** @var string */
        public readonly string $text,
        /** @var DocstringFormat */
        public readonly DocstringFormat $format,
        /** @var Span */
        public readonly Span $span,
        /** @var array<DocSection> */
        public readonly array $parsedSections,
        /** @var ?string */
        public readonly ?string $associatedItem = null
    ) { }
}

/**
 * A section within a docstring (e.g., Args, Returns, Raises).
 */
final class DocSection
{
    public function __construct(
        /** @var string */
        public readonly string $kind,
        /** @var string */
        public readonly string $description,
        /** @var ?string */
        public readonly ?string $name = null
    ) { }
}

/**
 * An import statement extracted from source code.
 */
final class ImportInfo
{
    public function __construct(
        /** @var string */
        public readonly string $source,
        /** @var array<string> */
        public readonly array $items,
        /** @var bool */
        public readonly bool $isWildcard,
        /** @var Span */
        public readonly Span $span,
        /** @var ?string */
        public readonly ?string $alias = null
    ) { }
}

/**
 * An export statement extracted from source code.
 */
final class ExportInfo
{
    public function __construct(
        /** @var string */
        public readonly string $name,
        /** @var ExportKind */
        public readonly ExportKind $kind,
        /** @var Span */
        public readonly Span $span
    ) { }
}

/**
 * A symbol (variable, function, type, etc.) extracted from source code.
 */
final class SymbolInfo
{
    public function __construct(
        /** @var string */
        public readonly string $name,
        /** @var SymbolKind */
        public readonly SymbolKind $kind,
        /** @var Span */
        public readonly Span $span,
        /** @var ?string */
        public readonly ?string $typeAnnotation = null,
        /** @var ?string */
        public readonly ?string $doc = null
    ) { }
}

/**
 * A diagnostic (syntax error, missing node, etc.) from parsing.
 */
final class Diagnostic
{
    public function __construct(
        /** @var string */
        public readonly string $message,
        /** @var DiagnosticSeverity */
        public readonly DiagnosticSeverity $severity,
        /** @var Span */
        public readonly Span $span
    ) { }
}

/**
 * A chunk of source code with rich metadata.
 */
final class CodeChunk
{
    public function __construct(
        /** @var string */
        public readonly string $content,
        /** @var int */
        public readonly int $startByte,
        /** @var int */
        public readonly int $endByte,
        /** @var int */
        public readonly int $startLine,
        /** @var int */
        public readonly int $endLine,
        /** @var ChunkContext */
        public readonly ChunkContext $metadata
    ) { }
}

/**
 * Metadata for a single chunk of source code.
 */
final class ChunkContext
{
    public function __construct(
        /** @var string */
        public readonly string $language,
        /** @var int */
        public readonly int $chunkIndex,
        /** @var int */
        public readonly int $totalChunks,
        /** @var array<string> */
        public readonly array $nodeTypes,
        /** @var array<string> */
        public readonly array $contextPath,
        /** @var array<string> */
        public readonly array $symbolsDefined,
        /** @var array<CommentInfo> */
        public readonly array $comments,
        /** @var array<DocstringInfo> */
        public readonly array $docstrings,
        /** @var bool */
        public readonly bool $hasErrorNodes
    ) { }
}

/**
 * Configuration for the tree-sitter language pack.
 *
 * Controls cache directory and which languages to pre-download.
 * Can be loaded from a TOML file, constructed programmatically,
 * or passed as a dict/object from language bindings.
 *
 * # Example
 */
final class PackConfig
{
    public function __construct(
        /**
         * Override default cache directory.
         *
         * Default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`
         *
         * @var ?string
         */
        public readonly ?string $cacheDir = null,
        /**
         * Languages to pre-download on init.
         *
         * Each entry is a language name (e.g. `"python"`, `"rust"`).
         *
         * @var ?array<string>
         */
        public readonly ?array $languages = null,
        /** @var ?array<string> Language groups to pre-download (e.g. `"web"`, `"systems"`, `"scripting"`). */
        public readonly ?array $groups = null
    ) { }
}

/**
 * A source position — row + column, zero-indexed.
 */
final class Point
{
    public function __construct(
        /** @var int Zero-indexed row number. */
        public readonly int $row,
        /** @var int Zero-indexed column number, in UTF-16 code units. */
        public readonly int $column
    ) { }
}

/**
 * A byte range — start (inclusive) to end (exclusive).
 */
final class ByteRange
{
    public function __construct(
        /** @var int Inclusive start byte offset. */
        public readonly int $start,
        /** @var int Exclusive end byte offset. */
        public readonly int $end
    ) { }
}

/**
 * Configuration for the `process()` function.
 *
 * Controls which analysis features are enabled and whether chunking is performed.
 *
 * # Examples
 */
final class ProcessConfig
{
    public function __construct(
        /** @var string Language name (required). */
        public readonly string $language,
        /** @var bool Extract structural items (functions, classes, etc.). Default: true. */
        public readonly bool $structure,
        /** @var bool Extract import statements. Default: true. */
        public readonly bool $imports,
        /** @var bool Extract export statements. Default: true. */
        public readonly bool $exports,
        /** @var bool Extract comments. Default: false. */
        public readonly bool $comments,
        /** @var bool Extract docstrings. Default: false. */
        public readonly bool $docstrings,
        /** @var bool Extract symbol definitions. Default: false. */
        public readonly bool $symbols,
        /** @var bool Include parse diagnostics. Default: false. */
        public readonly bool $diagnostics,
        /** @var ?int Maximum chunk size in bytes. `None` disables chunking. */
        public readonly ?int $chunkMaxSize = null
    ) { }
    public static function default(): ProcessConfig
    { throw new \RuntimeException('Not implemented — provided by the native extension.'); }
    public function withChunking(int $max_size): ProcessConfig
    { throw new \RuntimeException('Not implemented — provided by the native extension.'); }
    public function all(): ProcessConfig
    { throw new \RuntimeException('Not implemented — provided by the native extension.'); }
    public function minimal(): ProcessConfig
    { throw new \RuntimeException('Not implemented — provided by the native extension.'); }
}

enum StructureKind: string
{
    case Function = 'Function';
    case Method = 'Method';
    case Class_ = 'Class';
    case Struct = 'Struct';
    case Interface = 'Interface';
    case Enum = 'Enum';
    case Module = 'Module';
    case Trait = 'Trait';
    case Impl = 'Impl';
    case Namespace = 'Namespace';
    case Other = 'Other';
}

enum CommentKind: string
{
    case Line = 'Line';
    case Block = 'Block';
    case Doc = 'Doc';
}

enum DocstringFormat: string
{
    case PythonTripleQuote = 'PythonTripleQuote';
    case JSDoc = 'JSDoc';
    case Rustdoc = 'Rustdoc';
    case GoDoc = 'GoDoc';
    case JavaDoc = 'JavaDoc';
    case Other = 'Other';
}

enum ExportKind: string
{
    case Named = 'Named';
    case Default = 'Default';
    case ReExport = 'ReExport';
}

enum SymbolKind: string
{
    case Variable = 'Variable';
    case Constant = 'Constant';
    case Function = 'Function';
    case Class_ = 'Class';
    case Type = 'Type';
    case Interface = 'Interface';
    case Enum = 'Enum';
    case Module = 'Module';
    case Other = 'Other';
}

enum DiagnosticSeverity: string
{
    case Error = 'Error';
    case Warning = 'Warning';
    case Info = 'Info';
}

class TreeSitterLanguagePackApi
{
    public static function detectLanguageFromExtension(string $ext): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function detectLanguageFromPath(string $path): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function detectLanguageFromContent(string $content): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function getHighlightsQuery(string $language): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function getInjectionsQuery(string $language): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function getLocalsQuery(string $language): ?string { throw new \RuntimeException('Not implemented.'); }
    public static function getLanguage(string $name): \Tree\Sitter\Language\Pack\Language { throw new \RuntimeException('Not implemented.'); }
    public static function getParser(string $name): \Tree\Sitter\Language\Pack\Parser { throw new \RuntimeException('Not implemented.'); }
    public static function detectLanguage(string $path): ?string { throw new \RuntimeException('Not implemented.'); }
    /**
     * @return array<string>
     */
    public static function availableLanguages(): array { throw new \RuntimeException('Not implemented.'); }
    public static function hasLanguage(string $name): bool { throw new \RuntimeException('Not implemented.'); }
    public static function languageCount(): int { throw new \RuntimeException('Not implemented.'); }
    public static function process(string $source, \Tree\Sitter\Language\Pack\ProcessConfig $config): \Tree\Sitter\Language\Pack\ProcessResult { throw new \RuntimeException('Not implemented.'); }
    public static function init(\Tree\Sitter\Language\Pack\PackConfig $config): void { }
    public static function configure(\Tree\Sitter\Language\Pack\PackConfig $config): void { }
    /**
     * @param array<string> $names
     * @return int
     */
    public static function download(array $names): int { throw new \RuntimeException('Not implemented.'); }
    public static function downloadAll(): int { throw new \RuntimeException('Not implemented.'); }
    public static function downloadGroup(string $name): int { throw new \RuntimeException('Not implemented.'); }
    /**
     * @return array<string>
     */
    public static function manifestLanguages(): array { throw new \RuntimeException('Not implemented.'); }
    /**
     * @return array<string>
     */
    public static function downloadedLanguages(): array { throw new \RuntimeException('Not implemented.'); }
    public static function cleanCache(): void { }
    public static function cacheDir(): string { throw new \RuntimeException('Not implemented.'); }
}

} // end namespace
