// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7c6bbf972501acdaf81d61e908d599fc0fff20fb888032cf8714a7f70418311f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using TreeSitterLanguagePack;
using static TreeSitterLanguagePack.TreeSitterLanguagePackLib;

namespace TreeSitterLanguagePack
{
    /// <summary>E2e tests for category: parsing.</summary>
    public class ParsingTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ParsingGoFunction()
        {
            // Parse a Go function declaration and assert node type
            var result = TreeSitterLanguagePackLib.Process("package main\nfunc main() {}", new ProcessConfig { Language = "go" });

        }

        [Fact]
        public void Test_ParsingHtmlElement()
        {
            // Parse an HTML element and assert node type
            var result = TreeSitterLanguagePackLib.Process("<div>hello</div>", new ProcessConfig { Language = "html" });

        }

        [Fact]
        public void Test_ParsingJavascriptClass()
        {
            // Parse a JavaScript class declaration.
            var result = TreeSitterLanguagePackLib.Process("class Foo { bar() {} }", new ProcessConfig { Language = "javascript" });

        }

        [Fact]
        public void Test_ParsingJavascriptVariable()
        {
            // Parse a JavaScript variable declaration and assert node type
            var result = TreeSitterLanguagePackLib.Process("const x = 1;", new ProcessConfig { Language = "javascript" });

        }

        [Fact]
        public void Test_ParsingPythonFunction()
        {
            // Parse a Python function definition and assert node type
            var result = TreeSitterLanguagePackLib.Process("def hello(): pass", new ProcessConfig { Language = "python" });

        }

        [Fact]
        public void Test_ParsingRustFunction()
        {
            // Parse a Rust function definition and assert node type
            var result = TreeSitterLanguagePackLib.Process("fn main() {}", new ProcessConfig { Language = "rust" });

        }

        [Fact]
        public void Test_ParsingRustStruct()
        {
            // Parse a Rust struct definition.
            var result = TreeSitterLanguagePackLib.Process("struct Point { x: f64, y: f64 }", new ProcessConfig { Language = "rust" });

        }

        [Fact]
        public void Test_ParsingTypescriptFunction()
        {
            // Parse a TypeScript function with type annotations and template literal return
            var result = TreeSitterLanguagePackLib.Process("function greet(name: string): string { return `hi ${name}`; }", new ProcessConfig { Language = "typescript" });

        }


    }
}
