# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6b009b67f6b2b81396e42b3a3a93d5a0ad50e680621fbda45fed6329de157df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'tree_sitter_language_pack/version'
require_relative 'tree_sitter_language_pack/native'

module TreeSitterLanguagePack
  # Re-export all types and functions from native extension
end
