// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc46a63a4ec02e916a212eedf7a4b7d5ccb0deb437ee6b5de2474985e9f582bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.tslp.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.tslp.android.TreeSitterLanguagePack

/** E2e tests for category: query. */
class QueryTest {
    @Test
    fun testHighlightsNonexistentLanguage() = runBlocking {
        // Get highlights query for nonexistent language returns null/empty
        val result = TreeSitterLanguagePack.getHighlightsQuery("zzz_nonexistent_lang")
        assertTrue(result == null, "expected empty value")
    }

    @Test
    fun testHighlightsQueryRust() = runBlocking {
        // get_highlights_query returns non-empty string for rust
        val result = TreeSitterLanguagePack.getHighlightsQuery("rust")
        assertTrue(result != null, "expected non-empty value")
    }

    @Test
    fun testHighlightsQueryUnknownLanguage() = runBlocking {
        // get_highlights_query returns None for unknown language
        val result = TreeSitterLanguagePack.getHighlightsQuery("nonexistent_language_xyz")
        assertTrue(result == null, "expected empty value")
    }

    @Test
    fun testInjectionsQueryRust() = runBlocking {
        // get_injections_query returns non-empty for rust
        val result = TreeSitterLanguagePack.getInjectionsQuery("rust")
        assertTrue(result != null, "expected non-empty value")
    }

    @Test
    fun testInjectionsQueryUnknownLanguage() = runBlocking {
        // get_injections_query returns empty for unknown language
        val result = TreeSitterLanguagePack.getInjectionsQuery("nonexistent_xyz")
        assertTrue(result == null, "expected empty value")
    }

    @Test
    fun testLocalsQueryCue() = runBlocking {
        // get_locals_query returns non-empty for cue
        val result = TreeSitterLanguagePack.getLocalsQuery("cue")
        assertTrue(result != null, "expected non-empty value")
    }

    @Test
    fun testLocalsQueryUnknownLanguage() = runBlocking {
        // get_locals_query returns empty for unknown language
        val result = TreeSitterLanguagePack.getLocalsQuery("nonexistent_xyz")
        assertTrue(result == null, "expected empty value")
    }

}
