// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e0c4b171c5486218f0c86deadd1d901485d0179b6522e550ff400f575aab475
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
