// Generated by alef. Do not edit by hand.

package dev.kreuzberg.tslp.android

/**
 * Metadata for a single chunk of source code.
 */
data class ChunkContext(
    val language: String,
    val chunkIndex: Long,
    val totalChunks: Long,
    val nodeTypes: List<String>,
    val contextPath: List<String>,
    val symbolsDefined: List<String>,
    val comments: List<CommentInfo>,
    val docstrings: List<DocstringInfo>,
    val hasErrorNodes: Boolean
)
