// Generated by alef. Do not edit by hand.
// alef:hash:966b101e2b4cacb4cb93c43f34e30e8bab6e2478b171704ec0a66561b9335a89

export 'tree_sitter_language_pack_bridge_generated/lib.dart';
export 'traits.dart';
import 'tree_sitter_language_pack_bridge_generated/lib.dart' as rust_bridge;
// ignore: duplicate_import
import 'tree_sitter_language_pack_bridge_generated/lib.dart';

class TreeSitterLanguagePackBridge {
  /// Detect language name from a file extension (without leading dot).
  ///
  /// Returns `None` for unrecognized extensions. The match is case-insensitive.
  ///
  /// ```
  /// use tree_sitter_language_pack::detect_language_from_extension;
  /// assert_eq!(detect_language_from_extension("py"), Some("python"));
  /// assert_eq!(detect_language_from_extension("RS"), Some("rust"));
  /// assert_eq!(detect_language_from_extension("xyz"), None);
  /// ```
  static Future<String?> detectLanguageFromExtension(String ext) async {
    return await rust_bridge.detectLanguageFromExtension(ext: ext);
  }

  /// Detect language name from a file path.
  ///
  /// Extracts the file extension and looks it up. Returns `None` if the
  /// path has no extension or the extension is not recognized.
  ///
  /// ```
  /// use tree_sitter_language_pack::detect_language_from_path;
  /// assert_eq!(detect_language_from_path("src/main.rs"), Some("rust"));
  /// assert_eq!(detect_language_from_path("README.md"), Some("markdown"));
  /// assert_eq!(detect_language_from_path("Makefile"), None);
  /// ```
  static Future<String?> detectLanguageFromPath(String path) async {
    return await rust_bridge.detectLanguageFromPath(path: path);
  }

  /// Detect language name from file content using the shebang line (`#!`).
  ///
  /// Inspects only the first line of `content`. If it begins with `#!`, the
  /// interpreter name is extracted and mapped to a language name.
  ///
  /// Handles common patterns:
  /// - `#!/usr/bin/env python3` → `"python"`
  /// - `#!/bin/bash` → `"bash"`
  /// - `#!/usr/bin/env node` → `"javascript"`
  ///
  /// The `-S` flag accepted by some `env` implementations is skipped automatically.
  /// Version suffixes (e.g. `python3.11`, `ruby3.2`) are stripped before matching.
  ///
  /// Returns `None` when content does not start with `#!`, the shebang is
  /// malformed, or the interpreter is not recognised.
  ///
  /// ```
  /// use tree_sitter_language_pack::detect_language_from_content;
  /// assert_eq!(detect_language_from_content("#!/usr/bin/env python3\npass"), Some("python"));
  /// assert_eq!(detect_language_from_content("#!/bin/bash\necho hi"), Some("bash"));
  /// assert_eq!(detect_language_from_content("no shebang here"), None);
  /// ```
  static Future<String?> detectLanguageFromContent(String content) async {
    return await rust_bridge.detectLanguageFromContent(content: content);
  }

  /// Get the highlights query for a language, if bundled.
  ///
  /// Returns the contents of `highlights.scm` as a static string, or `None`
  /// if no highlights query is bundled for this language.
  ///
  /// # Example
  ///
  /// ```
  /// use tree_sitter_language_pack::get_highlights_query;
  ///
  /// // Returns Some(...) for languages with bundled queries
  /// let query = get_highlights_query("python");
  /// // Returns None for languages without bundled highlights queries
  /// let missing = get_highlights_query("nonexistent_lang");
  /// assert!(missing.is_none());
  /// ```
  static Future<String?> getHighlightsQuery(String language) async {
    return await rust_bridge.getHighlightsQuery(language: language);
  }

  /// Get the injections query for a language, if bundled.
  ///
  /// Returns the contents of `injections.scm` as a static string, or `None`
  /// if no injections query is bundled for this language.
  ///
  /// # Example
  ///
  /// ```
  /// use tree_sitter_language_pack::get_injections_query;
  ///
  /// let query = get_injections_query("markdown");
  /// // Returns None for languages without bundled injections queries
  /// let missing = get_injections_query("nonexistent_lang");
  /// assert!(missing.is_none());
  /// ```
  static Future<String?> getInjectionsQuery(String language) async {
    return await rust_bridge.getInjectionsQuery(language: language);
  }

  /// Get the locals query for a language, if bundled.
  ///
  /// Returns the contents of `locals.scm` as a static string, or `None`
  /// if no locals query is bundled for this language.
  ///
  /// # Example
  ///
  /// ```
  /// use tree_sitter_language_pack::get_locals_query;
  ///
  /// let query = get_locals_query("python");
  /// // Returns None for languages without bundled locals queries
  /// let missing = get_locals_query("nonexistent_lang");
  /// assert!(missing.is_none());
  /// ```
  static Future<String?> getLocalsQuery(String language) async {
    return await rust_bridge.getLocalsQuery(language: language);
  }

  /// Get the tags query for a language, if bundled.
  ///
  /// Returns the contents of `tags.scm` as a static string, or `None`
  /// if no tags query is bundled for this language.
  ///
  /// # Example
  ///
  /// ```
  /// use tree_sitter_language_pack::get_tags_query;
  ///
  /// let query = get_tags_query("rust");
  /// // Returns None for languages without bundled tags queries
  /// let missing = get_tags_query("nonexistent_lang");
  /// assert!(missing.is_none());
  /// ```
  static Future<String?> getTagsQuery(String language) async {
    return await rust_bridge.getTagsQuery(language: language);
  }

  /// Get a tree-sitter [`Language`] by name using the global registry.
  ///
  /// Resolves language aliases (e.g., `"shell"` maps to `"bash"`).
  /// When the `download` feature is enabled (default), automatically downloads
  /// the parser from GitHub releases if not found locally.
  ///
  /// # Errors
  ///
  /// Returns [`Error::LanguageNotFound`] if the language is not recognized,
  /// or [`Error::Download`] if auto-download fails.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::{get_language, Parser};
  ///
  /// let _lang = get_language("python")?;
  /// let mut parser = Parser::new();
  /// parser.set_language("python")?;
  /// let tree = parser.parse("x = 1").expect("parse failed");
  /// assert_eq!(tree.root_node().kind(), "module");
  /// # Ok::<(), tree_sitter_language_pack::Error>(())
  /// ```
  /// throws Error on failure
  static Future<Language> getLanguage(String name) async {
    return await rust_bridge.getLanguage(name: name);
  }

  /// Get a [`Parser`] pre-configured for the given language.
  ///
  /// This is a convenience function that calls [`get_language`] and configures
  /// a new parser in one step.
  ///
  /// # Errors
  ///
  /// Returns [`Error::LanguageNotFound`] if the language is not recognized, or
  /// [`Error::ParserSetup`] if the language cannot be applied to the parser.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::get_parser;
  ///
  /// let mut parser = get_parser("rust")?;
  /// let tree = parser.parse("fn main() {}").expect("parse failed");
  /// assert!(!tree.root_node().has_error());
  /// # Ok::<(), tree_sitter_language_pack::Error>(())
  /// ```
  /// throws Error on failure
  static Future<Parser> getParser(String name) async {
    return await rust_bridge.getParser(name: name);
  }

  /// Detect language name from a file path or extension.
  ///
  /// This compatibility alias matches the pre-Alef Python binding API.
  static Future<String?> detectLanguage(String path) async {
    return await rust_bridge.detectLanguage(path: path);
  }

  /// List all available language names (sorted, deduplicated, includes aliases).
  ///
  /// Returns names of both statically compiled and dynamically loadable languages,
  /// plus any configured aliases.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::available_languages;
  ///
  /// let langs = available_languages();
  /// for name in &langs {
  ///     println!("{}", name);
  /// }
  /// ```
  static Future<List<String>> availableLanguages() async {
    return await rust_bridge.availableLanguages();
  }

  /// Check if a language is available by name or alias.
  ///
  /// Returns `true` if the language can be loaded (statically compiled,
  /// dynamically available, or a known alias for one of these).
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::has_language;
  ///
  /// assert!(has_language("python"));
  /// assert!(has_language("shell")); // alias for "bash"
  /// assert!(!has_language("nonexistent_language"));
  /// ```
  static Future<bool> hasLanguage(String name) async {
    return await rust_bridge.hasLanguage(name: name);
  }

  /// Return the number of available languages.
  ///
  /// Includes statically compiled languages, dynamically loadable languages,
  /// and aliases.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::language_count;
  ///
  /// let count = language_count();
  /// println!("{} languages available", count);
  /// ```
  static Future<int> languageCount() async {
    return await rust_bridge.languageCount();
  }

  /// Process source code and extract file intelligence using the global registry.
  ///
  /// Parses the source with tree-sitter and extracts metrics, structure, imports,
  /// exports, comments, docstrings, symbols, diagnostics, and/or chunks based on
  /// the flags set in [`ProcessConfig`].
  ///
  /// # Errors
  ///
  /// Returns an error if the language is not found or parsing fails.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::{ProcessConfig, process};
  ///
  /// let config = ProcessConfig::new("python").all();
  /// let result = process("def hello(): pass", &config).unwrap();
  /// println!("Language: {}", result.language);
  /// println!("Lines: {}", result.metrics.total_lines);
  /// println!("Structures: {}", result.structure.len());
  /// ```
  /// throws Error on failure
  static Future<ProcessResult> process(
    String source, {
    ProcessConfig? config,
  }) async {
    return await rust_bridge.process(
      source: source,
      config:
          config ??
          ProcessConfig(
            language: '',
            structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunkMaxSize: null,
            dataExtraction: false,
          ),
    );
  }

  /// Initialize the language pack with the given configuration.
  ///
  /// Applies any custom cache directory, then downloads all languages and groups
  /// specified in the config. This is the recommended entry point when you want
  /// to pre-warm the cache before use.
  ///
  /// # Errors
  ///
  /// Returns an error if configuration cannot be applied or if downloads fail.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::{PackConfig, init};
  ///
  /// let config = PackConfig {
  ///     cache_dir: None,
  ///     languages: Some(vec!["python".to_string(), "rust".to_string()]),
  ///     groups: None,
  /// };
  /// init(&config).unwrap();
  /// ```
  /// throws Error on failure
  static Future<void> init({PackConfig? config}) async {
    return await rust_bridge.init(
      config: config ?? PackConfig(cacheDir: '', languages: [], groups: []),
    );
  }

  /// Apply download configuration without downloading anything.
  ///
  /// Use this to set a custom cache directory before the first call to
  /// [`get_language`] or any download function. Changing the cache dir
  /// after languages have been registered has no effect on already-loaded
  /// languages.
  ///
  /// # Errors
  ///
  /// Returns an error if the lock cannot be acquired.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use std::path::PathBuf;
  /// use tree_sitter_language_pack::{PackConfig, configure};
  ///
  /// let config = PackConfig {
  ///     cache_dir: Some(PathBuf::from("/tmp/my-parsers")),
  ///     languages: None,
  ///     groups: None,
  /// };
  /// configure(&config).unwrap();
  /// ```
  /// throws Error on failure
  static Future<void> configure({PackConfig? config}) async {
    return await rust_bridge.configure(
      config: config ?? PackConfig(cacheDir: '', languages: [], groups: []),
    );
  }

  /// Download specific languages to the local cache.
  ///
  /// Returns the number of requested languages available after the call. Already
  /// compiled or cached languages are included in the count.
  ///
  /// # Errors
  ///
  /// Returns an error if any language is not available in the manifest or if
  /// the download fails.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::download;
  ///
  /// let count = download(&["python", "rust", "typescript"]).unwrap();
  /// println!("Ensured {} languages", count);
  /// ```
  /// throws Error on failure
  static Future<int> download(List<String> names) async {
    return await rust_bridge.download(names: names);
  }

  /// Download all available languages from the remote manifest.
  ///
  /// Downloads the platform bundle and extracts every library it contains.
  /// Languages that appear in the manifest but are absent from the bundle
  /// (e.g. grammars that failed to compile at release time) are silently
  /// skipped — they are not treated as an error.
  ///
  /// Returns the total number of languages now available (statically compiled
  /// plus downloaded and cached).
  ///
  /// # Errors
  ///
  /// Returns an error if the manifest cannot be fetched or the bundle download fails.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::download_all;
  ///
  /// let count = download_all().unwrap();
  /// println!("{} languages available", count);
  /// ```
  /// throws Error on failure
  static Future<int> downloadAll() async {
    return await rust_bridge.downloadAll();
  }

  /// Download every language in a named group (e.g. `"web"`, `"data"`).
  ///
  /// Groups are defined in the remote manifest and let you ensure a curated
  /// set of related grammars in one call instead of listing each name to
  /// [`download()`]. Already-cached languages are skipped.
  ///
  /// Returns the total number of languages now available (statically compiled
  /// plus downloaded and cached).
  ///
  /// # Errors
  ///
  /// Returns an error if the manifest cannot be fetched, the group is unknown,
  /// or any constituent language fails to download.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::download_group;
  ///
  /// let count = download_group("web").unwrap();
  /// println!("{} languages available", count);
  /// ```
  /// throws Error on failure
  static Future<int> downloadGroup(String name) async {
    return await rust_bridge.downloadGroup(name: name);
  }

  /// Return all language names available in the remote manifest (306).
  ///
  /// Fetches (and caches) the remote manifest to discover the full list of
  /// downloadable languages. Use [`downloaded_languages`] to list what is
  /// already cached locally.
  ///
  /// # Errors
  ///
  /// Returns an error if the manifest cannot be fetched.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::manifest_languages;
  ///
  /// let langs = manifest_languages().unwrap();
  /// println!("{} languages available for download", langs.len());
  /// ```
  /// throws Error on failure
  static Future<List<String>> manifestLanguages() async {
    return await rust_bridge.manifestLanguages();
  }

  /// Return languages that are already downloaded and cached locally.
  ///
  /// Does not perform any network requests. Returns an empty list if the
  /// cache directory does not exist or cannot be read.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::downloaded_languages;
  ///
  /// let langs = downloaded_languages();
  /// println!("{} languages already cached", langs.len());
  /// ```
  static Future<List<String>> downloadedLanguages() async {
    return await rust_bridge.downloadedLanguages();
  }

  /// Delete all cached parser shared libraries.
  ///
  /// Resets the cache registration so the next call to [`get_language`] or
  /// a download function will re-register the (now empty) cache directory.
  ///
  /// # Errors
  ///
  /// Returns an error if the cache directory cannot be removed.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::clean_cache;
  ///
  /// clean_cache().unwrap();
  /// println!("Cache cleared");
  /// ```
  /// throws Error on failure
  static Future<void> cleanCache() async {
    return await rust_bridge.cleanCache();
  }

  /// Return the effective cache directory path.
  ///
  /// This is either the custom path set via [`configure`] / [`init`] or the
  /// default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`.
  ///
  /// # Errors
  ///
  /// Returns an error if the system cache directory cannot be determined.
  ///
  /// # Example
  ///
  /// ```no_run
  /// use tree_sitter_language_pack::cache_dir;
  ///
  /// let dir = cache_dir().unwrap();
  /// println!("Cache directory: {dir}");
  /// ```
  /// throws Error on failure
  static Future<String> cacheDir() async {
    return await rust_bridge.cacheDir();
  }
}
