// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0712358247aec50c0ffc677cb85e63cca2eccc565bd16e1ba487f879d33faa6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.treesitterlanguagepack.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.treesitterlanguagepack.TreeSitterLanguagePack;
import dev.kreuzberg.treesitterlanguagepack.ProcessConfig;
import java.util.Optional;
import dev.kreuzberg.treesitterlanguagepack.JsonUtil;

/** E2e tests for category: data_extraction. */
public class DataExtractionTest {

    @Test
    void testDataExtractionCaddyDirectives() throws Exception {
        // Data extraction: Caddyfile directives as KeyValue nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"caddy\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("localhost\nroot * /var/www\nfile_server\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionCsvRows() throws Exception {
        // Data extraction: CSV rows are positional Sequence nodes with indexed cells
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"csv\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("a,b,c\n1,2,3\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionCsvSingleRow() throws Exception {
        // Data extraction: CSV single row three cells
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"csv\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("x,y,z\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionCueFields() throws Exception {
        // Data extraction: CUE field definitions as KeyValue nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"cue\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host: \"localhost\"\nport: 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionDtdElementDecl() throws Exception {
        // Data extraction: DTD element declarations as KeyValue nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"dtd\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("<!ELEMENT server (host, port)>\n<!ELEMENT host (#PCDATA)>\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionEditorconfigSection() throws Exception {
        // Data extraction: .editorconfig INI dialect sections and settings
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"editorconfig\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("[*.rs]\nindent_style = space\nindent_size = 4\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionHclAttribute() throws Exception {
        // Data extraction: HCL attribute key-value pair
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"hcl\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("region = \"us-east-1\"\ncount  = 3\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionHclBlock() throws Exception {
        // Data extraction: HCL block becomes a container KeyValue node
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"hcl\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("resource \"aws_instance\" \"web\" {\n  ami = \"ami-123\"\n  instance_type = \"t2.micro\"\n}\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionHjsonFlat() throws Exception {
        // Data extraction: HJSON flat object (JSON superset with comments)
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"hjson\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("{\n  host: \"localhost\"\n  port: 8080\n}\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionHoconFlat() throws Exception {
        // Data extraction: HOCON (HCL dialect) flat key-value pairs
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"hocon\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host = \"localhost\"\nport = 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionIniFlat() throws Exception {
        // Data extraction: INI flat key-value settings
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"ini\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host=localhost\nport=8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionIniSection() throws Exception {
        // Data extraction: INI section becomes a container with children
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"ini\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("[database]\nhost=localhost\nport=5432\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionJson5Flat() throws Exception {
        // Data extraction: JSON5 flat object (JSON superset with trailing commas and comments)
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"json5\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("{\n  host: \"localhost\",\n  port: 8080,\n}\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionJsonArray() throws Exception {
        // Data extraction: JSON top-level array emits Sequence nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"json\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("[1, 2, 3]", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionJsonEmptyObject() throws Exception {
        // Data extraction: JSON empty object produces zero children
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"json\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("{}", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionJsonFlat() throws Exception {
        // Data extraction: JSON flat key-value object
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"json\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("{\"host\": \"localhost\", \"port\": 8080}", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionJsonNested() throws Exception {
        // Data extraction: JSON nested object preserves hierarchy
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"json\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("{\"server\": {\"host\": \"x\", \"port\": 8080}}", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionKdlFlat() throws Exception {
        // Data extraction: KDL flat nodes with scalar values
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"kdl\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host \"localhost\"\nport 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionKdlNested() throws Exception {
        // Data extraction: KDL node with children block
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"kdl\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("server {\n  host \"localhost\"\n  port 8080\n}\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionNginxDirectives() throws Exception {
        // Data extraction: nginx config directives as KeyValue nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"nginx\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("worker_processes 4;\nerror_log /var/log/nginx/error.log;\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionPoMessage() throws Exception {
        // Data extraction: PO gettext message pairs with msgid as key and msgstr as value
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"po\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("msgid \"Hello\"\nmsgstr \"Hallo\"\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionPropertiesDottedKey() throws Exception {
        // Data extraction: .properties dotted key preserved verbatim
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"properties\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("server.host=localhost\nserver.port=8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionPropertiesEmpty() throws Exception {
        // Data extraction: empty .properties file produces zero children
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"properties\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionPropertiesFlat() throws Exception {
        // Data extraction: .properties flat key=value pairs (closes issue #136)
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"properties\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host=localhost\nport=8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionPsvRows() throws Exception {
        // Data extraction: PSV (pipe-separated values) rows as Sequence nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"psv\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("a|b|c\n1|2|3\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionTomlArray() throws Exception {
        // Data extraction: TOML inline array emits Sequence node
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"toml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("ports = [8080, 8081, 8082]\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionTomlFlat() throws Exception {
        // Data extraction: TOML flat key-value pairs
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"toml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host = \"localhost\"\nport = 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionTomlTable() throws Exception {
        // Data extraction: TOML table section becomes a container KeyValue node
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"toml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("[server]\nhost = \"localhost\"\nport = 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionXmlElement() throws Exception {
        // Data extraction: XML element with attributes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"xml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("<server id=\"main\"><host>localhost</host></server>", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type

    }


    @Test
    void testDataExtractionXmlEmptyElement() throws Exception {
        // Data extraction: XML self-closing element produces an Element node
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"xml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("<br/>", config);
        // skipped: field 'data' not available on result type

    }


    @Test
    void testDataExtractionXmlNested() throws Exception {
        // Data extraction: XML nested elements produce child nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"xml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("<config><host>localhost</host><port>8080</port></config>", config);
        // skipped: field 'data' not available on result type

    }


    @Test
    void testDataExtractionYamlFlat() throws Exception {
        // Data extraction: YAML flat mapping
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"yaml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("host: localhost\nport: 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.kind' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionYamlNested() throws Exception {
        // Data extraction: YAML nested block mapping preserves hierarchy
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"yaml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("server:\n  host: localhost\n  port: 8080\n", config);
        // skipped: field 'data' not available on result type        // skipped: field 'data.children' not available on result type

    }


    @Test
    void testDataExtractionYamlSequence() throws Exception {
        // Data extraction: YAML block sequence emits Sequence nodes
        var config = JsonUtil.fromJson("{\"data_extraction\":true,\"language\":\"yaml\"}", ProcessConfig.class);

        var result = TreeSitterLanguagePack.process("ports:\n  - 8080\n  - 8081\n", config);
        // skipped: field 'data' not available on result type

    }

}
