# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cbfce82405886ba16adac06e72a988e1089331253ea6c38cea8c42f34fc3987b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code

"""E2e tests for category: query."""

from tree_sitter_language_pack import get_highlights_query, get_injections_query, get_locals_query, get_tags_query


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


def test_highlights_nonexistent_language() -> None:
    """Get highlights query for nonexistent language returns null/empty."""
    language = "zzz_nonexistent_lang"

    result = get_highlights_query(language)
    assert not result  # noqa: S101


def test_highlights_query_rust() -> None:
    """get_highlights_query returns non-empty string for rust."""
    language = "rust"

    result = get_highlights_query(language)
    assert result  # noqa: S101


def test_highlights_query_unknown_language() -> None:
    """get_highlights_query returns None for unknown language."""
    language = "nonexistent_language_xyz"

    result = get_highlights_query(language)
    assert not result  # noqa: S101


def test_injections_query_rust() -> None:
    """get_injections_query returns non-empty for rust."""
    language = "rust"

    result = get_injections_query(language)
    assert result  # noqa: S101


def test_injections_query_unknown_language() -> None:
    """get_injections_query returns empty for unknown language."""
    language = "nonexistent_xyz"

    result = get_injections_query(language)
    assert not result  # noqa: S101


def test_locals_query_cue() -> None:
    """get_locals_query returns non-empty for cue."""
    language = "cue"

    result = get_locals_query(language)
    assert result  # noqa: S101


def test_locals_query_unknown_language() -> None:
    """get_locals_query returns empty for unknown language."""
    language = "nonexistent_xyz"

    result = get_locals_query(language)
    assert not result  # noqa: S101


def test_tags_query_kotlin() -> None:
    """get_tags_query returns non-empty string for kotlin."""
    language = "kotlin"

    result = get_tags_query(language)
    assert result  # noqa: S101


def test_tags_query_rust() -> None:
    """get_tags_query returns non-empty string for rust."""
    language = "rust"

    result = get_tags_query(language)
    assert result  # noqa: S101


def test_tags_query_unknown_language() -> None:
    """get_tags_query returns empty for unknown language."""
    language = "nonexistent_xyz"

    result = get_tags_query(language)
    assert not result  # noqa: S101
