// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3c151d14314449759d569362f0a875efa94b8855f8e2f8c545175edc5635de17
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
