// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d5cec6c9d6670c8784127b4b9b50fa3b267f840a375e95e33e28533e39887f8a
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
