// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:81e9eed45cd9d0db0808ebe25b0501f51d2d213a1a2e37017044b066c66bf597
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace TreeSitterLanguagePack;

/// <summary>
/// The kind of a comment found in source code.
///
/// Distinguishes between single-line comments, block (multi-line) comments,
/// and documentation comments.
/// </summary>
public enum CommentKind
{
    [JsonPropertyName("line")]
    Line,
    [JsonPropertyName("block")]
    Block,
    [JsonPropertyName("doc")]
    Doc,
}
