// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:90b6da26e8330527e0d9a05a75b8f85f122dce6f2537d14722afc262b51be64d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// Severity level of a diagnostic produced during parsing./// /// Used to classify parse errors, warnings, and informational messages/// found in the syntax tree./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DiagnosticSeverity
{[JsonPropertyName("error")]
    Error,[JsonPropertyName("warning")]
    Warning,[JsonPropertyName("info")]
    Info,}
