// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b18aaf2fbe50375eaa9903e7ab9305c3ed8af009ef2bb9f0680f3ecb7e521b3f
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The format of a docstring extracted from source code.
///
/// Identifies the docstring convention used, which varies by language
/// (e.g., Python triple-quoted strings, JSDoc, Rustdoc `///` comments).
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DocstringFormat
{
    [JsonPropertyName("pythontriplequote")]
    PythonTripleQuote, [JsonPropertyName("jsdoc")]
    JsDoc, [JsonPropertyName("rustdoc")]
    Rustdoc, [JsonPropertyName("godoc")]
    GoDoc, [JsonPropertyName("javadoc")]
    JavaDoc, [JsonPropertyName("other")]
    Other,
}
