// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cea39f27c7b86439ba4384f63c1434154e6c1b7e45a9ac9f165d495df848c358
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
