// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ca15fa127bd51269ca56db50b56e79d59b6fe046ca45aa25f07840f278cf761c
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class IoException : ErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
