// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:68133ddb5b8efbe7e41070f6721a242527361da4659243e43afbbacd5396eb50
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
