// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23f7d79d26f75930a41caf0c601dfc93183ffd8185d18c6a77643762e3d4147b
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace TreeSitterLanguagePack;

internal sealed class LanguageSafeHandle : SafeHandle
{
    internal LanguageSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.LanguageFree(handle);
        return true;
    }
}

public sealed class Language : IDisposable
{
    private readonly LanguageSafeHandle _safeHandle;

    internal Language(IntPtr handle)
    {
        _safeHandle = new LanguageSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
