// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:10aa1e9a92cfbf4b4c6ed24b19b15a5dd32dbc5c78fee9598c936dbe07ceb7e8
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// An internal `RwLock` or `Mutex` was poisoned by a previous panic.
/// </summary>
public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
