// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1be2f727d086b02c4c88b3352346c81ed27be18a641caec61362c676d1a4dee2
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
