// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d13ac4436ebd4920b8e80d7b88b371ea12b3016df30018a7ba973a98282732e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Configuration for the tree-sitter language pack.
///
/// Controls cache directory and which languages to pre-download.
/// Can be loaded from a TOML file, constructed programmatically,
/// or passed as a dict/object from language bindings.
/// </summary>
public sealed record PackConfig
{
    /// <summary>
    /// Override default cache directory.
    ///
    /// Default: `~/.cache/tree-sitter-language-pack/v{version}/libs/`
    /// </summary>
    [JsonPropertyName("cache_dir")]
    public string? CacheDir { get; init; } = null;

    /// <summary>
    /// Languages to pre-download on init.
    ///
    /// Each entry is a language name (e.g. `"python"`, `"rust"`).
    /// </summary>
    [JsonPropertyName("languages")]
    public List<string>? Languages { get; init; } = null;

    /// <summary>
    /// Language groups to pre-download (e.g. `"web"`, `"systems"`, `"scripting"`).
    /// </summary>
    [JsonPropertyName("groups")]
    public List<string>? Groups { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="PackConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static PackConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PackConfig>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse PackConfig from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse PackConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
