// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4e4ec1f94c6c025b3003b948cc4d386fd1c01227fa6ab4d27d61a56d6991a2d4
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class ParseFailedException : ErrorException
{
    public ParseFailedException(string message) : base(message) { }

    public ParseFailedException(string message, Exception innerException) : base(message, innerException) { }
}
