// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:50183d15e220521a4e86736bcf8c9418458ea397105ac53fc85af3de90f387e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Manifest describing available parser downloads for a specific version.
/// </summary>
public sealed class ParserManifest
{
    [JsonPropertyName("version")]
    public string Version { get; set; } = "";

    [JsonPropertyName("platforms")]
    public Dictionary<string, PlatformBundle> Platforms { get; set; } = default!;

    [JsonPropertyName("languages")]
    public Dictionary<string, LanguageInfo> Languages { get; set; } = default!;

    [JsonPropertyName("groups")]
    public Dictionary<string, List<string>> Groups { get; set; } = default!;

}
