// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1fb94d7c54856acd7944954aa92366eb3ec335d096a084591a1f7a76148ff408
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// Complete analysis result from processing a source file.
///
/// Contains metrics, structural analysis, imports/exports, comments,
/// docstrings, symbols, diagnostics, and optionally chunked code segments.
/// Fields are populated based on the `ProcessConfig` flags.
///
/// # Fields
///
/// - `language` - The language used for parsing
/// - `metrics` - Always computed: line counts, byte sizes, error counts
/// - `structure` - Functions, classes, structs (when `config.structure = true`)
/// - `imports` - Import statements (when `config.imports = true`)
/// - `exports` - Export statements (when `config.exports = true`)
/// - `comments` - Comments (when `config.comments = true`)
/// - `docstrings` - Docstrings (when `config.docstrings = true`)
/// - `symbols` - Symbol definitions (when `config.symbols = true`)
/// - `diagnostics` - Parse errors (when `config.diagnostics = true`)
/// - `chunks` - Chunked code segments (when `config.chunk_max_size` is set)
/// </summary>
public sealed class ProcessResult
{
    [JsonPropertyName("language")]
    public string Language { get; set; } = "";

    [JsonPropertyName("metrics")]
    public FileMetrics Metrics { get; set; } = default!;

    [JsonPropertyName("structure")]
    public List<StructureItem> Structure { get; set; } = [];

    [JsonPropertyName("imports")]
    public List<ImportInfo> Imports { get; set; } = [];

    [JsonPropertyName("exports")]
    public List<ExportInfo> Exports { get; set; } = [];

    [JsonPropertyName("comments")]
    public List<CommentInfo> Comments { get; set; } = [];

    [JsonPropertyName("docstrings")]
    public List<DocstringInfo> Docstrings { get; set; } = [];

    [JsonPropertyName("symbols")]
    public List<SymbolInfo> Symbols { get; set; } = [];

    [JsonPropertyName("diagnostics")]
    public List<Diagnostic> Diagnostics { get; set; } = [];

    [JsonPropertyName("chunks")]
    public List<CodeChunk> Chunks { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="ProcessResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static ProcessResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ProcessResult>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse ProcessResult from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse ProcessResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
