// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0712358247aec50c0ffc677cb85e63cca2eccc565bd16e1ba487f879d33faa6d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
