// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:acea65785243ddcf3216cc7e3e5975421161e683fc7cd92dc563f8325a123417
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of structural item found in source code.
///
/// Categorizes top-level and nested declarations such as functions, classes,
/// structs, enums, traits, and more. Use `Other`(StructureKind.Other) for
/// language-specific constructs that do not fit a standard category.
/// </summary>
[JsonConverter(typeof(StructureKindJsonConverter))]
public enum StructureKind
{
    /// <summary>
    /// A free-standing or associated function.
    /// </summary>
    [JsonPropertyName("Function")]
    Function,
    /// <summary>
    /// A method defined inside a class, struct, trait, or impl block.
    /// </summary>
    [JsonPropertyName("Method")]
    Method,
    /// <summary>
    /// A class definition.
    /// </summary>
    [JsonPropertyName("Class")]
    Class,
    /// <summary>
    /// A struct definition.
    /// </summary>
    [JsonPropertyName("Struct")]
    Struct,
    /// <summary>
    /// An interface or protocol definition.
    /// </summary>
    [JsonPropertyName("Interface")]
    Interface,
    /// <summary>
    /// An enum definition.
    /// </summary>
    [JsonPropertyName("Enum")]
    Enum,
    /// <summary>
    /// A module or package declaration.
    /// </summary>
    [JsonPropertyName("Module")]
    Module,
    /// <summary>
    /// A trait definition.
    /// </summary>
    [JsonPropertyName("Trait")]
    Trait,
    /// <summary>
    /// An impl block (Rust) or similar implementation block.
    /// </summary>
    [JsonPropertyName("Impl")]
    Impl,
    /// <summary>
    /// A namespace declaration.
    /// </summary>
    [JsonPropertyName("Namespace")]
    Namespace,
    /// <summary>
    /// A language-specific construct that does not fit any standard category.
    /// </summary>
    [JsonPropertyName("Other")]
    Other,
}


/// <summary>
/// Custom JSON converter for <see cref="StructureKind"/> that respects explicit variant names.
/// </summary>
internal sealed class StructureKindJsonConverter : JsonConverter<StructureKind>
{
    public override StructureKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Function" => StructureKind.Function,
            "Method" => StructureKind.Method,
            "Class" => StructureKind.Class,
            "Struct" => StructureKind.Struct,
            "Interface" => StructureKind.Interface,
            "Enum" => StructureKind.Enum,
            "Module" => StructureKind.Module,
            "Trait" => StructureKind.Trait,
            "Impl" => StructureKind.Impl,
            "Namespace" => StructureKind.Namespace,
            "Other" => StructureKind.Other,
            _ => throw new JsonException($"Unknown StructureKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, StructureKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            StructureKind.Function => "Function",
            StructureKind.Method => "Method",
            StructureKind.Class => "Class",
            StructureKind.Struct => "Struct",
            StructureKind.Interface => "Interface",
            StructureKind.Enum => "Enum",
            StructureKind.Module => "Module",
            StructureKind.Trait => "Trait",
            StructureKind.Impl => "Impl",
            StructureKind.Namespace => "Namespace",
            StructureKind.Other => "Other",
            _ => throw new JsonException($"Unknown StructureKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
