// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4f5d66911897a4ed6b3f5d6561f57a6ac2320a8864265ea61ce567bcae0d72ba
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class TreeSitterLanguagePackException : Exception
{
    public int Code { get; }

    public TreeSitterLanguagePackException(int code, string message) : base(message)
    {
        Code = code;
    }

    public TreeSitterLanguagePackException(string message) : base(message)
    {
        Code = 0;
    }

    public TreeSitterLanguagePackException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
