// Generated by alef. Do not edit by hand.
// alef:hash:6c258a20ebfddd074592606d754e7ca338d9ae406fd413fe81e0164d67af105a

#![allow(unused_variables, unreachable_code, unreachable_patterns, missing_docs)]
#![allow(
    clippy::collapsible_if,
    clippy::collapsible_match,
    clippy::needless_borrows_for_generic_args,
    clippy::field_reassign_with_default,
    clippy::too_many_arguments,
    clippy::clone_on_copy,
    clippy::unnecessary_cast,
    clippy::manual_flatten,
    clippy::match_single_binding,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::inherent_to_string
)]

/// Process-wide tokio runtime shared across every swift-bridge async wrapper.
///
/// alef-emitted; see shims.rs for the rationale (orphaned reqwest connection
/// pools when each call creates and drops its own current-thread runtime).
fn __alef_tokio_runtime() -> &'static ::tokio::runtime::Runtime {
    use std::sync::OnceLock;
    static RT: OnceLock<::tokio::runtime::Runtime> = OnceLock::new();
    RT.get_or_init(|| {
        ::tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .expect("build process-wide alef tokio runtime")
    })
}

#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type Span;
        #[swift_bridge(init)]
        fn new(
            start_byte: usize,
            end_byte: usize,
            start_line: usize,
            start_column: usize,
            end_line: usize,
            end_column: usize,
        ) -> Span;
        #[swift_bridge(swift_name = "startByte")]
        fn start_byte(&self) -> usize;
        #[swift_bridge(swift_name = "endByte")]
        fn end_byte(&self) -> usize;
        #[swift_bridge(swift_name = "startLine")]
        fn start_line(&self) -> usize;
        #[swift_bridge(swift_name = "startColumn")]
        fn start_column(&self) -> usize;
        #[swift_bridge(swift_name = "endLine")]
        fn end_line(&self) -> usize;
        #[swift_bridge(swift_name = "endColumn")]
        fn end_column(&self) -> usize;
    }

    extern "Rust" {
        type ProcessResult;
        #[swift_bridge(init)]
        fn new(
            language: String,
            metrics: FileMetrics,
            structure: Vec<StructureItem>,
            imports: Vec<ImportInfo>,
            exports: Vec<ExportInfo>,
            comments: Vec<CommentInfo>,
            docstrings: Vec<DocstringInfo>,
            symbols: Vec<SymbolInfo>,
            diagnostics: Vec<Diagnostic>,
            chunks: Vec<CodeChunk>,
        ) -> ProcessResult;
        fn language(&self) -> String;
        fn metrics(&self) -> FileMetrics;
        fn structure(&self) -> Vec<StructureItem>;
        fn imports(&self) -> Vec<ImportInfo>;
        fn exports(&self) -> Vec<ExportInfo>;
        fn comments(&self) -> Vec<CommentInfo>;
        fn docstrings(&self) -> Vec<DocstringInfo>;
        fn symbols(&self) -> Vec<SymbolInfo>;
        fn diagnostics(&self) -> Vec<Diagnostic>;
        fn chunks(&self) -> Vec<CodeChunk>;
    }

    extern "Rust" {
        type FileMetrics;
        #[swift_bridge(init)]
        fn new(
            total_lines: usize,
            code_lines: usize,
            comment_lines: usize,
            blank_lines: usize,
            total_bytes: usize,
            node_count: usize,
            error_count: usize,
            max_depth: usize,
        ) -> FileMetrics;
        #[swift_bridge(swift_name = "totalLines")]
        fn total_lines(&self) -> usize;
        #[swift_bridge(swift_name = "codeLines")]
        fn code_lines(&self) -> usize;
        #[swift_bridge(swift_name = "commentLines")]
        fn comment_lines(&self) -> usize;
        #[swift_bridge(swift_name = "blankLines")]
        fn blank_lines(&self) -> usize;
        #[swift_bridge(swift_name = "totalBytes")]
        fn total_bytes(&self) -> usize;
        #[swift_bridge(swift_name = "nodeCount")]
        fn node_count(&self) -> usize;
        #[swift_bridge(swift_name = "errorCount")]
        fn error_count(&self) -> usize;
        #[swift_bridge(swift_name = "maxDepth")]
        fn max_depth(&self) -> usize;
    }

    extern "Rust" {
        type StructureItem;
        #[swift_bridge(init)]
        fn new(
            kind: StructureKind,
            name: Option<String>,
            visibility: Option<String>,
            span: Span,
            children: Vec<StructureItem>,
            decorators: Vec<String>,
            doc_comment: Option<String>,
            signature: Option<String>,
            body_span: Option<Span>,
        ) -> StructureItem;
        fn kind(&self) -> String;
        fn name(&self) -> Option<String>;
        fn visibility(&self) -> Option<String>;
        fn span(&self) -> Span;
        fn children(&self) -> Vec<StructureItem>;
        fn decorators(&self) -> Vec<String>;
        #[swift_bridge(swift_name = "docComment")]
        fn doc_comment(&self) -> Option<String>;
        fn signature(&self) -> Option<String>;
        #[swift_bridge(swift_name = "bodySpan")]
        fn body_span(&self) -> Option<Span>;
    }

    extern "Rust" {
        type CommentInfo;
        #[swift_bridge(init)]
        fn new(text: String, kind: CommentKind, span: Span, associated_node: Option<String>) -> CommentInfo;
        fn text(&self) -> String;
        fn kind(&self) -> String;
        fn span(&self) -> Span;
        #[swift_bridge(swift_name = "associatedNode")]
        fn associated_node(&self) -> Option<String>;
    }

    extern "Rust" {
        type DocstringInfo;
        #[swift_bridge(init)]
        fn new(
            text: String,
            format: DocstringFormat,
            span: Span,
            associated_item: Option<String>,
            parsed_sections: Vec<DocSection>,
        ) -> DocstringInfo;
        fn text(&self) -> String;
        fn format(&self) -> String;
        fn span(&self) -> Span;
        #[swift_bridge(swift_name = "associatedItem")]
        fn associated_item(&self) -> Option<String>;
        #[swift_bridge(swift_name = "parsedSections")]
        fn parsed_sections(&self) -> Vec<DocSection>;
    }

    extern "Rust" {
        type DocSection;
        #[swift_bridge(init)]
        fn new(kind: String, name: Option<String>, description: String) -> DocSection;
        fn kind(&self) -> String;
        fn name(&self) -> Option<String>;
        fn description(&self) -> String;
    }

    extern "Rust" {
        type ImportInfo;
        #[swift_bridge(init)]
        fn new(source: String, items: Vec<String>, alias: Option<String>, is_wildcard: bool, span: Span) -> ImportInfo;
        fn source(&self) -> String;
        fn items(&self) -> Vec<String>;
        fn alias(&self) -> Option<String>;
        #[swift_bridge(swift_name = "isWildcard")]
        fn is_wildcard(&self) -> bool;
        fn span(&self) -> Span;
    }

    extern "Rust" {
        type ExportInfo;
        #[swift_bridge(init)]
        fn new(name: String, kind: ExportKind, span: Span) -> ExportInfo;
        fn name(&self) -> String;
        fn kind(&self) -> String;
        fn span(&self) -> Span;
    }

    extern "Rust" {
        type SymbolInfo;
        #[swift_bridge(init)]
        fn new(
            name: String,
            kind: SymbolKind,
            span: Span,
            type_annotation: Option<String>,
            doc: Option<String>,
        ) -> SymbolInfo;
        fn name(&self) -> String;
        fn kind(&self) -> String;
        fn span(&self) -> Span;
        #[swift_bridge(swift_name = "typeAnnotation")]
        fn type_annotation(&self) -> Option<String>;
        fn doc(&self) -> Option<String>;
    }

    extern "Rust" {
        type Diagnostic;
        #[swift_bridge(init)]
        fn new(message: String, severity: DiagnosticSeverity, span: Span) -> Diagnostic;
        fn message(&self) -> String;
        fn severity(&self) -> String;
        fn span(&self) -> Span;
    }

    extern "Rust" {
        type CodeChunk;
        #[swift_bridge(init)]
        fn new(
            content: String,
            start_byte: usize,
            end_byte: usize,
            start_line: usize,
            end_line: usize,
            metadata: ChunkContext,
        ) -> CodeChunk;
        fn content(&self) -> String;
        #[swift_bridge(swift_name = "startByte")]
        fn start_byte(&self) -> usize;
        #[swift_bridge(swift_name = "endByte")]
        fn end_byte(&self) -> usize;
        #[swift_bridge(swift_name = "startLine")]
        fn start_line(&self) -> usize;
        #[swift_bridge(swift_name = "endLine")]
        fn end_line(&self) -> usize;
        fn metadata(&self) -> ChunkContext;
    }

    extern "Rust" {
        type ChunkContext;
        #[swift_bridge(init)]
        fn new(
            language: String,
            chunk_index: usize,
            total_chunks: usize,
            node_types: Vec<String>,
            context_path: Vec<String>,
            symbols_defined: Vec<String>,
            comments: Vec<CommentInfo>,
            docstrings: Vec<DocstringInfo>,
            has_error_nodes: bool,
        ) -> ChunkContext;
        fn language(&self) -> String;
        #[swift_bridge(swift_name = "chunkIndex")]
        fn chunk_index(&self) -> usize;
        #[swift_bridge(swift_name = "totalChunks")]
        fn total_chunks(&self) -> usize;
        #[swift_bridge(swift_name = "nodeTypes")]
        fn node_types(&self) -> Vec<String>;
        #[swift_bridge(swift_name = "contextPath")]
        fn context_path(&self) -> Vec<String>;
        #[swift_bridge(swift_name = "symbolsDefined")]
        fn symbols_defined(&self) -> Vec<String>;
        fn comments(&self) -> Vec<CommentInfo>;
        fn docstrings(&self) -> Vec<DocstringInfo>;
        #[swift_bridge(swift_name = "hasErrorNodes")]
        fn has_error_nodes(&self) -> bool;
    }

    extern "Rust" {
        type PackConfig;
        #[swift_bridge(init)]
        fn new(cache_dir: Option<String>, languages: Option<Vec<String>>, groups: Option<Vec<String>>) -> PackConfig;
        #[swift_bridge(swift_name = "cacheDir")]
        fn cache_dir(&self) -> Option<String>;
        fn languages(&self) -> Option<Vec<String>>;
        fn groups(&self) -> Option<Vec<String>>;
    }

    extern "Rust" {
        type Point;
        #[swift_bridge(init)]
        fn new(row: usize, column: usize) -> Point;
        fn row(&self) -> usize;
        fn column(&self) -> usize;
    }

    extern "Rust" {
        type ByteRange;
        #[swift_bridge(init)]
        fn new(start: usize, end: usize) -> ByteRange;
        fn start(&self) -> usize;
        fn end(&self) -> usize;
    }

    extern "Rust" {
        type Parser;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "parserSetLanguage")]
        fn parser_set_language(client: &mut Parser, name: String) -> Result<(), String>;
        #[swift_bridge(swift_name = "parserParse")]
        fn parser_parse(client: &mut Parser, source: String) -> Option<Tree>;
        #[swift_bridge(swift_name = "parserParseBytes")]
        fn parser_parse_bytes(client: &mut Parser, source: Vec<u8>) -> Option<Tree>;
        #[swift_bridge(swift_name = "parserReset")]
        fn parser_reset(client: &mut Parser) -> ();
    }

    extern "Rust" {
        type Tree;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "treeRootNode")]
        fn tree_root_node(client: &Tree) -> Node;
        #[swift_bridge(swift_name = "treeWalk")]
        fn tree_walk(client: &Tree) -> TreeCursor;
    }

    extern "Rust" {
        type Node;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "nodeClone")]
        fn node_clone(client: &Node) -> Node;
        #[swift_bridge(swift_name = "nodeKind")]
        fn node_kind(client: &Node) -> String;
        #[swift_bridge(swift_name = "nodeKindId")]
        fn node_kind_id(client: &Node) -> u16;
        #[swift_bridge(swift_name = "nodeStartByte")]
        fn node_start_byte(client: &Node) -> usize;
        #[swift_bridge(swift_name = "nodeEndByte")]
        fn node_end_byte(client: &Node) -> usize;
        #[swift_bridge(swift_name = "nodeByteRange")]
        fn node_byte_range(client: &Node) -> ByteRange;
        #[swift_bridge(swift_name = "nodeStartPosition")]
        fn node_start_position(client: &Node) -> Point;
        #[swift_bridge(swift_name = "nodeEndPosition")]
        fn node_end_position(client: &Node) -> Point;
        #[swift_bridge(swift_name = "nodeIsNamed")]
        fn node_is_named(client: &Node) -> bool;
        #[swift_bridge(swift_name = "nodeIsError")]
        fn node_is_error(client: &Node) -> bool;
        #[swift_bridge(swift_name = "nodeIsMissing")]
        fn node_is_missing(client: &Node) -> bool;
        #[swift_bridge(swift_name = "nodeIsExtra")]
        fn node_is_extra(client: &Node) -> bool;
        #[swift_bridge(swift_name = "nodeHasError")]
        fn node_has_error(client: &Node) -> bool;
        #[swift_bridge(swift_name = "nodeParent")]
        fn node_parent(client: &Node) -> Option<Node>;
        #[swift_bridge(swift_name = "nodeChild")]
        fn node_child(client: &Node, index: u32) -> Option<Node>;
        #[swift_bridge(swift_name = "nodeChildCount")]
        fn node_child_count(client: &Node) -> usize;
        #[swift_bridge(swift_name = "nodeNamedChild")]
        fn node_named_child(client: &Node, index: u32) -> Option<Node>;
        #[swift_bridge(swift_name = "nodeNamedChildCount")]
        fn node_named_child_count(client: &Node) -> usize;
        #[swift_bridge(swift_name = "nodeChildByFieldName")]
        fn node_child_by_field_name(client: &Node, name: String) -> Option<Node>;
        #[swift_bridge(swift_name = "nodeToSexp")]
        fn node_to_sexp(client: &Node) -> String;
        #[swift_bridge(swift_name = "nodeWalk")]
        fn node_walk(client: &Node) -> TreeCursor;
    }

    extern "Rust" {
        type TreeCursor;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "treeCursorNode")]
        fn tree_cursor_node(client: &TreeCursor) -> Node;
        #[swift_bridge(swift_name = "treeCursorGotoFirstChild")]
        fn tree_cursor_goto_first_child(client: &mut TreeCursor) -> bool;
        #[swift_bridge(swift_name = "treeCursorGotoParent")]
        fn tree_cursor_goto_parent(client: &mut TreeCursor) -> bool;
        #[swift_bridge(swift_name = "treeCursorGotoNextSibling")]
        fn tree_cursor_goto_next_sibling(client: &mut TreeCursor) -> bool;
        #[swift_bridge(swift_name = "treeCursorFieldName")]
        fn tree_cursor_field_name(client: &TreeCursor) -> String;
    }

    extern "Rust" {
        type ProcessConfig;
        #[swift_bridge(init)]
        fn new(
            language: String,
            structure: bool,
            imports: bool,
            exports: bool,
            comments: bool,
            docstrings: bool,
            symbols: bool,
            diagnostics: bool,
            chunk_max_size: Option<usize>,
        ) -> ProcessConfig;
        fn language(&self) -> String;
        fn structure(&self) -> bool;
        fn imports(&self) -> bool;
        fn exports(&self) -> bool;
        fn comments(&self) -> bool;
        fn docstrings(&self) -> bool;
        fn symbols(&self) -> bool;
        fn diagnostics(&self) -> bool;
        #[swift_bridge(swift_name = "chunkMaxSize")]
        fn chunk_max_size(&self) -> Option<usize>;
    }

    extern "Rust" {
        type LanguageRegistry;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "languageRegistryGetLanguage")]
        fn language_registry_get_language(client: &LanguageRegistry, name: String) -> Result<Language, String>;
        #[swift_bridge(swift_name = "languageRegistryAvailableLanguages")]
        fn language_registry_available_languages(client: &LanguageRegistry) -> Vec<String>;
        #[swift_bridge(swift_name = "languageRegistryHasParser")]
        fn language_registry_has_parser(client: &LanguageRegistry, name: String) -> bool;
        #[swift_bridge(swift_name = "languageRegistryHasLanguage")]
        fn language_registry_has_language(client: &LanguageRegistry, name: String) -> bool;
        #[swift_bridge(swift_name = "languageRegistryLanguageCount")]
        fn language_registry_language_count(client: &LanguageRegistry) -> usize;
        #[swift_bridge(swift_name = "languageRegistryProcess")]
        fn language_registry_process(
            client: &LanguageRegistry,
            source: String,
            config: ProcessConfig,
        ) -> Result<ProcessResult, String>;
    }

    extern "Rust" {
        type DownloadManager;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "downloadManagerInstalledLanguages")]
        fn download_manager_installed_languages(client: &DownloadManager) -> Vec<String>;
        #[swift_bridge(swift_name = "downloadManagerDownloadAllBestEffort")]
        fn download_manager_download_all_best_effort(client: &DownloadManager) -> Result<usize, String>;
        #[swift_bridge(swift_name = "downloadManagerCleanCache")]
        fn download_manager_clean_cache(client: &DownloadManager) -> Result<(), String>;
    }

    extern "Rust" {
        type Language;
    }

    extern "Rust" {
        type StructureKind;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        type CommentKind;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        type DocstringFormat;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        type ExportKind;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        type SymbolKind;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        type DiagnosticSeverity;
        fn to_string(&self) -> String;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "detectLanguageFromExtension")]
        fn detect_language_from_extension(ext: String) -> String;
        #[swift_bridge(swift_name = "detectLanguageFromPath")]
        fn detect_language_from_path(path: String) -> String;
        #[swift_bridge(swift_name = "detectLanguageFromContent")]
        fn detect_language_from_content(content: String) -> String;
        #[swift_bridge(swift_name = "getHighlightsQuery")]
        fn get_highlights_query(language: String) -> String;
        #[swift_bridge(swift_name = "getInjectionsQuery")]
        fn get_injections_query(language: String) -> String;
        #[swift_bridge(swift_name = "getLocalsQuery")]
        fn get_locals_query(language: String) -> String;
        #[swift_bridge(swift_name = "getLanguage")]
        fn get_language(name: String) -> Result<Language, String>;
        #[swift_bridge(swift_name = "getParser")]
        fn get_parser(name: String) -> Result<Parser, String>;
        #[swift_bridge(swift_name = "detectLanguage")]
        fn detect_language(path: String) -> String;
        #[swift_bridge(swift_name = "availableLanguages")]
        fn available_languages() -> Vec<String>;
        #[swift_bridge(swift_name = "hasLanguage")]
        fn has_language(name: String) -> bool;
        #[swift_bridge(swift_name = "languageCount")]
        fn language_count() -> usize;
        fn process(source: String, config: ProcessConfig) -> Result<ProcessResult, String>;
        fn init_(config: PackConfig) -> Result<(), String>;
        fn configure(config: PackConfig) -> Result<(), String>;
        fn download(names: Vec<String>) -> Result<usize, String>;
        #[swift_bridge(swift_name = "downloadAll")]
        fn download_all() -> Result<usize, String>;
        #[swift_bridge(swift_name = "downloadGroup")]
        fn download_group(name: String) -> Result<usize, String>;
        #[swift_bridge(swift_name = "manifestLanguages")]
        fn manifest_languages() -> Result<Vec<String>, String>;
        #[swift_bridge(swift_name = "downloadedLanguages")]
        fn downloaded_languages() -> Vec<String>;
        #[swift_bridge(swift_name = "cleanCache")]
        fn clean_cache() -> Result<(), String>;
        #[swift_bridge(swift_name = "cacheDir")]
        fn cache_dir() -> Result<String, String>;
    }

    extern "Rust" {
        #[swift_bridge(swift_name = "packConfigFromJson")]
        fn pack_config_from_json(json: String) -> Result<PackConfig, String>;
        #[swift_bridge(swift_name = "processConfigFromJson")]
        fn process_config_from_json(json: String) -> Result<ProcessConfig, String>;
    }
    extern "Rust" {
        #[swift_bridge(swift_name = "spanFromJson")]
        fn span_from_json(json: String) -> Result<Span, String>;
        #[swift_bridge(swift_name = "processResultFromJson")]
        fn process_result_from_json(json: String) -> Result<ProcessResult, String>;
        #[swift_bridge(swift_name = "fileMetricsFromJson")]
        fn file_metrics_from_json(json: String) -> Result<FileMetrics, String>;
        #[swift_bridge(swift_name = "structureItemFromJson")]
        fn structure_item_from_json(json: String) -> Result<StructureItem, String>;
        #[swift_bridge(swift_name = "commentInfoFromJson")]
        fn comment_info_from_json(json: String) -> Result<CommentInfo, String>;
        #[swift_bridge(swift_name = "docstringInfoFromJson")]
        fn docstring_info_from_json(json: String) -> Result<DocstringInfo, String>;
        #[swift_bridge(swift_name = "docSectionFromJson")]
        fn doc_section_from_json(json: String) -> Result<DocSection, String>;
        #[swift_bridge(swift_name = "importInfoFromJson")]
        fn import_info_from_json(json: String) -> Result<ImportInfo, String>;
        #[swift_bridge(swift_name = "exportInfoFromJson")]
        fn export_info_from_json(json: String) -> Result<ExportInfo, String>;
        #[swift_bridge(swift_name = "symbolInfoFromJson")]
        fn symbol_info_from_json(json: String) -> Result<SymbolInfo, String>;
        #[swift_bridge(swift_name = "diagnosticFromJson")]
        fn diagnostic_from_json(json: String) -> Result<Diagnostic, String>;
        #[swift_bridge(swift_name = "codeChunkFromJson")]
        fn code_chunk_from_json(json: String) -> Result<CodeChunk, String>;
        #[swift_bridge(swift_name = "chunkContextFromJson")]
        fn chunk_context_from_json(json: String) -> Result<ChunkContext, String>;
        #[swift_bridge(swift_name = "pointFromJson")]
        fn point_from_json(json: String) -> Result<Point, String>;
        #[swift_bridge(swift_name = "byteRangeFromJson")]
        fn byte_range_from_json(json: String) -> Result<ByteRange, String>;
    }
    extern "Rust" {
        #[swift_bridge(swift_name = "structureKindFromJson")]
        fn structure_kind_from_json(json: String) -> Result<StructureKind, String>;
        #[swift_bridge(swift_name = "commentKindFromJson")]
        fn comment_kind_from_json(json: String) -> Result<CommentKind, String>;
        #[swift_bridge(swift_name = "docstringFormatFromJson")]
        fn docstring_format_from_json(json: String) -> Result<DocstringFormat, String>;
        #[swift_bridge(swift_name = "exportKindFromJson")]
        fn export_kind_from_json(json: String) -> Result<ExportKind, String>;
        #[swift_bridge(swift_name = "symbolKindFromJson")]
        fn symbol_kind_from_json(json: String) -> Result<SymbolKind, String>;
        #[swift_bridge(swift_name = "diagnosticSeverityFromJson")]
        fn diagnostic_severity_from_json(json: String) -> Result<DiagnosticSeverity, String>;
    }
    extern "Rust" {
        // Phantom Vec<T> functions: swift-bridge-build must emit the full Vec support
        // C ABI symbols (__swift_bridge__$Vec_T$new, drop, push, pop, get, get_mut, as_ptr, len)
        // which the auto-generated Swift Vec<T> conformances reference.
        //
        // swift-bridge 0.1.59 only emits these when Vec<T> appears as a return type
        // in an extern block. Without these phantom functions, Swift linker fails when
        // trying to construct or manipulate Vec<T> of opaque types.
        //
        // These declarations are paired with phantom_impl functions below the bridge module.
        fn __alef_phantom_vec_span() -> Vec<Span>;
        fn __alef_phantom_vec_process_result() -> Vec<ProcessResult>;
        fn __alef_phantom_vec_file_metrics() -> Vec<FileMetrics>;
        fn __alef_phantom_vec_structure_item() -> Vec<StructureItem>;
        fn __alef_phantom_vec_comment_info() -> Vec<CommentInfo>;
        fn __alef_phantom_vec_docstring_info() -> Vec<DocstringInfo>;
        fn __alef_phantom_vec_doc_section() -> Vec<DocSection>;
        fn __alef_phantom_vec_import_info() -> Vec<ImportInfo>;
        fn __alef_phantom_vec_export_info() -> Vec<ExportInfo>;
        fn __alef_phantom_vec_symbol_info() -> Vec<SymbolInfo>;
        fn __alef_phantom_vec_diagnostic() -> Vec<Diagnostic>;
        fn __alef_phantom_vec_code_chunk() -> Vec<CodeChunk>;
        fn __alef_phantom_vec_chunk_context() -> Vec<ChunkContext>;
        fn __alef_phantom_vec_pack_config() -> Vec<PackConfig>;
        fn __alef_phantom_vec_point() -> Vec<Point>;
        fn __alef_phantom_vec_byte_range() -> Vec<ByteRange>;
        fn __alef_phantom_vec_parser() -> Vec<Parser>;
        fn __alef_phantom_vec_tree() -> Vec<Tree>;
        fn __alef_phantom_vec_node() -> Vec<Node>;
        fn __alef_phantom_vec_tree_cursor() -> Vec<TreeCursor>;
        fn __alef_phantom_vec_process_config() -> Vec<ProcessConfig>;
        fn __alef_phantom_vec_language_registry() -> Vec<LanguageRegistry>;
        fn __alef_phantom_vec_download_manager() -> Vec<DownloadManager>;
        fn __alef_phantom_vec_language() -> Vec<Language>;
        fn __alef_phantom_vec_structure_kind() -> Vec<StructureKind>;
        fn __alef_phantom_vec_comment_kind() -> Vec<CommentKind>;
        fn __alef_phantom_vec_docstring_format() -> Vec<DocstringFormat>;
        fn __alef_phantom_vec_export_kind() -> Vec<ExportKind>;
        fn __alef_phantom_vec_symbol_kind() -> Vec<SymbolKind>;
        fn __alef_phantom_vec_diagnostic_severity() -> Vec<DiagnosticSeverity>;
    }
}

#[doc(hidden)]
pub fn __alef_phantom_vec_span() -> Vec<Span> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_process_result() -> Vec<ProcessResult> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_file_metrics() -> Vec<FileMetrics> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_structure_item() -> Vec<StructureItem> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_comment_info() -> Vec<CommentInfo> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_docstring_info() -> Vec<DocstringInfo> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_doc_section() -> Vec<DocSection> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_import_info() -> Vec<ImportInfo> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_export_info() -> Vec<ExportInfo> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_symbol_info() -> Vec<SymbolInfo> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_diagnostic() -> Vec<Diagnostic> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_code_chunk() -> Vec<CodeChunk> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_chunk_context() -> Vec<ChunkContext> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_pack_config() -> Vec<PackConfig> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_point() -> Vec<Point> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_byte_range() -> Vec<ByteRange> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_parser() -> Vec<Parser> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_tree() -> Vec<Tree> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_node() -> Vec<Node> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_tree_cursor() -> Vec<TreeCursor> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_process_config() -> Vec<ProcessConfig> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_language_registry() -> Vec<LanguageRegistry> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_download_manager() -> Vec<DownloadManager> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_language() -> Vec<Language> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_structure_kind() -> Vec<StructureKind> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_comment_kind() -> Vec<CommentKind> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_docstring_format() -> Vec<DocstringFormat> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_export_kind() -> Vec<ExportKind> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_symbol_kind() -> Vec<SymbolKind> {
    Vec::new()
}
#[doc(hidden)]
pub fn __alef_phantom_vec_diagnostic_severity() -> Vec<DiagnosticSeverity> {
    Vec::new()
}

pub struct Span(pub tree_sitter_language_pack::Span);
impl Span {
    pub fn new(
        start_byte: usize,
        end_byte: usize,
        start_line: usize,
        start_column: usize,
        end_line: usize,
        end_column: usize,
    ) -> Span {
        Span(tree_sitter_language_pack::Span {
            start_byte,
            end_byte,
            start_line,
            start_column,
            end_line,
            end_column,
        })
    }
    pub fn start_byte(&self) -> usize {
        ::serde_json::to_value(&self.0.start_byte)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end_byte(&self) -> usize {
        ::serde_json::to_value(&self.0.end_byte)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn start_line(&self) -> usize {
        ::serde_json::to_value(&self.0.start_line)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn start_column(&self) -> usize {
        ::serde_json::to_value(&self.0.start_column)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end_line(&self) -> usize {
        ::serde_json::to_value(&self.0.end_line)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end_column(&self) -> usize {
        ::serde_json::to_value(&self.0.end_column)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
}

pub struct ProcessResult(pub tree_sitter_language_pack::ProcessResult);
impl ProcessResult {
    pub fn new(
        language: String,
        metrics: FileMetrics,
        structure: Vec<StructureItem>,
        imports: Vec<ImportInfo>,
        exports: Vec<ExportInfo>,
        comments: Vec<CommentInfo>,
        docstrings: Vec<DocstringInfo>,
        symbols: Vec<SymbolInfo>,
        diagnostics: Vec<Diagnostic>,
        chunks: Vec<CodeChunk>,
    ) -> ProcessResult {
        let mut __target: tree_sitter_language_pack::ProcessResult = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&language)
                .unwrap_or(::serde_json::Value::String(language.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.language = t;
            }
        }
        __target.metrics = metrics.0;
        __target.structure = structure.into_iter().map(|w| w.0).collect();
        __target.imports = imports.into_iter().map(|w| w.0).collect();
        __target.exports = exports.into_iter().map(|w| w.0).collect();
        __target.comments = comments.into_iter().map(|w| w.0).collect();
        __target.docstrings = docstrings.into_iter().map(|w| w.0).collect();
        __target.symbols = symbols.into_iter().map(|w| w.0).collect();
        __target.diagnostics = diagnostics.into_iter().map(|w| w.0).collect();
        __target.chunks = chunks.into_iter().map(|w| w.0).collect();
        ProcessResult(__target)
    }
    pub fn language(&self) -> String {
        self.0.language.clone()
    }
    pub fn metrics(&self) -> FileMetrics {
        FileMetrics(self.0.metrics.clone())
    }
    pub fn structure(&self) -> Vec<StructureItem> {
        self.0
            .structure
            .iter()
            .map(|elem| StructureItem(elem.clone()))
            .collect()
    }
    pub fn imports(&self) -> Vec<ImportInfo> {
        self.0.imports.iter().map(|elem| ImportInfo(elem.clone())).collect()
    }
    pub fn exports(&self) -> Vec<ExportInfo> {
        self.0.exports.iter().map(|elem| ExportInfo(elem.clone())).collect()
    }
    pub fn comments(&self) -> Vec<CommentInfo> {
        self.0.comments.iter().map(|elem| CommentInfo(elem.clone())).collect()
    }
    pub fn docstrings(&self) -> Vec<DocstringInfo> {
        self.0
            .docstrings
            .iter()
            .map(|elem| DocstringInfo(elem.clone()))
            .collect()
    }
    pub fn symbols(&self) -> Vec<SymbolInfo> {
        self.0.symbols.iter().map(|elem| SymbolInfo(elem.clone())).collect()
    }
    pub fn diagnostics(&self) -> Vec<Diagnostic> {
        self.0.diagnostics.iter().map(|elem| Diagnostic(elem.clone())).collect()
    }
    pub fn chunks(&self) -> Vec<CodeChunk> {
        self.0.chunks.iter().map(|elem| CodeChunk(elem.clone())).collect()
    }
}

pub struct FileMetrics(pub tree_sitter_language_pack::FileMetrics);
impl FileMetrics {
    pub fn new(
        total_lines: usize,
        code_lines: usize,
        comment_lines: usize,
        blank_lines: usize,
        total_bytes: usize,
        node_count: usize,
        error_count: usize,
        max_depth: usize,
    ) -> FileMetrics {
        FileMetrics(tree_sitter_language_pack::FileMetrics {
            total_lines,
            code_lines,
            comment_lines,
            blank_lines,
            total_bytes,
            node_count,
            error_count,
            max_depth,
        })
    }
    pub fn total_lines(&self) -> usize {
        ::serde_json::to_value(&self.0.total_lines)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn code_lines(&self) -> usize {
        ::serde_json::to_value(&self.0.code_lines)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn comment_lines(&self) -> usize {
        ::serde_json::to_value(&self.0.comment_lines)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn blank_lines(&self) -> usize {
        ::serde_json::to_value(&self.0.blank_lines)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn total_bytes(&self) -> usize {
        ::serde_json::to_value(&self.0.total_bytes)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn node_count(&self) -> usize {
        ::serde_json::to_value(&self.0.node_count)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn error_count(&self) -> usize {
        ::serde_json::to_value(&self.0.error_count)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn max_depth(&self) -> usize {
        ::serde_json::to_value(&self.0.max_depth)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
}

pub struct StructureItem(pub tree_sitter_language_pack::StructureItem);
impl StructureItem {
    pub fn new(
        kind: StructureKind,
        name: Option<String>,
        visibility: Option<String>,
        span: Span,
        children: Vec<StructureItem>,
        decorators: Vec<String>,
        doc_comment: Option<String>,
        signature: Option<String>,
        body_span: Option<Span>,
    ) -> StructureItem {
        let mut __target: tree_sitter_language_pack::StructureItem = ::std::default::Default::default();
        // alef: kind (StructureKind) is an enum; reverse From not generated — left at default
        if let Some(s) = name {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.name = Some(t);
            }
        }
        if let Some(s) = visibility {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.visibility = Some(t);
            }
        }
        __target.span = span.0;
        __target.children = children.into_iter().map(|w| w.0).collect();
        if let Ok(__v) = ::serde_json::to_value(decorators) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.decorators = t;
            }
        }
        if let Some(s) = doc_comment {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.doc_comment = Some(t);
            }
        }
        if let Some(s) = signature {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.signature = Some(t);
            }
        }
        if let Some(w) = body_span {
            __target.body_span = Some(w.0);
        }
        StructureItem(__target)
    }
    pub fn kind(&self) -> String {
        StructureKind::from(self.0.kind.clone()).to_string()
    }
    pub fn name(&self) -> Option<String> {
        self.0.name.clone()
    }
    pub fn visibility(&self) -> Option<String> {
        self.0.visibility.clone()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
    pub fn children(&self) -> Vec<StructureItem> {
        self.0.children.iter().map(|elem| StructureItem(elem.clone())).collect()
    }
    pub fn decorators(&self) -> Vec<String> {
        ::serde_json::to_value(&self.0.decorators)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn doc_comment(&self) -> Option<String> {
        self.0.doc_comment.clone()
    }
    pub fn signature(&self) -> Option<String> {
        self.0.signature.clone()
    }
    pub fn body_span(&self) -> Option<Span> {
        self.0.body_span.clone().map(Span)
    }
}

pub struct CommentInfo(pub tree_sitter_language_pack::CommentInfo);
impl CommentInfo {
    pub fn new(text: String, kind: CommentKind, span: Span, associated_node: Option<String>) -> CommentInfo {
        let mut __target: tree_sitter_language_pack::CommentInfo = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&text)
                .unwrap_or(::serde_json::Value::String(text.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.text = t;
            }
        }
        // alef: kind (CommentKind) is an enum; reverse From not generated — left at default
        __target.span = span.0;
        if let Some(s) = associated_node {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.associated_node = Some(t);
            }
        }
        CommentInfo(__target)
    }
    pub fn text(&self) -> String {
        self.0.text.clone()
    }
    pub fn kind(&self) -> String {
        CommentKind::from(self.0.kind.clone()).to_string()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
    pub fn associated_node(&self) -> Option<String> {
        self.0.associated_node.clone()
    }
}

pub struct DocstringInfo(pub tree_sitter_language_pack::DocstringInfo);
impl DocstringInfo {
    pub fn new(
        text: String,
        format: DocstringFormat,
        span: Span,
        associated_item: Option<String>,
        parsed_sections: Vec<DocSection>,
    ) -> DocstringInfo {
        let mut __target: tree_sitter_language_pack::DocstringInfo = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&text)
                .unwrap_or(::serde_json::Value::String(text.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.text = t;
            }
        }
        // alef: format (DocstringFormat) is an enum; reverse From not generated — left at default
        __target.span = span.0;
        if let Some(s) = associated_item {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.associated_item = Some(t);
            }
        }
        __target.parsed_sections = parsed_sections.into_iter().map(|w| w.0).collect();
        DocstringInfo(__target)
    }
    pub fn text(&self) -> String {
        self.0.text.clone()
    }
    pub fn format(&self) -> String {
        DocstringFormat::from(self.0.format.clone()).to_string()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
    pub fn associated_item(&self) -> Option<String> {
        self.0.associated_item.clone()
    }
    pub fn parsed_sections(&self) -> Vec<DocSection> {
        self.0
            .parsed_sections
            .iter()
            .map(|elem| DocSection(elem.clone()))
            .collect()
    }
}

pub struct DocSection(pub tree_sitter_language_pack::DocSection);
impl DocSection {
    pub fn new(kind: String, name: Option<String>, description: String) -> DocSection {
        let mut __target: tree_sitter_language_pack::DocSection = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&kind)
                .unwrap_or(::serde_json::Value::String(kind.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.kind = t;
            }
        }
        if let Some(s) = name {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.name = Some(t);
            }
        }
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&description)
                .unwrap_or(::serde_json::Value::String(description.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.description = t;
            }
        }
        DocSection(__target)
    }
    pub fn kind(&self) -> String {
        self.0.kind.clone()
    }
    pub fn name(&self) -> Option<String> {
        self.0.name.clone()
    }
    pub fn description(&self) -> String {
        self.0.description.clone()
    }
}

pub struct ImportInfo(pub tree_sitter_language_pack::ImportInfo);
impl ImportInfo {
    pub fn new(source: String, items: Vec<String>, alias: Option<String>, is_wildcard: bool, span: Span) -> ImportInfo {
        let mut __target: tree_sitter_language_pack::ImportInfo = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&source)
                .unwrap_or(::serde_json::Value::String(source.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.source = t;
            }
        }
        if let Ok(__v) = ::serde_json::to_value(items) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.items = t;
            }
        }
        if let Some(s) = alias {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.alias = Some(t);
            }
        }
        __target.is_wildcard = is_wildcard;
        __target.span = span.0;
        ImportInfo(__target)
    }
    pub fn source(&self) -> String {
        self.0.source.clone()
    }
    pub fn items(&self) -> Vec<String> {
        ::serde_json::to_value(&self.0.items)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn alias(&self) -> Option<String> {
        self.0.alias.clone()
    }
    pub fn is_wildcard(&self) -> bool {
        ::serde_json::to_value(&self.0.is_wildcard)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
}

pub struct ExportInfo(pub tree_sitter_language_pack::ExportInfo);
impl ExportInfo {
    pub fn new(name: String, kind: ExportKind, span: Span) -> ExportInfo {
        let mut __target: tree_sitter_language_pack::ExportInfo = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&name)
                .unwrap_or(::serde_json::Value::String(name.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.name = t;
            }
        }
        // alef: kind (ExportKind) is an enum; reverse From not generated — left at default
        __target.span = span.0;
        ExportInfo(__target)
    }
    pub fn name(&self) -> String {
        self.0.name.clone()
    }
    pub fn kind(&self) -> String {
        ExportKind::from(self.0.kind.clone()).to_string()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
}

pub struct SymbolInfo(pub tree_sitter_language_pack::SymbolInfo);
impl SymbolInfo {
    pub fn new(
        name: String,
        kind: SymbolKind,
        span: Span,
        type_annotation: Option<String>,
        doc: Option<String>,
    ) -> SymbolInfo {
        let mut __target: tree_sitter_language_pack::SymbolInfo = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&name)
                .unwrap_or(::serde_json::Value::String(name.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.name = t;
            }
        }
        // alef: kind (SymbolKind) is an enum; reverse From not generated — left at default
        __target.span = span.0;
        if let Some(s) = type_annotation {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.type_annotation = Some(t);
            }
        }
        if let Some(s) = doc {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.doc = Some(t);
            }
        }
        SymbolInfo(__target)
    }
    pub fn name(&self) -> String {
        self.0.name.clone()
    }
    pub fn kind(&self) -> String {
        SymbolKind::from(self.0.kind.clone()).to_string()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
    pub fn type_annotation(&self) -> Option<String> {
        self.0.type_annotation.clone()
    }
    pub fn doc(&self) -> Option<String> {
        self.0.doc.clone()
    }
}

pub struct Diagnostic(pub tree_sitter_language_pack::Diagnostic);
impl Diagnostic {
    pub fn new(message: String, severity: DiagnosticSeverity, span: Span) -> Diagnostic {
        let mut __target: tree_sitter_language_pack::Diagnostic = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&message)
                .unwrap_or(::serde_json::Value::String(message.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.message = t;
            }
        }
        // alef: severity (DiagnosticSeverity) is an enum; reverse From not generated — left at default
        __target.span = span.0;
        Diagnostic(__target)
    }
    pub fn message(&self) -> String {
        self.0.message.clone()
    }
    pub fn severity(&self) -> String {
        DiagnosticSeverity::from(self.0.severity.clone()).to_string()
    }
    pub fn span(&self) -> Span {
        Span(self.0.span.clone())
    }
}

pub struct CodeChunk(pub tree_sitter_language_pack::CodeChunk);
impl CodeChunk {
    pub fn new(
        content: String,
        start_byte: usize,
        end_byte: usize,
        start_line: usize,
        end_line: usize,
        metadata: ChunkContext,
    ) -> CodeChunk {
        let mut __target: tree_sitter_language_pack::CodeChunk = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&content)
                .unwrap_or(::serde_json::Value::String(content.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.content = t;
            }
        }
        __target.start_byte = start_byte;
        __target.end_byte = end_byte;
        __target.start_line = start_line;
        __target.end_line = end_line;
        __target.metadata = metadata.0;
        CodeChunk(__target)
    }
    pub fn content(&self) -> String {
        self.0.content.clone()
    }
    pub fn start_byte(&self) -> usize {
        ::serde_json::to_value(&self.0.start_byte)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end_byte(&self) -> usize {
        ::serde_json::to_value(&self.0.end_byte)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn start_line(&self) -> usize {
        ::serde_json::to_value(&self.0.start_line)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end_line(&self) -> usize {
        ::serde_json::to_value(&self.0.end_line)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn metadata(&self) -> ChunkContext {
        ChunkContext(self.0.metadata.clone())
    }
}

pub struct ChunkContext(pub tree_sitter_language_pack::ChunkContext);
impl ChunkContext {
    pub fn new(
        language: String,
        chunk_index: usize,
        total_chunks: usize,
        node_types: Vec<String>,
        context_path: Vec<String>,
        symbols_defined: Vec<String>,
        comments: Vec<CommentInfo>,
        docstrings: Vec<DocstringInfo>,
        has_error_nodes: bool,
    ) -> ChunkContext {
        let mut __target: tree_sitter_language_pack::ChunkContext = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&language)
                .unwrap_or(::serde_json::Value::String(language.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.language = t;
            }
        }
        __target.chunk_index = chunk_index;
        __target.total_chunks = total_chunks;
        if let Ok(__v) = ::serde_json::to_value(node_types) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.node_types = t;
            }
        }
        if let Ok(__v) = ::serde_json::to_value(context_path) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.context_path = t;
            }
        }
        if let Ok(__v) = ::serde_json::to_value(symbols_defined) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.symbols_defined = t;
            }
        }
        __target.comments = comments.into_iter().map(|w| w.0).collect();
        __target.docstrings = docstrings.into_iter().map(|w| w.0).collect();
        __target.has_error_nodes = has_error_nodes;
        ChunkContext(__target)
    }
    pub fn language(&self) -> String {
        self.0.language.clone()
    }
    pub fn chunk_index(&self) -> usize {
        ::serde_json::to_value(&self.0.chunk_index)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn total_chunks(&self) -> usize {
        ::serde_json::to_value(&self.0.total_chunks)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn node_types(&self) -> Vec<String> {
        ::serde_json::to_value(&self.0.node_types)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn context_path(&self) -> Vec<String> {
        ::serde_json::to_value(&self.0.context_path)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn symbols_defined(&self) -> Vec<String> {
        ::serde_json::to_value(&self.0.symbols_defined)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn comments(&self) -> Vec<CommentInfo> {
        self.0.comments.iter().map(|elem| CommentInfo(elem.clone())).collect()
    }
    pub fn docstrings(&self) -> Vec<DocstringInfo> {
        self.0
            .docstrings
            .iter()
            .map(|elem| DocstringInfo(elem.clone()))
            .collect()
    }
    pub fn has_error_nodes(&self) -> bool {
        ::serde_json::to_value(&self.0.has_error_nodes)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
}

pub struct PackConfig(pub tree_sitter_language_pack::PackConfig);
impl PackConfig {
    pub fn new(cache_dir: Option<String>, languages: Option<Vec<String>>, groups: Option<Vec<String>>) -> PackConfig {
        let mut __target: tree_sitter_language_pack::PackConfig = ::std::default::Default::default();
        if let Some(s) = cache_dir {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&s).unwrap_or(::serde_json::Value::String(s));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.cache_dir = Some(t);
            }
        }
        if let Ok(__v) = ::serde_json::to_value(languages) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.languages = t;
            }
        }
        if let Ok(__v) = ::serde_json::to_value(groups) {
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.groups = t;
            }
        }
        PackConfig(__target)
    }
    pub fn cache_dir(&self) -> Option<String> {
        self.0.cache_dir.as_ref().and_then(|v| serde_json::to_string(v).ok())
    }
    pub fn languages(&self) -> Option<Vec<String>> {
        self.0.languages.as_ref().and_then(|v| {
            ::serde_json::to_value(v)
                .ok()
                .and_then(|j| ::serde_json::from_value(j).ok())
        })
    }
    pub fn groups(&self) -> Option<Vec<String>> {
        self.0.groups.as_ref().and_then(|v| {
            ::serde_json::to_value(v)
                .ok()
                .and_then(|j| ::serde_json::from_value(j).ok())
        })
    }
}

pub struct Point(pub tree_sitter_language_pack::Point);
impl Point {
    pub fn new(row: usize, column: usize) -> Point {
        Point(tree_sitter_language_pack::Point { row, column })
    }
    pub fn row(&self) -> usize {
        ::serde_json::to_value(&self.0.row)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn column(&self) -> usize {
        ::serde_json::to_value(&self.0.column)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
}

pub struct ByteRange(pub tree_sitter_language_pack::ByteRange);
impl ByteRange {
    pub fn new(start: usize, end: usize) -> ByteRange {
        ByteRange(tree_sitter_language_pack::ByteRange { start, end })
    }
    pub fn start(&self) -> usize {
        ::serde_json::to_value(&self.0.start)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn end(&self) -> usize {
        ::serde_json::to_value(&self.0.end)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
}

pub struct Parser(pub tree_sitter_language_pack::Parser);

pub fn parser_set_language(client: &mut Parser, name: String) -> Result<(), String> {
    client.0.set_language(&name).map_err(|e| e.to_string())
}
pub fn parser_parse(client: &mut Parser, source: String) -> Option<Tree> {
    (client.0.parse(&source)).map(Tree)
}
pub fn parser_parse_bytes(client: &mut Parser, source: Vec<u8>) -> Option<Tree> {
    (client.0.parse_bytes(&source)).map(Tree)
}
pub fn parser_reset(client: &mut Parser) {
    client.0.reset()
}

pub struct Tree(pub tree_sitter_language_pack::Tree);

pub fn tree_root_node(client: &Tree) -> Node {
    Node(client.0.root_node())
}
pub fn tree_walk(client: &Tree) -> TreeCursor {
    TreeCursor(client.0.walk())
}

pub struct Node(pub tree_sitter_language_pack::Node);

pub fn node_clone(client: &Node) -> Node {
    Node(client.0.clone())
}
pub fn node_kind(client: &Node) -> String {
    client.0.kind().to_string()
}
pub fn node_kind_id(client: &Node) -> u16 {
    client.0.kind_id()
}
pub fn node_start_byte(client: &Node) -> usize {
    client.0.start_byte()
}
pub fn node_end_byte(client: &Node) -> usize {
    client.0.end_byte()
}
pub fn node_byte_range(client: &Node) -> ByteRange {
    ByteRange(client.0.byte_range())
}
pub fn node_start_position(client: &Node) -> Point {
    Point(client.0.start_position())
}
pub fn node_end_position(client: &Node) -> Point {
    Point(client.0.end_position())
}
pub fn node_is_named(client: &Node) -> bool {
    client.0.is_named()
}
pub fn node_is_error(client: &Node) -> bool {
    client.0.is_error()
}
pub fn node_is_missing(client: &Node) -> bool {
    client.0.is_missing()
}
pub fn node_is_extra(client: &Node) -> bool {
    client.0.is_extra()
}
pub fn node_has_error(client: &Node) -> bool {
    client.0.has_error()
}
pub fn node_parent(client: &Node) -> Option<Node> {
    (client.0.parent()).map(Node)
}
pub fn node_child(client: &Node, index: u32) -> Option<Node> {
    (client.0.child(index)).map(Node)
}
pub fn node_child_count(client: &Node) -> usize {
    client.0.child_count()
}
pub fn node_named_child(client: &Node, index: u32) -> Option<Node> {
    (client.0.named_child(index)).map(Node)
}
pub fn node_named_child_count(client: &Node) -> usize {
    client.0.named_child_count()
}
pub fn node_child_by_field_name(client: &Node, name: String) -> Option<Node> {
    (client.0.child_by_field_name(&name)).map(Node)
}
pub fn node_to_sexp(client: &Node) -> String {
    client.0.to_sexp().to_string()
}
pub fn node_walk(client: &Node) -> TreeCursor {
    TreeCursor(client.0.walk())
}

pub struct TreeCursor(pub tree_sitter_language_pack::TreeCursor);

pub fn tree_cursor_node(client: &TreeCursor) -> Node {
    Node(client.0.node())
}
pub fn tree_cursor_goto_first_child(client: &mut TreeCursor) -> bool {
    client.0.goto_first_child()
}
pub fn tree_cursor_goto_parent(client: &mut TreeCursor) -> bool {
    client.0.goto_parent()
}
pub fn tree_cursor_goto_next_sibling(client: &mut TreeCursor) -> bool {
    client.0.goto_next_sibling()
}
pub fn tree_cursor_field_name(client: &TreeCursor) -> String {
    serde_json::to_string(&(client.0.field_name())).expect("serializable return")
}

pub struct ProcessConfig(pub tree_sitter_language_pack::ProcessConfig);
impl ProcessConfig {
    pub fn new(
        language: String,
        structure: bool,
        imports: bool,
        exports: bool,
        comments: bool,
        docstrings: bool,
        symbols: bool,
        diagnostics: bool,
        chunk_max_size: Option<usize>,
    ) -> ProcessConfig {
        let mut __target: tree_sitter_language_pack::ProcessConfig = ::std::default::Default::default();
        {
            // Try JSON parse first (handles enum/object values); on parse failure
            // treat the raw input as a JSON string scalar so plain `String` /
            // string-like enum fields don't end up empty for inputs that aren't
            // valid JSON tokens (e.g. `tts-1`).
            let __v = ::serde_json::from_str::<::serde_json::Value>(&language)
                .unwrap_or(::serde_json::Value::String(language.clone()));
            if let Ok(t) = ::serde_json::from_value(__v) {
                __target.language = t;
            }
        }
        __target.structure = structure;
        __target.imports = imports;
        __target.exports = exports;
        __target.comments = comments;
        __target.docstrings = docstrings;
        __target.symbols = symbols;
        __target.diagnostics = diagnostics;
        __target.chunk_max_size = chunk_max_size;
        ProcessConfig(__target)
    }
    pub fn language(&self) -> String {
        self.0.language.to_string()
    }
    pub fn structure(&self) -> bool {
        ::serde_json::to_value(&self.0.structure)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn imports(&self) -> bool {
        ::serde_json::to_value(&self.0.imports)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn exports(&self) -> bool {
        ::serde_json::to_value(&self.0.exports)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn comments(&self) -> bool {
        ::serde_json::to_value(&self.0.comments)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn docstrings(&self) -> bool {
        ::serde_json::to_value(&self.0.docstrings)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn symbols(&self) -> bool {
        ::serde_json::to_value(&self.0.symbols)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn diagnostics(&self) -> bool {
        ::serde_json::to_value(&self.0.diagnostics)
            .ok()
            .and_then(|j| ::serde_json::from_value(j).ok())
            .unwrap_or_default()
    }
    pub fn chunk_max_size(&self) -> Option<usize> {
        self.0.chunk_max_size.as_ref().and_then(|v| {
            ::serde_json::to_value(v)
                .ok()
                .and_then(|j| ::serde_json::from_value(j).ok())
        })
    }
}

pub struct LanguageRegistry(pub tree_sitter_language_pack::LanguageRegistry);

pub fn language_registry_get_language(client: &LanguageRegistry, name: String) -> Result<Language, String> {
    client.0.get_language(&name).map_err(|e| e.to_string()).map(Language)
}
pub fn language_registry_available_languages(client: &LanguageRegistry) -> Vec<String> {
    client.0.available_languages()
}
pub fn language_registry_has_parser(client: &LanguageRegistry, name: String) -> bool {
    client.0.has_parser(&name)
}
pub fn language_registry_has_language(client: &LanguageRegistry, name: String) -> bool {
    client.0.has_language(&name)
}
pub fn language_registry_language_count(client: &LanguageRegistry) -> usize {
    client.0.language_count()
}
pub fn language_registry_process(
    client: &LanguageRegistry,
    source: String,
    config: ProcessConfig,
) -> Result<ProcessResult, String> {
    client
        .0
        .process(&source, &config.0)
        .map_err(|e| e.to_string())
        .map(ProcessResult)
}

pub struct DownloadManager(pub tree_sitter_language_pack::DownloadManager);

pub fn download_manager_installed_languages(client: &DownloadManager) -> Vec<String> {
    client.0.installed_languages()
}
pub fn download_manager_download_all_best_effort(client: &DownloadManager) -> Result<usize, String> {
    client.0.download_all_best_effort().map_err(|e| e.to_string())
}
pub fn download_manager_clean_cache(client: &DownloadManager) -> Result<(), String> {
    client.0.clean_cache().map_err(|e| e.to_string())
}

pub struct Language(pub tree_sitter_language_pack::Language);

pub enum StructureKind {
    Function,
    Method,
    Class,
    Struct,
    Interface,
    Enum,
    Module,
    Trait,
    Impl,
    Namespace,
    Other,
}

impl From<tree_sitter_language_pack::StructureKind> for StructureKind {
    fn from(val: tree_sitter_language_pack::StructureKind) -> Self {
        match val {
            tree_sitter_language_pack::StructureKind::Function => Self::Function,
            tree_sitter_language_pack::StructureKind::Method => Self::Method,
            tree_sitter_language_pack::StructureKind::Class => Self::Class,
            tree_sitter_language_pack::StructureKind::Struct => Self::Struct,
            tree_sitter_language_pack::StructureKind::Interface => Self::Interface,
            tree_sitter_language_pack::StructureKind::Enum => Self::Enum,
            tree_sitter_language_pack::StructureKind::Module => Self::Module,
            tree_sitter_language_pack::StructureKind::Trait => Self::Trait,
            tree_sitter_language_pack::StructureKind::Impl => Self::Impl,
            tree_sitter_language_pack::StructureKind::Namespace => Self::Namespace,
            tree_sitter_language_pack::StructureKind::Other(..) => Self::Other,
        }
    }
}

impl StructureKind {
    pub fn to_string(&self) -> String {
        match self {
            Self::Function => "Function".to_string(),
            Self::Method => "Method".to_string(),
            Self::Class => "Class".to_string(),
            Self::Struct => "Struct".to_string(),
            Self::Interface => "Interface".to_string(),
            Self::Enum => "Enum".to_string(),
            Self::Module => "Module".to_string(),
            Self::Trait => "Trait".to_string(),
            Self::Impl => "Impl".to_string(),
            Self::Namespace => "Namespace".to_string(),
            Self::Other => "Other".to_string(),
        }
    }
}

pub enum CommentKind {
    Line,
    Block,
    Doc,
}

impl From<tree_sitter_language_pack::CommentKind> for CommentKind {
    fn from(val: tree_sitter_language_pack::CommentKind) -> Self {
        match val {
            tree_sitter_language_pack::CommentKind::Line => Self::Line,
            tree_sitter_language_pack::CommentKind::Block => Self::Block,
            tree_sitter_language_pack::CommentKind::Doc => Self::Doc,
        }
    }
}

impl CommentKind {
    pub fn to_string(&self) -> String {
        match self {
            Self::Line => "Line".to_string(),
            Self::Block => "Block".to_string(),
            Self::Doc => "Doc".to_string(),
        }
    }
}

pub enum DocstringFormat {
    PythonTripleQuote,
    JSDoc,
    Rustdoc,
    GoDoc,
    JavaDoc,
    Other,
}

impl From<tree_sitter_language_pack::DocstringFormat> for DocstringFormat {
    fn from(val: tree_sitter_language_pack::DocstringFormat) -> Self {
        match val {
            tree_sitter_language_pack::DocstringFormat::PythonTripleQuote => Self::PythonTripleQuote,
            tree_sitter_language_pack::DocstringFormat::JSDoc => Self::JSDoc,
            tree_sitter_language_pack::DocstringFormat::Rustdoc => Self::Rustdoc,
            tree_sitter_language_pack::DocstringFormat::GoDoc => Self::GoDoc,
            tree_sitter_language_pack::DocstringFormat::JavaDoc => Self::JavaDoc,
            tree_sitter_language_pack::DocstringFormat::Other(..) => Self::Other,
        }
    }
}

impl DocstringFormat {
    pub fn to_string(&self) -> String {
        match self {
            Self::PythonTripleQuote => "PythonTripleQuote".to_string(),
            Self::JSDoc => "JSDoc".to_string(),
            Self::Rustdoc => "Rustdoc".to_string(),
            Self::GoDoc => "GoDoc".to_string(),
            Self::JavaDoc => "JavaDoc".to_string(),
            Self::Other => "Other".to_string(),
        }
    }
}

pub enum ExportKind {
    Named,
    Default,
    ReExport,
}

impl From<tree_sitter_language_pack::ExportKind> for ExportKind {
    fn from(val: tree_sitter_language_pack::ExportKind) -> Self {
        match val {
            tree_sitter_language_pack::ExportKind::Named => Self::Named,
            tree_sitter_language_pack::ExportKind::Default => Self::Default,
            tree_sitter_language_pack::ExportKind::ReExport => Self::ReExport,
        }
    }
}

impl ExportKind {
    pub fn to_string(&self) -> String {
        match self {
            Self::Named => "Named".to_string(),
            Self::Default => "Default".to_string(),
            Self::ReExport => "ReExport".to_string(),
        }
    }
}

pub enum SymbolKind {
    Variable,
    Constant,
    Function,
    Class,
    Type,
    Interface,
    Enum,
    Module,
    Other,
}

impl From<tree_sitter_language_pack::SymbolKind> for SymbolKind {
    fn from(val: tree_sitter_language_pack::SymbolKind) -> Self {
        match val {
            tree_sitter_language_pack::SymbolKind::Variable => Self::Variable,
            tree_sitter_language_pack::SymbolKind::Constant => Self::Constant,
            tree_sitter_language_pack::SymbolKind::Function => Self::Function,
            tree_sitter_language_pack::SymbolKind::Class => Self::Class,
            tree_sitter_language_pack::SymbolKind::Type => Self::Type,
            tree_sitter_language_pack::SymbolKind::Interface => Self::Interface,
            tree_sitter_language_pack::SymbolKind::Enum => Self::Enum,
            tree_sitter_language_pack::SymbolKind::Module => Self::Module,
            tree_sitter_language_pack::SymbolKind::Other(..) => Self::Other,
        }
    }
}

impl SymbolKind {
    pub fn to_string(&self) -> String {
        match self {
            Self::Variable => "Variable".to_string(),
            Self::Constant => "Constant".to_string(),
            Self::Function => "Function".to_string(),
            Self::Class => "Class".to_string(),
            Self::Type => "Type".to_string(),
            Self::Interface => "Interface".to_string(),
            Self::Enum => "Enum".to_string(),
            Self::Module => "Module".to_string(),
            Self::Other => "Other".to_string(),
        }
    }
}

pub enum DiagnosticSeverity {
    Error,
    Warning,
    Info,
}

impl From<tree_sitter_language_pack::DiagnosticSeverity> for DiagnosticSeverity {
    fn from(val: tree_sitter_language_pack::DiagnosticSeverity) -> Self {
        match val {
            tree_sitter_language_pack::DiagnosticSeverity::Error => Self::Error,
            tree_sitter_language_pack::DiagnosticSeverity::Warning => Self::Warning,
            tree_sitter_language_pack::DiagnosticSeverity::Info => Self::Info,
        }
    }
}

impl DiagnosticSeverity {
    pub fn to_string(&self) -> String {
        match self {
            Self::Error => "Error".to_string(),
            Self::Warning => "Warning".to_string(),
            Self::Info => "Info".to_string(),
        }
    }
}

pub fn detect_language_from_extension(ext: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::detect_language_from_extension(&ext)))
        .expect("serializable return")
}

pub fn detect_language_from_path(path: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::detect_language_from_path(&path))).expect("serializable return")
}

pub fn detect_language_from_content(content: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::detect_language_from_content(&content)))
        .expect("serializable return")
}

pub fn get_highlights_query(language: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::get_highlights_query(&language))).expect("serializable return")
}

pub fn get_injections_query(language: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::get_injections_query(&language))).expect("serializable return")
}

pub fn get_locals_query(language: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::get_locals_query(&language))).expect("serializable return")
}

pub fn get_language(name: String) -> Result<Language, String> {
    tree_sitter_language_pack::get_language(&name)
        .map_err(|e| e.to_string())
        .map(Language)
}

pub fn get_parser(name: String) -> Result<Parser, String> {
    tree_sitter_language_pack::get_parser(&name)
        .map_err(|e| e.to_string())
        .map(Parser)
}

pub fn detect_language(path: String) -> String {
    serde_json::to_string(&(tree_sitter_language_pack::detect_language(&path))).expect("serializable return")
}

pub fn available_languages() -> Vec<String> {
    tree_sitter_language_pack::available_languages()
        .into_iter()
        .map(|s| s.to_string())
        .collect::<Vec<_>>()
}

pub fn has_language(name: String) -> bool {
    tree_sitter_language_pack::has_language(&name)
}

pub fn language_count() -> usize {
    tree_sitter_language_pack::language_count()
}

pub fn process(source: String, config: ProcessConfig) -> Result<ProcessResult, String> {
    tree_sitter_language_pack::process(&source, &config.0)
        .map_err(|e| e.to_string())
        .map(ProcessResult)
}

pub fn init_(config: PackConfig) -> Result<(), String> {
    tree_sitter_language_pack::init(&config.0).map_err(|e| e.to_string())
}

pub fn configure(config: PackConfig) -> Result<(), String> {
    tree_sitter_language_pack::configure(&config.0).map_err(|e| e.to_string())
}

pub fn download(names: Vec<String>) -> Result<usize, String> {
    tree_sitter_language_pack::download(&names.iter().map(|s| s.as_str()).collect::<Vec<_>>())
        .map_err(|e| e.to_string())
}

pub fn download_all() -> Result<usize, String> {
    tree_sitter_language_pack::download_all().map_err(|e| e.to_string())
}

pub fn download_group(name: String) -> Result<usize, String> {
    tree_sitter_language_pack::download_group(&name).map_err(|e| e.to_string())
}

pub fn manifest_languages() -> Result<Vec<String>, String> {
    tree_sitter_language_pack::manifest_languages()
        .map_err(|e| e.to_string())
        .map(|v| v.into_iter().map(|s| s.to_string()).collect::<Vec<_>>())
}

pub fn downloaded_languages() -> Vec<String> {
    tree_sitter_language_pack::downloaded_languages()
        .into_iter()
        .map(|s| s.to_string())
        .collect::<Vec<_>>()
}

pub fn clean_cache() -> Result<(), String> {
    tree_sitter_language_pack::clean_cache().map_err(|e| e.to_string())
}

pub fn cache_dir() -> Result<String, String> {
    tree_sitter_language_pack::cache_dir()
        .map_err(|e| e.to_string())
        .map(|s| s.to_string())
}

pub fn pack_config_from_json(json: String) -> Result<PackConfig, String> {
    serde_json::from_str::<tree_sitter_language_pack::PackConfig>(&json)
        .map(PackConfig)
        .map_err(|e| e.to_string())
}
pub fn process_config_from_json(json: String) -> Result<ProcessConfig, String> {
    serde_json::from_str::<tree_sitter_language_pack::ProcessConfig>(&json)
        .map(ProcessConfig)
        .map_err(|e| e.to_string())
}
pub fn span_from_json(json: String) -> Result<Span, String> {
    serde_json::from_str::<tree_sitter_language_pack::Span>(&json)
        .map(Span)
        .map_err(|e| e.to_string())
}
pub fn process_result_from_json(json: String) -> Result<ProcessResult, String> {
    serde_json::from_str::<tree_sitter_language_pack::ProcessResult>(&json)
        .map(ProcessResult)
        .map_err(|e| e.to_string())
}
pub fn file_metrics_from_json(json: String) -> Result<FileMetrics, String> {
    serde_json::from_str::<tree_sitter_language_pack::FileMetrics>(&json)
        .map(FileMetrics)
        .map_err(|e| e.to_string())
}
pub fn structure_item_from_json(json: String) -> Result<StructureItem, String> {
    serde_json::from_str::<tree_sitter_language_pack::StructureItem>(&json)
        .map(StructureItem)
        .map_err(|e| e.to_string())
}
pub fn comment_info_from_json(json: String) -> Result<CommentInfo, String> {
    serde_json::from_str::<tree_sitter_language_pack::CommentInfo>(&json)
        .map(CommentInfo)
        .map_err(|e| e.to_string())
}
pub fn docstring_info_from_json(json: String) -> Result<DocstringInfo, String> {
    serde_json::from_str::<tree_sitter_language_pack::DocstringInfo>(&json)
        .map(DocstringInfo)
        .map_err(|e| e.to_string())
}
pub fn doc_section_from_json(json: String) -> Result<DocSection, String> {
    serde_json::from_str::<tree_sitter_language_pack::DocSection>(&json)
        .map(DocSection)
        .map_err(|e| e.to_string())
}
pub fn import_info_from_json(json: String) -> Result<ImportInfo, String> {
    serde_json::from_str::<tree_sitter_language_pack::ImportInfo>(&json)
        .map(ImportInfo)
        .map_err(|e| e.to_string())
}
pub fn export_info_from_json(json: String) -> Result<ExportInfo, String> {
    serde_json::from_str::<tree_sitter_language_pack::ExportInfo>(&json)
        .map(ExportInfo)
        .map_err(|e| e.to_string())
}
pub fn symbol_info_from_json(json: String) -> Result<SymbolInfo, String> {
    serde_json::from_str::<tree_sitter_language_pack::SymbolInfo>(&json)
        .map(SymbolInfo)
        .map_err(|e| e.to_string())
}
pub fn diagnostic_from_json(json: String) -> Result<Diagnostic, String> {
    serde_json::from_str::<tree_sitter_language_pack::Diagnostic>(&json)
        .map(Diagnostic)
        .map_err(|e| e.to_string())
}
pub fn code_chunk_from_json(json: String) -> Result<CodeChunk, String> {
    serde_json::from_str::<tree_sitter_language_pack::CodeChunk>(&json)
        .map(CodeChunk)
        .map_err(|e| e.to_string())
}
pub fn chunk_context_from_json(json: String) -> Result<ChunkContext, String> {
    serde_json::from_str::<tree_sitter_language_pack::ChunkContext>(&json)
        .map(ChunkContext)
        .map_err(|e| e.to_string())
}
pub fn point_from_json(json: String) -> Result<Point, String> {
    serde_json::from_str::<tree_sitter_language_pack::Point>(&json)
        .map(Point)
        .map_err(|e| e.to_string())
}
pub fn byte_range_from_json(json: String) -> Result<ByteRange, String> {
    serde_json::from_str::<tree_sitter_language_pack::ByteRange>(&json)
        .map(ByteRange)
        .map_err(|e| e.to_string())
}
pub fn structure_kind_from_json(json: String) -> Result<StructureKind, String> {
    serde_json::from_str::<tree_sitter_language_pack::StructureKind>(&json)
        .map(StructureKind::from)
        .map_err(|e| e.to_string())
}
pub fn comment_kind_from_json(json: String) -> Result<CommentKind, String> {
    serde_json::from_str::<tree_sitter_language_pack::CommentKind>(&json)
        .map(CommentKind::from)
        .map_err(|e| e.to_string())
}
pub fn docstring_format_from_json(json: String) -> Result<DocstringFormat, String> {
    serde_json::from_str::<tree_sitter_language_pack::DocstringFormat>(&json)
        .map(DocstringFormat::from)
        .map_err(|e| e.to_string())
}
pub fn export_kind_from_json(json: String) -> Result<ExportKind, String> {
    serde_json::from_str::<tree_sitter_language_pack::ExportKind>(&json)
        .map(ExportKind::from)
        .map_err(|e| e.to_string())
}
pub fn symbol_kind_from_json(json: String) -> Result<SymbolKind, String> {
    serde_json::from_str::<tree_sitter_language_pack::SymbolKind>(&json)
        .map(SymbolKind::from)
        .map_err(|e| e.to_string())
}
pub fn diagnostic_severity_from_json(json: String) -> Result<DiagnosticSeverity, String> {
    serde_json::from_str::<tree_sitter_language_pack::DiagnosticSeverity>(&json)
        .map(DiagnosticSeverity::from)
        .map_err(|e| e.to_string())
}
