# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7cd71c67790bc045f2bb622072ee2aaa2632a2a413fb7d14169821f7df1f7a79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: language-detection
defmodule E2e.LanguageDetectionTest do
  use ExUnit.Case, async: false

  describe "ambiguity_h_extension" do
    @tag :skip
    test "The .h extension is ambiguous (could be C, C++, or Objective-C)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "ambiguity_py_extension" do
    @tag :skip
    test "The .py extension is NOT ambiguous (only maps to python)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "ambiguity_unknown_extension" do
    @tag :skip
    test "Unknown extension returns empty (no ambiguity data)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_content_bash_shebang" do
    @tag :skip
    test "detect_language_from_content recognizes #!/bin/bash shebang" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_content_no_shebang" do
    @tag :skip
    test "detect_language_from_content returns None when no shebang present" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_content_python_shebang" do
    @tag :skip
    test "detect_language_from_content recognizes #!/usr/bin/env python3 shebang" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_cpp" do
    @tag :skip
    test "detect_language_from_extension recognizes .cpp as cpp" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_go" do
    @tag :skip
    test "detect_language_from_extension recognizes .go as go" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_java" do
    @tag :skip
    test "detect_language_from_extension recognizes .java as java" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_javascript" do
    @tag :skip
    test "detect_language_from_extension recognizes .js as javascript" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_php" do
    @tag :skip
    test "detect_language_from_extension recognizes .php as php" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_python" do
    @tag :skip
    test "detect_language_from_extension recognizes .py as python" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_ruby" do
    @tag :skip
    test "detect_language_from_extension recognizes .rb as ruby" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_rust" do
    @tag :skip
    test "detect_language_from_extension recognizes .rs as rust" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_typescript" do
    @tag :skip
    test "detect_language_from_extension recognizes .ts as typescript" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_ext_unknown" do
    @tag :skip
    test "detect_language_from_extension returns None for unknown extension .xyz" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_dotfile" do
    @tag :skip
    test "detect_language_from_path returns None for dotfile .gitignore (no standard extension)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_go_nested" do
    @tag :skip
    test "detect_language_from_path extracts extension from nested path lib/server.go" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_java_root" do
    @tag :skip
    test "detect_language_from_path recognizes Main.java in root directory" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_js_root" do
    @tag :skip
    test "detect_language_from_path recognizes app.js in root directory" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_nested" do
    @tag :skip
    test "detect_language_from_path extracts extension from nested path src/main.py" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_no_extension" do
    @tag :skip
    test "detect_language_from_path returns None for extensionless file Makefile" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "detect_path_rust_src" do
    @tag :skip
    test "detect_language_from_path extracts extension from nested path src/main.rs" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
