# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b9638a8c0da8eb8ec73ba110b54061b41da5eda98e11d40d404ab77af2c542a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: query
defmodule E2e.QueryTest do
  use ExUnit.Case, async: false

  describe "highlights_nonexistent_language" do
    @tag :skip
    test "Get highlights query for nonexistent language returns null/empty" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "highlights_query_python" do
    @tag :skip
    test "get_highlights_query returns non-empty string for python" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "highlights_query_unknown_language" do
    @tag :skip
    test "get_highlights_query returns None for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "injections_query_javascript" do
    @tag :skip
    test "get_injections_query returns non-empty for javascript (has embedded languages)" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "injections_query_unknown_language" do
    @tag :skip
    test "get_injections_query returns empty for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "locals_query_python" do
    @tag :skip
    test "get_locals_query returns non-empty for python" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "locals_query_unknown_language" do
    @tag :skip
    test "get_locals_query returns empty for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
