// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f3825c44988d0221f9d32343905b9bffc37935405aab3943adb70c2d254823c
// To regenerate: alef e2e generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'package:tree_sitter_language_pack/tree_sitter_language_pack.dart';
import 'package:tree_sitter_language_pack/src/tree_sitter_language_pack_bridge_generated/frb_generated.dart'
    show RustLib;

// E2e tests for category: registry

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    await RustLib.init();
    _rustLibInitialized = true;
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
  });

  test('get_language(\'python\') returns a valid Language object', () async {
    final language = await TreeSitterLanguagePackBridge.getLanguage('python');
    expect(language, isNotNull);
  });

  test(
    'get_language(\'nonexistent_xyz\') returns an error for unknown language',
    () async {
      await expectLater(
        TreeSitterLanguagePackBridge.getLanguage('nonexistent_xyz'),
        throwsA(anything),
      );
    },
  );

  test('get_parser(\'python\') returns a valid Parser object', () async {
    final parser = await TreeSitterLanguagePackBridge.getParser('python');
    expect(parser, isNotNull);
  });

  test(
    'get_parser(\'nonexistent_xyz\') returns an error for unknown language',
    () async {
      await expectLater(
        TreeSitterLanguagePackBridge.getParser('nonexistent_xyz'),
        throwsA(anything),
      );
    },
  );

  test(
    'get_language(\'shell\') resolves the alias to \'bash\' and returns ok',
    () async {
      final language = await TreeSitterLanguagePackBridge.getLanguage('shell');
      expect(language, isNotNull);
    },
  );

  test(
    'get_parser(\'shell\') resolves the alias and returns a Parser',
    () async {
      final parser = await TreeSitterLanguagePackBridge.getParser('shell');
      expect(parser, isNotNull);
    },
  );

  test(
    'has_language(\'shell\') returns true via alias resolution to \'bash\'',
    () async {
      final result = await TreeSitterLanguagePackBridge.hasLanguage('shell');
      expect(result, isTrue);
    },
  );

  test('has_language(\'nonexistent\') should return false', () async {
    final result = await TreeSitterLanguagePackBridge.hasLanguage(
      'nonexistent',
    );
    expect(result, isFalse);
  });

  test('has_language(\'python\') should return true', () async {
    final result = await TreeSitterLanguagePackBridge.hasLanguage('python');
    expect(result, isTrue);
  });

  test(
    'language_count returns the number of languages available in the current build/cache',
    () async {
      final result = await TreeSitterLanguagePackBridge.languageCount();
      expect(result, greaterThanOrEqualTo(1));
    },
  );

  test('available_languages should return a non-empty list', () async {
    final result = await TreeSitterLanguagePackBridge.availableLanguages();
    expect(result.toString(), isNotEmpty);
  });
}
