// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da1db2e19b303427ea44851adf6f3271951b5b176929f4a8f8a964af78f4a84f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: parsing
package e2e_test

import (
	"encoding/base64"
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

func Test_ParsingGoFunction(t *testing.T) {
	// Parse a Go function declaration and assert node type
	sourceBytes, _ := base64.StdEncoding.DecodeString(`package main
func main() {}`)
	_, err := tspack.ParseString(`go`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingHtmlElement(t *testing.T) {
	// Parse an HTML element and assert node type
	sourceBytes, _ := base64.StdEncoding.DecodeString(`<div>hello</div>`)
	_, err := tspack.ParseString(`html`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingJavascriptClass(t *testing.T) {
	// Parse a JavaScript class declaration.
	sourceBytes, _ := base64.StdEncoding.DecodeString(`class Foo { bar() {} }`)
	_, err := tspack.ParseString(`javascript`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingJavascriptVariable(t *testing.T) {
	// Parse a JavaScript variable declaration and assert node type
	sourceBytes, _ := base64.StdEncoding.DecodeString(`const x = 1;`)
	_, err := tspack.ParseString(`javascript`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingPythonFunction(t *testing.T) {
	// Parse a Python function definition and assert node type
	sourceBytes, _ := base64.StdEncoding.DecodeString(`def hello(): pass`)
	_, err := tspack.ParseString(`python`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingRustFunction(t *testing.T) {
	// Parse a Rust function definition and assert node type
	sourceBytes, _ := base64.StdEncoding.DecodeString(`fn main() {}`)
	_, err := tspack.ParseString(`rust`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ParsingRustStruct(t *testing.T) {
	// Parse a Rust struct definition.
	sourceBytes, _ := base64.StdEncoding.DecodeString(`struct Point { x: f64, y: f64 }`)
	_, err := tspack.ParseString(`rust`, sourceBytes)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
